/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_bv.h"
#include "cblas_f77_bv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_snrm2_sub_bv_base(...); */
/* Note: This should match the signature of snrm2_sub_bv in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */


/*
  Differentiation of cblas_snrm2 in reverse (adjoint) mode (with options multiDirectional):
   gradient     of useful results: cblas_snrm2 *X
   with respect to varying inputs: *X
   RW status of diff variables: cblas_snrm2:in-killed X:(loc)
                *X:incr
*/
void cblas_snrm2_bv(const __int32_t N, const float *X, float (*Xb)[NBDirsMax],
        const __int32_t incX, float cblas_snrm2b[NBDirsMax], int nbdirs) {
    float nrm2;
    float nrm2b[NBDirsMax];
    int32_t F77_N;
    int nd;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    for (nd = 0; nd < nbdirs; ++nd)
        nrm2b[nd] = cblas_snrm2b[nd];
    F77_snrm2sub_bv(&F77_N, X, Xb, &F77_incX, &nrm2, &nrm2b, &nbdirs);
}
