/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dnrm2_sub_b_base(...); */
/* Note: This should match the signature of dnrm2_sub_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */


/*
  Differentiation of cblas_dnrm2 in reverse (adjoint) mode:
   gradient     of useful results: cblas_dnrm2 *X
   with respect to varying inputs: *X
   RW status of diff variables: cblas_dnrm2:in-killed X:(loc)
                *X:incr
*/
void cblas_dnrm2_b(const __int32_t N, const double *X, double *Xb, const 
        __int32_t incX, double cblas_dnrm2b) {
    double nrm2;
    double nrm2b;
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    nrm2b = cblas_dnrm2b;
    F77_dnrm2sub_b(&F77_N, X, Xb, &F77_incX, &nrm2, &nrm2b);
}
