/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dspmv_b_base(..., (size_t)1); */
/* Note: This should match the signature of dspmv_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_dspmv_b_base F77_GLOBAL_SUFFIX(dspmv_b,DSPMV_B)
#define F77_dspmv_b(...) F77_dspmv_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_dspmv in reverse (adjoint) mode:
   gradient     of useful results: *Y
   with respect to varying inputs: alpha beta *X *Y *AP
   RW status of diff variables: alpha:out beta:out X:(loc) *X:out
                Y:(loc) *Y:in-out AP:(loc) *AP:out
*/
void cblas_dspmv_b(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const double alpha, double *alphab, const double *AP, 
        double *APb, const double *X, double *Xb, const __int32_t incX, const 
        double beta, double *betab, double *Y, double *Yb, const __int32_t 
        incY) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int branch;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'U';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'L';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (betab)
                *betab = 0.0;
            if (Xb)
                *Xb = 0.0;
            if (APb)
                *APb = 0.0;
            goto label100;
        }
        F77_dspmv_b(&UL, &F77_N, &alpha, &(*alphab), AP, APb, X, Xb, &F77_incX, &
                 beta, &(*betab), Y, Yb, &F77_incY, (size_t)1);
        popControl1b(&branch);
    } else if (layout == CblasRowMajor) {
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'U';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (betab)
                *betab = 0.0;
            if (Xb)
                *Xb = 0.0;
            if (APb)
                *APb = 0.0;
            goto label100;
        }
        F77_dspmv_b(&UL, &F77_N, &alpha, &(*alphab), AP, APb, X, Xb, &F77_incX, &
                 beta, &(*betab), Y, Yb, &F77_incY, (size_t)1);
        popControl1b(&branch);
    } else {
        if (alphab)
            *alphab = 0.0;
        if (betab)
            *betab = 0.0;
        if (Xb)
            *Xb = 0.0;
        if (APb)
            *APb = 0.0;
    }
  label100:
    ;
}
