/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_ztbmv_dv_base(...); */
/* Note: This should match the signature of ztbmv_dv in Fortran */


/*
  Differentiation of cblas_ztbmv in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *X
   with respect to varying inputs: *A *X
   RW status of diff variables: A:(loc) *A:in X:(loc) *X:in-out
   Plus diff mem management of: X:in
*/
void cblas_ztbmv_dv(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const __int32_t N, 
        const __int32_t K, const void *A, const void *Ad, const __int32_t lda,
        void *X, void *Xd, const __int32_t incX, int nbdirs) {
    char TA;
    char UL;
    char DI;
    int32_t F77_N;
    int nd;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_K;
    F77_K = K;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t n;
    int32_t i;
    i = 0;
    int32_t tincX;
    double *st;
    st = 0;
    double *x;
    double *xd[NBDirsMax];
    for (nd = 0; nd < nbdirs; ++nd) xd[nd] = (double *)Xd + nd;
    x = (double *)X;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_ztbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(3, "cblas_ztbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_ztbmv", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ztbmv_dv((double complex *)&UL, &TA, (double complex *)&DI, &F77_N, &F77_K, (double complex *)A, (double complex *)Ad, &F77_lda, (double complex *)X, (double complex *)Xd, &
                  F77_incX, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_ztbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans) {
            TA = 'N';
            if (N > 0) {
                if (incX > 0)
                    tincX = incX;
                else
                    tincX = -incX;
                i = tincX << 1;
                n = i*N;
                for (nd = 0; nd < nbdirs; ++nd) xd[nd] += NBDirsMax;
                x++;
                st = x + n;
                do {
                    for (nd = 0; nd < nbdirs; ++nd)
                        *xd[nd] = -*xd[nd];
                    *x = -*x;
                    for (nd = 0; nd < nbdirs; ++nd) xd[nd] += i*NBDirsMax;
                    x += i;
                } while(x != st);
                for (nd = 0; nd < nbdirs; ++nd) xd[nd] -= n*NBDirsMax;
                x -= n;
            }
        } else {
            cblas_xerbla(3, "cblas_ztbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_ztbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ztbmv_dv((double complex *)&UL, &TA, (double complex *)&DI, &F77_N, &F77_K, (double complex *)A, (double complex *)Ad, &F77_lda, (double complex *)X, (double complex *)Xd, &
                  F77_incX, &nbdirs, (size_t)1, (size_t)1);
        if (TransA == CblasConjTrans)
            if (N > 0)
                do {
                    for (nd = 0; nd < nbdirs; ++nd)
                        *xd[nd] = -*xd[nd];
                    *x = -*x;
                    for (nd = 0; nd < nbdirs; ++nd) xd[nd] += i*NBDirsMax;
                    x += i;
                } while(x != st);
    } else
        cblas_xerbla(1, "cblas_ztbmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
