/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_cgemm_d_base(...); */
/* Note: This should match the signature of cgemm_d in Fortran */


/*
  Differentiation of cblas_cgemm in forward (tangent) mode:
   variations   of useful results: *C
   with respect to varying inputs: *alpha *A *B *C *beta
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in B:(loc) *B:in C:(loc) *C:in-out beta:(loc)
                *beta:in
*/
void cblas_cgemm_d(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const CBLAS_TRANSPOSE TransB, const __int32_t M, const __int32_t N, 
        const __int32_t K, const void *alpha, const void *alphad, const void *
        A, const void *Ad, const __int32_t lda, const void *B, const void *Bd,
        const __int32_t ldb, const void *beta, const void *betad, void *C, 
        void *Cd, const __int32_t ldc) {
    char TA, TB;
    int32_t F77_M = M;
    int32_t F77_N = N;
    int32_t F77_K = K;
    int32_t F77_lda = lda;
    int32_t F77_ldb = ldb;
    int32_t F77_ldc = ldc;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else if (TransA == CblasNoTrans)
            TA = 'N';
        else {
            cblas_xerbla(2, "cblas_cgemm", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransB == CblasTrans)
            TB = 'T';
        else if (TransB == CblasConjTrans)
            TB = 'C';
        else if (TransB == CblasNoTrans)
            TB = 'N';
        else {
            cblas_xerbla(3, "cblas_cgemm", "Illegal TransB setting, %d\n", 
                         TransB);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_cgemm_d(&TA, &TB, &F77_M, &F77_N, &F77_K, alpha, alphad, A, Ad, &
                 F77_lda, B, Bd, &F77_ldb, beta, betad, C, Cd, &F77_ldc);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (TransA == CblasTrans)
            TB = 'T';
        else if (TransA == CblasConjTrans)
            TB = 'C';
        else if (TransA == CblasNoTrans)
            TB = 'N';
        else {
            cblas_xerbla(2, "cblas_cgemm", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransB == CblasTrans)
            TA = 'T';
        else if (TransB == CblasConjTrans)
            TA = 'C';
        else if (TransB == CblasNoTrans)
            TA = 'N';
        else {
            cblas_xerbla(2, "cblas_cgemm", "Illegal TransB setting, %d\n", 
                         TransB);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_cgemm_d(&TA, &TB, &F77_N, &F77_M, &F77_K, alpha, alphad, B, Bd, &
                 F77_ldb, A, Ad, &F77_lda, beta, betad, C, Cd, &F77_ldc);
    } else
        cblas_xerbla(1, "cblas_cgemm", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
