/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_bv.h"
#include "cblas_f77_bv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dswap_bv_base(...); */
/* Note: This should match the signature of dswap_bv in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_dswap_bv_base F77_GLOBAL_SUFFIX(dswap_bv,DSWAP_BV)
#define F77_dswap_bv(...) F77_dswap_bv_base(__VA_ARGS__)


/*
  Differentiation of cblas_dswap in reverse (adjoint) mode (with options multiDirectional):
   gradient     of useful results: *X *Y
   with respect to varying inputs: *X *Y
   RW status of diff variables: X:(loc) *X:in-out Y:(loc) *Y:in-out
*/
void cblas_dswap_bv(const __int32_t N, double *X, double (*Xb)[NBDirsMax], 
        const __int32_t incX, double *Y, double (*Yb)[NBDirsMax], const 
        __int32_t incY, int nbdirs) {
    int32_t F77_N;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    F77_dswap_bv(&F77_N, X, Xb, &F77_incX, Y, Yb, &F77_incY, &nbdirs);
}
