/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_strmv_d_base(...); */
/* Note: This should match the signature of strmv_d in Fortran */


/*
  Differentiation of cblas_strmv in forward (tangent) mode:
   variations   of useful results: *X
   with respect to varying inputs: *A *X
   RW status of diff variables: A:(loc) *A:in X:(loc) *X:in-out
*/
void cblas_strmv_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const __int32_t N, 
        const float *A, const float *Ad, const __int32_t lda, float *X, float 
        *Xd, const __int32_t incX) {
    char TA;
    char UL;
    char DI;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_strmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(3, "cblas_strmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_strmv", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_strmv_d(&UL, &TA, &DI, &F77_N, A, Ad, &F77_lda, X, Xd, &F77_incX);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_strmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans)
            TA = 'N';
        else {
            cblas_xerbla(3, "cblas_strmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_strmv", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_strmv_d(&UL, &TA, &DI, &F77_N, A, Ad, &F77_lda, X, Xd, &F77_incX);
    } else
        cblas_xerbla(1, "cblas_strmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
