/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_ssymm_dv_base(...); */
/* Note: This should match the signature of ssymm_dv in Fortran */


/*
  Differentiation of cblas_ssymm in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *C
   with respect to varying inputs: alpha *A *B *C beta
   RW status of diff variables: alpha:in A:(loc) *A:in B:(loc)
                *B:in C:(loc) *C:in-out beta:in
*/
void cblas_ssymm_dv(const CBLAS_LAYOUT layout, const CBLAS_SIDE Side, const 
        CBLAS_UPLO Uplo, const __int32_t M, const __int32_t N, const float 
        alpha, const float alphad[NBDirsMax], const float *A, const float (*Ad
        )[NBDirsMax], const __int32_t lda, const float *B, const float (*Bd)[
        NBDirsMax], const __int32_t ldb, const float beta, const float betad[
        NBDirsMax], float *C, float (*Cd)[NBDirsMax], const __int32_t ldc, int
        nbdirs) {
    char SD, UL;
    int32_t F77_M;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_ldb;
    F77_ldb = ldb;
    int32_t F77_ldc;
    F77_ldc = ldc;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Side == CblasRight)
            SD = 'R';
        else if (Side == CblasLeft)
            SD = 'L';
        else {
            cblas_xerbla(2, "cblas_ssymm", "Illegal Side setting, %d\n", Side)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(3, "cblas_ssymm", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ssymm_dv((float *)&SD, (float *)&UL, &F77_M, &F77_N, (float *)&alpha, (float *)alphad, (float *)A, (float *)Ad, &F77_lda, (float *)B, (float *)Bd, &F77_ldb, (float *)&beta, (float *)betad, (float *)C, (float *)Cd, &F77_ldc, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Side == CblasRight)
            SD = 'L';
        else if (Side == CblasLeft)
            SD = 'R';
        else {
            cblas_xerbla(2, "cblas_ssymm", "Illegal Side setting, %d\n", Side)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(3, "cblas_ssymm", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ssymm_dv((float *)&SD, (float *)&UL, &F77_N, &F77_M, (float *)&alpha, (float *)alphad, (float *)A, (float *)Ad, &F77_lda, (float *)B, (float *)Bd, &F77_ldb, (float *)&beta, (float *)betad, (float *)C, (float *)Cd, &F77_ldc, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_ssymm", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
