/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dspr2_d_base(...); */
/* Note: This should match the signature of dspr2_d in Fortran */


/*
  Differentiation of cblas_dspr2 in forward (tangent) mode:
   variations   of useful results: *A
   with respect to varying inputs: alpha *X *Y
   RW status of diff variables: alpha:in A:(loc) *A:out X:(loc)
                *X:in Y:(loc) *Y:in
*/
void cblas_dspr2_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const double alpha, const double alphad, const double *X,
        const double *Xd, const __int32_t incX, const double *Y, const double 
        *Yd, const __int32_t incY, double *A, double *Ad) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasLower)
            UL = 'L';
        else if (Uplo == CblasUpper)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_dspr2", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            if (Ad)
                *Ad = 0.0;
            return;
        }
        F77_dspr2_d(&UL, &F77_N, &alpha, &alphad, X, Xd, &F77_incX, Y, Yd, &
                 F77_incY, A, Ad);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasLower)
            UL = 'U';
        else if (Uplo == CblasUpper)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_dspr2", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            if (Ad)
                *Ad = 0.0;
            return;
        }
        F77_dspr2_d(&UL, &F77_N, &alpha, &alphad, X, Xd, &F77_incX, Y, Yd, &
                 F77_incY, A, Ad);
    } else {
        cblas_xerbla(1, "cblas_dspr2", "Illegal layout setting, %d\n", layout)
        ;
        if (Ad)
            *Ad = 0.0;
    }
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
