/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include <stdio.h>
#include <stdlib.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_chemv_d_base(...); */
/* Note: This should match the signature of chemv_d in Fortran */


/*
  Differentiation of cblas_chemv in forward (tangent) mode:
   variations   of useful results: *Y
   with respect to varying inputs: *alpha *A *beta *X *Y
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in beta:(loc) *beta:in X:(loc) *X:in Y:(loc)
                *Y:in-out
   Plus diff mem management of: alpha:in beta:in X:in Y:in
*/
void cblas_chemv_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const void *alpha, const void *alphad, const void *A, 
        const void *Ad, const __int32_t lda, const void *X, const void *Xd, 
        const __int32_t incX, const void *beta, const void *betad, void *Y, 
        void *Yd, const __int32_t incY) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    int32_t n = 0;
    int32_t i = 0;
    int32_t incx = incX;
    const float *xx = (float *)X, *alp = (float *)alpha, *bet = (float *)beta;
    float ALPHA[2], BETA[2];
    float ALPHAd[2], BETAd[2];
    int32_t tincY, tincx;
    float *x = (float *)X;
    float *xd = (float *)Xd;
    float *y = (float *)Y;
    float *yd = (float *)Yd;
    float *st = 0;
    float *std;
    float *tx;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int ii1;
    const float *alpd;
    const float *betd;
    const float *xxd;
    float *txd;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_chemv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_chemv_d(&UL, &F77_N, alpha, alphad, A, Ad, &F77_lda, X, Xd, &F77_incX
                 , beta, betad, Y, Yd, &F77_incY);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        for (ii1 = 0; ii1 < 2; ++ii1)
            ALPHAd[ii1] = 0.0;
        ALPHAd[0] = *alpd;
        ALPHA[0] = *alp;
        ALPHAd[1] = -alpd[1];
        ALPHA[1] = -alp[1];
        for (ii1 = 0; ii1 < 2; ++ii1)
            BETAd[ii1] = 0.0;
        BETAd[0] = *betd;
        BETA[0] = *bet;
        BETAd[1] = -betd[1];
        BETA[1] = -bet[1];
        if (N > 0) {
            n = N << 1;
            xd = (float *)malloc(n*sizeof(float));
            x = (float *)malloc(n*sizeof(float));
            tx = x;
            if (incX > 0) {
                i = incX << 1;
                tincx = 2;
                st = x + n;
            } else {
                i = incX*-2;
                tincx = -2;
                st = x - 2;
                xd = xd + (n - 2);
                x += n - 2;
            }
            do {
                *xd = *xxd;
                *x = *xx;
                xd[1] = -xxd[1];
                x[1] = -xx[1];
                xd = xd + tincx;
                x += tincx;
                xxd = xxd + i;
                xx += i;
            } while(x != st);
            xd = txd;
            x = tx;
            F77_incX = 1;
            if (incY > 0)
                tincY = incY;
            else
                tincY = -incY;
            yd++;
            y++;
            i = tincY << 1;
            n = i*N;
            st = y + n;
            do {
                *yd = -*yd;
                *y = -*y;
                yd = yd + i;
                y += i;
            } while(y != st);
            yd = yd - n;
            y -= n;
        } else {
            xd = (float *)Xd;
            x = (float *)X;
        }
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_chemv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_chemv_d(&UL, &F77_N, ALPHA, ALPHAd, A, Ad, &F77_lda, x, xd, &F77_incX
                 , BETA, BETAd, Y, Yd, &F77_incY);
    } else {
        cblas_xerbla(1, "cblas_chemv", "Illegal layout setting, %d\n", layout)
        ;
        CBLAS_CallFromC = 0;
        RowMajorStrg = 0;
        return;
    }
    if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (X != x) {
            free(xd);
            free(x);
        }
        if (N > 0)
            do {
                *yd = -*yd;
                *y = -*y;
                yd = yd + i;
                y += i;
            } while(y != st);
    }
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
