/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sgbmv_d_base(...); */
/* Note: This should match the signature of sgbmv_d in Fortran */


/*
  Differentiation of cblas_sgbmv in forward (tangent) mode:
   variations   of useful results: *Y
   with respect to varying inputs: alpha *A beta *X *Y
   RW status of diff variables: alpha:in A:(loc) *A:in beta:in
                X:(loc) *X:in Y:(loc) *Y:in-out
*/
void cblas_sgbmv_d(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const __int32_t M, const __int32_t N, const __int32_t KL, const 
        __int32_t KU, const float alpha, const float alphad, const float *A, 
        const float *Ad, const __int32_t lda, const float *X, const float *Xd,
        const __int32_t incX, const float beta, const float betad, float *Y, 
        float *Yd, const __int32_t incY) {
    char TA;
    int32_t F77_M = M;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    int32_t F77_KL = KL;
    int32_t F77_KU = KU;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(2, "cblas_sgbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_sgbmv_d(&TA, &F77_M, &F77_N, &F77_KL, &F77_KU, &alpha, &alphad, A, Ad
                 , &F77_lda, X, Xd, &F77_incX, &beta, &betad, Y, Yd, &F77_incY
                );
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans)
            TA = 'N';
        else {
            cblas_xerbla(2, "cblas_sgbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_sgbmv_d(&TA, &F77_N, &F77_M, &F77_KU, &F77_KL, &alpha, &alphad, A, Ad
                 , &F77_lda, X, Xd, &F77_incX, &beta, &betad, Y, Yd, &F77_incY
                );
    } else
        cblas_xerbla(1, "cblas_sgbmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
