/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_ssyr_dv_base(...); */
/* Note: This should match the signature of ssyr_dv in Fortran */


/*
  Differentiation of cblas_ssyr in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *A
   with respect to varying inputs: alpha *A *X
   RW status of diff variables: alpha:in A:(loc) *A:in-out X:(loc)
                *X:in
*/
void cblas_ssyr_dv(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const float alpha, const float alphad[NBDirsMax], const 
        float *X, const float (*Xd)[NBDirsMax], const __int32_t incX, float *A
        , float (*Ad)[NBDirsMax], const __int32_t lda, int nbdirs) {
    char UL;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_lda;
    F77_lda = lda;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasLower)
            UL = 'L';
        else if (Uplo == CblasUpper)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_ssyr", "Illegal Uplo setting, %d\n", Uplo);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ssyr_dv((float *)&UL, &F77_N, (float *)&alpha, (float *)alphad, (float *)X, (float *)Xd, &F77_incX, (float *)A, (float *)Ad, &
                 F77_lda, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasLower)
            UL = 'U';
        else if (Uplo == CblasUpper)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_ssyr", "Illegal Uplo setting, %d\n", Uplo);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ssyr_dv((float *)&UL, &F77_N, (float *)&alpha, (float *)alphad, (float *)X, (float *)Xd, &F77_incX, (float *)A, (float *)Ad, &
                 F77_lda, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_ssyr", "Illegal layout setting, %d\n", layout);
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
