/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <stdio.h>
#include <stdlib.h>

/* Declaration for differentiated Fortran routine */
/* void F77_chbmv_b_base(..., (size_t)1); */
/* Note: This should match the signature of chbmv_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_chbmv_b_base F77_GLOBAL_SUFFIX(chbmv_b,CHBMV_B)
#define F77_chbmv_b(...) F77_chbmv_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_chbmv in reverse (adjoint) mode:
   gradient     of useful results: *Y
   with respect to varying inputs: *alpha *A *beta *X *Y
   RW status of diff variables: alpha:(loc) *alpha:out A:(loc)
                *A:out beta:(loc) *beta:out X:(loc) *X:out Y:(loc)
                *Y:in-out
   Plus diff mem management of: alpha:in beta:in X:in Y:in
*/
void cblas_chbmv_b(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const __int32_t K, const void *alpha, void *alphab, const
        void *A, void *Ab, const __int32_t lda, const void *X, void *Xb, const
        __int32_t incX, const void *beta, void *betab, void *Y, void *Yb, 
        const __int32_t incY) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_K = K;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    int32_t n;
    int32_t i = 0;
    int32_t incx = incX;
    const float *xx = (float *)X, *alp = (float *)alpha, *bet = (float *)beta;
    float ALPHA[2], BETA[2];
    float ALPHAb[2], BETAb[2];
    int32_t tincY, tincx;
    float *x = (void *)0;
    float *xb = (float *)Xb;
    float *y = (float *)Y;
    float *yb = (float *)Yb;
    float *st = 0;
    float *stb = (void *)0;
    float *tx;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    float *alpb;
    float *betb;
    int ii1;
    float *xxb;
    float *txb;
    int adCount;
    int i0;
    int adCount0;
    int i1;
    int adCount1;
    int i2;
    int branch;
    if (layout == CblasColMajor) {
        if (Uplo == CblasLower) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasUpper) {
            pushControl1b(1);
            UL = 'U';
        } else {
            if (alphab)
                *((float complex *)alphab) = 0;
            if (Ab)
                *((float complex *)Ab) = 0;
            if (betab)
                *((float complex *)betab) = 0;
            if (Xb)
                *((float complex *)Xb) = 0;
            goto label110;
        }
        pushControl1b(0);
    } else if (layout == CblasRowMajor) {
        ALPHA[0] = *alp;
        ALPHA[1] = -alp[1];
        BETA[0] = *bet;
        BETA[1] = -bet[1];
        if (N > 0) {
            n = N << 1;
            xb = (float *)malloc(n*sizeof(float));
            for (ii1 = 0; ii1 < n; ++ii1)
                xb[ii1] = 0.0;
            x = (float *)malloc(n*sizeof(float));
            if (incX > 0) {
                pushControl1b(1);
                i = incX << 1;
                tincx = 2;
                st = x + n;
            } else {
                i = incX*-2;
                tincx = -2;
                st = x - 2;
                pushPointer8(xb);
                xb = xb + (n - 2);
                pushPointer8(x);
                x = x + (n - 2);
                pushControl1b(0);
            }
            adCount = 0;
            do {
                *x = *xx;
                x[1] = -xx[1];
                pushPointer8(xb);
                xb = xb + tincx;
                pushPointer8(x);
                x = x + tincx;
                pushPointer8(xxb);
                xxb = xxb + i;
                xx = xx + i;
                adCount = adCount + 1;
            } while(x != st);
            pushInteger4(adCount);
            pushPointer8(xb);
            xb = txb;
            F77_incX = 1;
            if (incY > 0)
                tincY = incY;
            else
                tincY = -incY;
            yb++;
            y++;
            i = tincY << 1;
            n = i*N;
            st = y + n;
            adCount0 = 0;
            do {
                *y = -*y;
                pushPointer8(yb);
                yb = yb + i;
                y = y + i;
                adCount0 = adCount0 + 1;
            } while(y != st);
            pushInteger4(adCount0);
            pushControl1b(0);
            yb = yb - n;
            y = y - n;
        } else {
            pushControl1b(1);
            xb = (float *)Xb;
        }
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'U';
        } else {
            if (Ab)
                *((float complex *)Ab) = 0;
            if (Xb)
                *((float complex *)Xb) = 0;
            for (ii1 = 0; ii1 < 2; ++ii1)
                ALPHAb[ii1] = 0.0;
            for (ii1 = 0; ii1 < 2; ++ii1)
                BETAb[ii1] = 0.0;
            goto label100;
        }
        pushControl1b(1);
    } else {
        if (alphab)
            *((float complex *)alphab) = 0;
        if (Ab)
            *((float complex *)Ab) = 0;
        if (betab)
            *((float complex *)betab) = 0;
        if (Xb)
            *((float complex *)Xb) = 0;
        goto label110;
    }
    if (layout == CblasRowMajor)
        if (N > 0) {
            adCount1 = 0;
            do {
                pushPointer8(yb);
                yb = yb + i;
                pushPointer8(y);
                y = y + i;
                adCount1 = adCount1 + 1;
            } while(y != st);
            pushInteger4(adCount1);
            popInteger4(&adCount1);
            for (i2 = 1; i2 < adCount1+1; ++i2) {
                popPointer8((void **)&y);
                popPointer8((void **)&yb);
                *yb = -*yb;
            }
        }
    popControl1b(&branch);
    if (branch == 0) {
        F77_chbmv_b(&UL, &F77_N, &F77_K, alpha, alphab, A, Ab, &F77_lda, X, Xb, &
                 F77_incX, beta, betab, Y, Yb, &F77_incY, (size_t)1);
        popControl1b(&branch);
        goto label110;
    } else {
        F77_chbmv_b(&UL, &F77_N, &F77_K, ALPHA, ALPHAb, A, Ab, &F77_lda, x, xb, &
                 F77_incX, BETA, BETAb, Y, Yb, &F77_incY, (size_t)1);
        popControl1b(&branch);
    }
  label100:
    popControl1b(&branch);
    if (branch == 0) {
        popInteger4(&adCount0);
        for (i1 = 1; i1 < adCount0+1; ++i1) {
            popPointer8((void **)&yb);
            *yb = -*yb;
        }
        --y;
        --yb;
        popPointer8((void **)&xb);
        popInteger4(&adCount);
        for (i0 = 1; i0 < adCount+1; ++i0) {
            popPointer8((void **)&xxb);
            popPointer8((void **)&x);
            popPointer8((void **)&xb);
            xxb[1] = xxb[1] - xb[1];
            xb[1] = 0.0;
            *xxb = *xxb + *xb;
            *((float complex *)xb) = 0;
        }
        popControl1b(&branch);
        if (branch == 0) {
            popPointer8((void **)&x);
            popPointer8((void **)&xb);
        }
        free(x);
        free(xb);
    }
    if (betab)
        *((float complex *)betab) = 0;
    betb[1] = betb[1] - BETAb[1];
    BETAb[1] = 0.0;
    *betb = *betb + BETAb[0];
    if (alphab)
        *((float complex *)alphab) = 0;
    alpb[1] = alpb[1] - ALPHAb[1];
    ALPHAb[1] = 0.0;
    *alpb = *alpb + ALPHAb[0];
  label110:
    ;
}
