/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dsymv_dv_base(...); */
/* Note: This should match the signature of dsymv_dv in Fortran */


/*
  Differentiation of cblas_dsymv in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *Y
   with respect to varying inputs: alpha *A beta *X *Y
   RW status of diff variables: alpha:in A:(loc) *A:in beta:in
                X:(loc) *X:in Y:(loc) *Y:in-out
*/
void cblas_dsymv_dv(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const double alpha, const double alphad[NBDirsMax], const
        double *A, const double (*Ad)[NBDirsMax], const __int32_t lda, const 
        double *X, const double (*Xd)[NBDirsMax], const __int32_t incX, const 
        double beta, const double betad[NBDirsMax], double *Y, double (*Yd)[
        NBDirsMax], const __int32_t incY, int nbdirs) {
    char UL;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_dsymv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_dsymv_dv((double *)&UL, &F77_N, (double *)&alpha, (double *)alphad, (double *)A, (double *)Ad, &F77_lda, (double *)X, (double *)Xd, &
                  F77_incX, (double *)&beta, (double *)betad, (double *)Y, (double *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_dsymv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_dsymv_dv((double *)&UL, &F77_N, (double *)&alpha, (double *)alphad, (double *)A, (double *)Ad, &F77_lda, (double *)X, (double *)Xd, &
                  F77_incX, (double *)&beta, (double *)betad, (double *)Y, (double *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_dsymv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
