/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_cdotc_sub_b_base(...); */
/* Note: This should match the signature of cdotc_sub_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */


/*
  Differentiation of cblas_cdotc_sub in reverse (adjoint) mode:
   gradient     of useful results: *dotc
   with respect to varying inputs: *dotc *X *Y
   RW status of diff variables: dotc:(loc) *dotc:in-out X:(loc)
                *X:out Y:(loc) *Y:out
*/
void cblas_cdotc_sub_b(const __int32_t N, const void *X, void *Xb, const 
        __int32_t incX, const void *Y, void *Yb, const __int32_t incY, void *
        dotc, void *dotcb) {
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    F77_cdotcsub_b(&F77_N, X, Xb, &F77_incX, Y, Yb, &F77_incY, dotc, dotcb);
}
