/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dsymm_b_base(..., (size_t)1, (size_t)1); */
/* Note: This should match the signature of dsymm_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_dsymm_b_base F77_GLOBAL_SUFFIX(dsymm_b,DSYMM_B)
#define F77_dsymm_b(...) F77_dsymm_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_dsymm in reverse (adjoint) mode:
   gradient     of useful results: *C
   with respect to varying inputs: alpha *A *B *C beta
   RW status of diff variables: alpha:out A:(loc) *A:out B:(loc)
                *B:out C:(loc) *C:in-out beta:out
*/
void cblas_dsymm_b(const CBLAS_LAYOUT layout, const CBLAS_SIDE Side, const 
        CBLAS_UPLO Uplo, const __int32_t M, const __int32_t N, const double 
        alpha, double *alphab, const double *A, double *Ab, const __int32_t 
        lda, const double *B, double *Bb, const __int32_t ldb, const double 
        beta, double *betab, double *C, double *Cb, const __int32_t ldc) {
    char SD, UL;
    int32_t F77_M = M;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_ldb = ldb;
    int32_t F77_ldc = ldc;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int branch;
    if (layout == CblasColMajor) {
        if (Side == CblasRight) {
            pushControl1b(0);
            SD = 'R';
        } else if (Side == CblasLeft) {
            pushControl1b(1);
            SD = 'L';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (Ab)
                *Ab = 0.0;
            if (Bb)
                *Bb = 0.0;
            if (betab)
                *betab = 0.0;
            goto label120;
        }
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'U';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'L';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (Ab)
                *Ab = 0.0;
            if (Bb)
                *Bb = 0.0;
            if (betab)
                *betab = 0.0;
            goto label100;
        }
        F77_dsymm_b(&SD, &UL, &F77_M, &F77_N, &alpha, &(*alphab), A, Ab, &F77_lda
                 , B, Bb, &F77_ldb, &beta, &(*betab), C, Cb, &F77_ldc, (size_t)1, (size_t)1);
        popControl1b(&branch);
      label100:
        popControl1b(&branch);
    } else if (layout == CblasRowMajor) {
        if (Side == CblasRight) {
            pushControl1b(0);
            SD = 'L';
        } else if (Side == CblasLeft) {
            pushControl1b(1);
            SD = 'R';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (Ab)
                *Ab = 0.0;
            if (Bb)
                *Bb = 0.0;
            if (betab)
                *betab = 0.0;
            goto label120;
        }
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'U';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (Ab)
                *Ab = 0.0;
            if (Bb)
                *Bb = 0.0;
            if (betab)
                *betab = 0.0;
            goto label110;
        }
        F77_dsymm_b(&SD, &UL, &F77_N, &F77_M, &alpha, &(*alphab), A, Ab, &F77_lda
                 , B, Bb, &F77_ldb, &beta, &(*betab), C, Cb, &F77_ldc, (size_t)1, (size_t)1);
        popControl1b(&branch);
      label110:
        popControl1b(&branch);
    } else {
        if (alphab)
            *alphab = 0.0;
        if (Ab)
            *Ab = 0.0;
        if (Bb)
            *Bb = 0.0;
        if (betab)
            *betab = 0.0;
    }
  label120:
    ;
}
