C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of saxpy in reverse (adjoint) mode (with options multiDirectional):
C   gradient     of useful results: sa sx sy
C   with respect to varying inputs: sa sx sy
C> \brief \b SAXPY
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE SAXPY(N,SA,SX,INCX,SY,INCY)
C
C       .. Scalar Arguments ..
C       REAL SA
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       REAL SX(*),SY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C>    SAXPY constant times a vector plus a vector.
C>    uses unrolled loops for increments equal to one.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in] SA
C> \verbatim
C>          SA is REAL
C>           On entry, SA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] SX
C> \verbatim
C>          SX is REAL array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of SX
C> \endverbatim
C>
C> \param[in,out] SY
C> \verbatim
C>          SY is REAL array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of SY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup axpy
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, linpack, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE SAXPY_BV(n, sa, sab, sx, sxb, incx, sy, syb, incy, 
     +                    nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZESF.inc'
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      REAL sa
      REAL sab(nbdirsmax)
      INTEGER incx, incy, n, nbdirs
C     ..
C     .. Array Arguments ..
      REAL sx(*), sy(*)
      REAL sxb(nbdirsmax, *), syb(nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      INTEGER i, ix, iy, m, mp1
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MOD
      INTEGER nd
      INTEGER*4 branch
C     ..
      IF (n .GT. 0) THEN
        IF (sa .NE. 0.0) THEN
          IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C        code for both increments equal to 1
C
C
C        clean-up loop
C
            m = MOD(n, 4)
            IF (m .NE. 0) THEN
              CALL PUSHCONTROL1B(0)
            ELSE
              CALL PUSHCONTROL1B(1)
            END IF
            IF (n .GE. 4) THEN
              mp1 = m + 1
              DO i=n-MOD(n-mp1, 4),mp1,-4
                DO nd=1,nbdirs
                  sab(nd) = sab(nd) + sx(i+3)*syb(nd, i+3) + sx(i+2)*syb
     +              (nd, i+2) + sx(i+1)*syb(nd, i+1) + sx(i)*syb(nd, i)
                  sxb(nd, i+3) = sxb(nd, i+3) + sa*syb(nd, i+3)
                  sxb(nd, i+2) = sxb(nd, i+2) + sa*syb(nd, i+2)
                  sxb(nd, i+1) = sxb(nd, i+1) + sa*syb(nd, i+1)
                  sxb(nd, i) = sxb(nd, i) + sa*syb(nd, i)
                ENDDO
              ENDDO
            END IF
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              DO i=m,1,-1
                DO nd=1,nbdirs
                  sab(nd) = sab(nd) + sx(i)*syb(nd, i)
                  sxb(nd, i) = sxb(nd, i) + sa*syb(nd, i)
                ENDDO
              ENDDO
            END IF
          ELSE
C
C        code for unequal increments or equal increments
C          not equal to 1
C
            ix = 1
            iy = 1
            IF (incx .LT. 0) ix = (-n+1)*incx + 1
            IF (incy .LT. 0) iy = (-n+1)*incy + 1
            DO i=1,n
              CALL PUSHINTEGER4(ix)
              ix = ix + incx
              CALL PUSHINTEGER4(iy)
              iy = iy + incy
            ENDDO
            DO i=n,1,-1
              CALL POPINTEGER4(iy)
              CALL POPINTEGER4(ix)
              DO nd=1,nbdirs
                sab(nd) = sab(nd) + sx(ix)*syb(nd, iy)
                sxb(nd, ix) = sxb(nd, ix) + sa*syb(nd, iy)
              ENDDO
            ENDDO
          END IF
        END IF
      END IF
      END

