/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dspr_d_base(...); */
/* Note: This should match the signature of dspr_d in Fortran */


/*
  Differentiation of cblas_dspr in forward (tangent) mode:
   variations   of useful results: *Ap
   with respect to varying inputs: alpha *X
   RW status of diff variables: alpha:in Ap:(loc) *Ap:out X:(loc)
                *X:in
*/
void cblas_dspr_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const double alpha, const double alphad, const double *X,
        const double *Xd, const __int32_t incX, double *Ap, double *Apd) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasLower)
            UL = 'L';
        else if (Uplo == CblasUpper)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_dspr", "Illegal Uplo setting, %d\n", Uplo);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            if (Apd)
                *Apd = 0.0;
            return;
        }
        F77_dspr_d(&UL, &F77_N, &alpha, &alphad, X, Xd, &F77_incX, Ap, Apd);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasLower)
            UL = 'U';
        else if (Uplo == CblasUpper)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_dspr", "Illegal Uplo setting, %d\n", Uplo);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            if (Apd)
                *Apd = 0.0;
            return;
        }
        F77_dspr_d(&UL, &F77_N, &alpha, &alphad, X, Xd, &F77_incX, Ap, Apd);
    } else {
        cblas_xerbla(1, "cblas_dspr", "Illegal layout setting, %d\n", layout);
        if (Apd)
            *Apd = 0.0;
    }
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
