/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zswap_d_base(...); */
/* Note: This should match the signature of zswap_d in Fortran */


/*
  Differentiation of cblas_zswap in forward (tangent) mode:
   variations   of useful results: *X *Y
   with respect to varying inputs: *X *Y
   RW status of diff variables: X:(loc) *X:in-out Y:(loc) *Y:in-out
*/
void cblas_zswap_d(const __int32_t N, void *X, void *Xd, const __int32_t incX,
        void *Y, void *Yd, const __int32_t incY) {
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    F77_zswap_d(&F77_N, X, Xd, &F77_incX, Y, Yd, &F77_incY);
}
