/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sspr2_b_base(..., (size_t)1); */
/* Note: This should match the signature of sspr2_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_sspr2_b_base F77_GLOBAL_SUFFIX(sspr2_b,SSPR2_B)
#define F77_sspr2_b(...) F77_sspr2_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_sspr2 in reverse (adjoint) mode:
   gradient     of useful results: alpha *A *X *Y
   with respect to varying inputs: alpha *A *X *Y
   RW status of diff variables: alpha:incr A:(loc) *A:in-out X:(loc)
                *X:incr Y:(loc) *Y:incr
*/
void cblas_sspr2_b(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        __int32_t N, const float alpha, float *alphab, const float *X, float *
        Xb, const __int32_t incX, const float *Y, float *Yb, const __int32_t 
        incY, float *A, float *Ab) {
    char UL;
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int branch;
    if (layout == CblasColMajor) {
        if (Uplo == CblasLower) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasUpper) {
            pushControl1b(1);
            UL = 'U';
        } else
            goto label100;
        F77_sspr2_b(&UL, &F77_N, &alpha, &(*alphab), X, Xb, &F77_incX, Y, Yb, &
                 F77_incY, A, Ab, (size_t)1);
        popControl1b(&branch);
    } else if (layout == CblasRowMajor) {
        if (Uplo == CblasLower) {
            pushControl1b(0);
            UL = 'U';
        } else if (Uplo == CblasUpper) {
            pushControl1b(1);
            UL = 'L';
        } else
            goto label100;
        F77_sspr2_b(&UL, &F77_N, &alpha, &(*alphab), X, Xb, &F77_incX, Y, Yb, &
                 F77_incY, A, Ab, (size_t)1);
        popControl1b(&branch);
    }
  label100:
    ;
}
