/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include <stdio.h>
#include <stdlib.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zgbmv_dv_base(...); */
/* Note: This should match the signature of zgbmv_dv in Fortran */


/*
  Differentiation of cblas_zgbmv in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *Y
   with respect to varying inputs: *alpha *A *beta *X *Y
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in beta:(loc) *beta:in X:(loc) *X:in Y:(loc)
                *Y:in-out
   Plus diff mem management of: alpha:in beta:in X:in Y:in
*/
void cblas_zgbmv_dv(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const __int32_t M, const __int32_t N, const __int32_t KL, const 
        __int32_t KU, const void *alpha, const void *alphad, const void *A, 
        const void *Ad, const __int32_t lda, const void *X, const void *Xd, 
        const __int32_t incX, const void *beta, const void *betad, void *Y, 
        void *Yd, const __int32_t incY, int nbdirs) {
    char TA;
    int32_t F77_M;
    int ii1;
    int nd;
    const double (*alpd)[NBDirsMax];
    const double (*betd)[NBDirsMax];
    const double (*xxd)[NBDirsMax];
    double (*txd)[NBDirsMax];
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    int32_t F77_KL;
    F77_KL = KL;
    int32_t F77_KU;
    F77_KU = KU;
    int32_t n;
    int32_t i;
    i = 0;
    int32_t incx;
    incx = incX;
    const double *xx = (double *)X, *alp = (double *)alpha, *bet = (double *)
    beta;
    double ALPHA[2], BETA[2];
    double ALPHAd[2][NBDirsMax], BETAd[2][NBDirsMax];
    int32_t tincY, tincx;
    double *x;
    double *xd[NBDirsMax];
    x = (double *)X;
    double *y;
    double *yd[NBDirsMax];
    for (nd = 0; nd < nbdirs; ++nd) yd[nd] = (double *)Yd + nd;
    y = (double *)Y;
    double *st;
    double *std;
    st = 0;
    double *tx;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(2, "cblas_zgbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_zgbmv_dv(&TA, &F77_M, &F77_N, &F77_KL, &F77_KU, (double complex *)alpha, (double complex *)alphad, (double complex *)A, (double complex *)Ad, &F77_lda, (double complex *)X, (double complex *)Xd, &F77_incX, (double complex *)beta, (double complex *)betad, (double complex *)Y, (double complex *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (TransA == CblasNoTrans) {
            TA = 'T';
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    ALPHAd[ii1][nd] = 0.0;
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    BETAd[ii1][nd] = 0.0;
        } else if (TransA == CblasTrans) {
            TA = 'N';
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    ALPHAd[ii1][nd] = 0.0;
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    BETAd[ii1][nd] = 0.0;
        } else if (TransA == CblasConjTrans) {
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    ALPHAd[ii1][nd] = 0.0;
            for (ii1 = 0; ii1 < 2; ++ii1)
                for (nd = 0; nd < NBDirsMax; ++nd)
                    BETAd[ii1][nd] = 0.0;
            for (nd = 0; nd < nbdirs; ++nd) {
                ALPHAd[0][nd] = (*alpd)[nd];
                ALPHAd[1][nd] = -alpd[1][nd];
                BETAd[0][nd] = (*betd)[nd];
                BETAd[1][nd] = -betd[1][nd];
            }
            ALPHA[0] = *alp;
            ALPHA[1] = -alp[1];
            BETA[0] = *bet;
            BETA[1] = -bet[1];
            TA = 'N';
            if (M > 0) {
                n = M << 1;
                xd[nd] = (double *)malloc(n*sizeof(double [
                                                     NBDirsMax])*NBDirsMax);
                x = (double *)malloc(n*sizeof(double));
                tx = x;
                if (incX > 0) {
                    i = incX << 1;
                    tincx = 2;
                    st = x + n;
                } else {
                    i = incX*-2;
                    tincx = -2;
                    st = x - 2;
                    xd[nd] += (n-2)*NBDirsMax;
                    x += n - 2;
                }
                do {
                    for (nd = 0; nd < nbdirs; ++nd) {
                        *xd[nd] = xxd[0][nd];
                        xd[1][nd] = -xxd[1][nd];
                    }
                    *x = *xx;
                    x[1] = -xx[1];
                    xd[nd] += tincx*NBDirsMax;
                    x += tincx;
                    xxd += i;
                    xx += i;
                } while(x != st);
                xd[nd] = txd[nd];
                x = tx;
                F77_incX = 1;
                if (incY > 0)
                    tincY = incY;
                else
                    tincY = -incY;
                yd[nd] += NBDirsMax;
                y++;
                if (N > 0) {
                    i = tincY << 1;
                    n = i*N;
                    st = y + n;
                    do {
                        for (nd = 0; nd < nbdirs; ++nd)
                            *yd[nd] = -*yd[nd];
                        *y = -*y;
                        yd[nd] += i*NBDirsMax;
                        y += i;
                    } while(y != st);
                    for (nd = 0; nd < nbdirs; ++nd) yd[nd] -= n*NBDirsMax;
                    y -= n;
                }
            } else {
                for (nd = 0; nd < nbdirs; ++nd) xd[nd] = (double *)Xd + nd;
                x = (double *)X;
            }
        } else {
            cblas_xerbla(2, "cblas_zgbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasConjTrans)
            F77_zgbmv_dv(&TA, &F77_N, &F77_M, &F77_KU, &F77_KL, (double complex *)ALPHA, (double complex *)ALPHAd, (double complex *)A, (double complex *)Ad, &F77_lda, (double complex *)x, (double complex *)xd, &F77_incX, (double complex *)BETA, (double complex *)BETAd, (double complex *)Y, (double complex *)Yd, &
                      F77_incY, &nbdirs, (size_t)1, (size_t)1);
        else
            F77_zgbmv_dv(&TA, &F77_N, &F77_M, &F77_KU, &F77_KL, (double complex *)alpha, (double complex *)alphad, (double complex *)A, (double complex *)Ad, &F77_lda, (double complex *)x, (double complex *)xd, &F77_incX, (double complex *)beta, (double complex *)betad, (double complex *)Y, (double complex *)Yd, &
                      F77_incY, &nbdirs, (size_t)1, (size_t)1);
        if (TransA == CblasConjTrans) {
            if (x != X) {
                free(xd[nd]);
                free(x);
            }
            if (N > 0)
                do {
                    for (nd = 0; nd < nbdirs; ++nd)
                        *yd[nd] = -*yd[nd];
                    *y = -*y;
                    yd[nd] += i*NBDirsMax;
                    y += i;
                } while(y != st);
        }
    } else
        cblas_xerbla(1, "cblas_zgbmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
