/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include <stdio.h>
#include <stdlib.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_cgerc_d_base(...); */
/* Note: This should match the signature of cgerc_d in Fortran */

/* Declaration for differentiated Fortran routine */
/* void F77_cgeru_d_base(...); */
/* Note: This should match the signature of cgeru_d in Fortran */


/*
  Differentiation of cblas_cgerc in forward (tangent) mode:
   variations   of useful results: *A
   with respect to varying inputs: *alpha *A *X *Y
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in-out X:(loc) *X:in Y:(loc) *Y:in
   Plus diff mem management of: Y:in
*/
void cblas_cgerc_d(const CBLAS_LAYOUT layout, const __int32_t M, const 
        __int32_t N, const void *alpha, const void *alphad, const void *X, 
        const void *Xd, const __int32_t incX, const void *Y, const void *Yd, 
        const __int32_t incY, void *A, void *Ad, const __int32_t lda) {
    int32_t F77_M = M;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    int32_t n, i, tincy;
    int32_t incy = incY;
    float *y = (float *)Y;
    float *yd = (float *)Yd;
    float *yy = (float *)Y;
    float *yyd = (float *)Yd;
    float *ty;
    float *st;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    float *tyd;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor)
        F77_cgerc_d(&F77_M, &F77_N, alpha, alphad, X, Xd, &F77_incX, Y, Yd, &
                 F77_incY, A, Ad, &F77_lda);
    else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (N > 0) {
            n = N << 1;
            yd = (float *)malloc(n*sizeof(float));
            y = (float *)malloc(n*sizeof(float));
            ty = y;
            if (incY > 0) {
                i = incY << 1;
                tincy = 2;
                st = y + n;
            } else {
                i = incY*-2;
                tincy = -2;
                st = y - 2;
                yd = yd + (n - 2);
                y += n - 2;
            }
            do {
                *yd = *yyd;
                *y = *yy;
                yd[1] = -yyd[1];
                y[1] = -yy[1];
                yd = yd + tincy;
                y += tincy;
                yyd = yyd + i;
                yy += i;
            } while(y != st);
            yd = tyd;
            y = ty;
            F77_incY = 1;
        } else {
            yd = (float *)Yd;
            y = (float *)Y;
        }
        F77_cgeru_d(&F77_N, &F77_M, alpha, alphad, y, yd, &F77_incY, X, Xd, &
                 F77_incX, A, Ad, &F77_lda);
        if (Y != y) {
            free(yd);
            free(y);
        }
    } else
        cblas_xerbla(1, "cblas_cgerc", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
