/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_dgemv_dv_base(...); */
/* Note: This should match the signature of dgemv_dv in Fortran */


/*
  Differentiation of cblas_dgemv in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *Y
   with respect to varying inputs: alpha *A beta *X *Y
   RW status of diff variables: alpha:in A:(loc) *A:in beta:in
                X:(loc) *X:in Y:(loc) *Y:in-out
*/
void cblas_dgemv_dv(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const __int32_t M, const __int32_t N, const double alpha, const double
        alphad[NBDirsMax], const double *A, const double (*Ad)[NBDirsMax], 
        const __int32_t lda, const double *X, const double (*Xd)[NBDirsMax], 
        const __int32_t incX, const double beta, const double betad[NBDirsMax]
        , double *Y, double (*Yd)[NBDirsMax], const __int32_t incY, int nbdirs
) {
    char TA;
    int32_t F77_M;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(2, "cblas_dgemv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_dgemv_dv(&TA, &F77_M, &F77_N, (double *)&alpha, (double *)alphad, (double *)A, (double *)Ad, &F77_lda, (double *)X, (double *)Xd, &F77_incX, (double *)&beta, (double *)betad, (double *)Y, (double *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans)
            TA = 'N';
        else {
            cblas_xerbla(2, "cblas_dgemv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_dgemv_dv(&TA, &F77_N, &F77_M, (double *)&alpha, (double *)alphad, (double *)A, (double *)Ad, &F77_lda, (double *)X, (double *)Xd, &F77_incX, (double *)&beta, (double *)betad, (double *)Y, (double *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_dgemv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
