/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdint.h>
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_ddot_sub_dv_base(...); */
/* Note: This should match the signature of ddot_sub_dv in Fortran */


/*
  Differentiation of cblas_ddot in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: cblas_ddot
   with respect to varying inputs: *X *Y
   RW status of diff variables: cblas_ddot:out X:(loc) *X:in Y:(loc)
                *Y:in
*/
void cblas_ddot_dv(const __int32_t N, const double *X, const double (*Xd)[
        NBDirsMax], const __int32_t incX, const double *Y, const double (*Yd)[
        NBDirsMax], const __int32_t incY, double *cblas_ddot, double 
        cblas_ddotd[NBDirsMax], int nbdirs) {
    double dot;
    double dotd[NBDirsMax];
    int32_t F77_N;
    int nd;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    F77_ddotsub_dv(&F77_N, (double *)X, (double *)Xd, &F77_incX, (double *)Y, (double *)Yd, &F77_incY, (double *)&dot, (double *)&dotd, &nbdirs, (size_t)1, (size_t)1);
    *cblas_ddot = dot;
    for (nd = 0; nd < nbdirs; ++nd)
        cblas_ddotd[nd] = dotd[nd];
}
