/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdint.h>
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zswap_dv_base(...); */
/* Note: This should match the signature of zswap_dv in Fortran */


/*
  Differentiation of cblas_zswap in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *X *Y
   with respect to varying inputs: *X *Y
   RW status of diff variables: X:(loc) *X:in-out Y:(loc) *Y:in-out
*/
void cblas_zswap_dv(const __int32_t N, void *X, void *Xd, const __int32_t incX
        , void *Y, void *Yd, const __int32_t incY, int nbdirs) {
    int32_t F77_N;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    F77_zswap_dv(&F77_N, (double complex *)X, (double complex *)Xd, &F77_incX, (double complex *)Y, (double complex *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
}
