/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdint.h>
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zdotc_sub_dv_base(...); */
/* Note: This should match the signature of zdotc_sub_dv in Fortran */


/*
  Differentiation of cblas_zdotc_sub in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *dotc
   with respect to varying inputs: *dotc *X *Y
   RW status of diff variables: dotc:(loc) *dotc:in-out X:(loc)
                *X:in Y:(loc) *Y:in
*/
void cblas_zdotc_sub_dv(const __int32_t N, const void *X, const void *Xd, 
        const __int32_t incX, const void *Y, const void *Yd, const __int32_t 
        incY, void *dotc, void *dotcd, int nbdirs) {
    int32_t F77_N;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    F77_zdotcsub_dv(&F77_N, (double complex *)X, (double complex *)Xd, &F77_incX, (double complex *)Y, (double complex *)Yd, &F77_incY, (double complex *)dotc, (double complex *)dotcd, &nbdirs, (size_t)1, (size_t)1);
    return;
}
