/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <stdint.h>
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sswap_dv_base(...); */
/* Note: This should match the signature of sswap_dv in Fortran */


/*
  Differentiation of cblas_sswap in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *X *Y
   with respect to varying inputs: *X *Y
   RW status of diff variables: X:(loc) *X:in-out Y:(loc) *Y:in-out
*/
void cblas_sswap_dv(const __int32_t N, float *X, float (*Xd)[NBDirsMax], const
        __int32_t incX, float *Y, float (*Yd)[NBDirsMax], const __int32_t incY
        , int nbdirs) {
    int32_t F77_N;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    F77_sswap_dv(&F77_N, (float *)X, (float *)Xd, &F77_incX, (float *)Y, (float *)Yd, &F77_incY, &nbdirs, (size_t)1, (size_t)1);
}
