/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zgeru_dv_base(...); */
/* Note: This should match the signature of zgeru_dv in Fortran */


/*
  Differentiation of cblas_zgeru in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *A
   with respect to varying inputs: *alpha *A *X *Y
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in-out X:(loc) *X:in Y:(loc) *Y:in
*/
void cblas_zgeru_dv(const CBLAS_LAYOUT layout, const __int32_t M, const 
        __int32_t N, const void *alpha, const void *alphad, const void *X, 
        const void *Xd, const __int32_t incX, const void *Y, const void *Yd, 
        const __int32_t incY, void *A, void *Ad, const __int32_t lda, int 
        nbdirs) {
    int32_t F77_M;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor)
        F77_zgeru_dv(&F77_M, &F77_N, (double complex *)alpha, (double complex *)alphad, (double complex *)X, (double complex *)Xd, &F77_incX, (double complex *)Y, (double complex *)Yd, &
                  F77_incY, (double complex *)A, (double complex *)Ad, &F77_lda, &nbdirs, (size_t)1, (size_t)1);
    else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        F77_zgeru_dv(&F77_N, &F77_M, (double complex *)alpha, (double complex *)alphad, (double complex *)Y, (double complex *)Yd, &F77_incY, (double complex *)X, (double complex *)Xd, &
                  F77_incX, (double complex *)A, (double complex *)Ad, &F77_lda, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_zgeru", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
