/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_strsv_b_base(...); */
/* Note: This should match the signature of strsv_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_strsv_b_base F77_GLOBAL_SUFFIX(strsv_b,STRSV_B)
#define F77_strsv_b(...) F77_strsv_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_strsv in reverse (adjoint) mode:
   gradient     of useful results: *X
   with respect to varying inputs: *A *X
   RW status of diff variables: A:(loc) *A:out X:(loc) *X:in-out
*/
void cblas_strsv_b(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const __int32_t N, 
        const float *A, float *Ab, const __int32_t lda, float *X, float *Xb, 
        const __int32_t incX) {
    char TA;
    char UL;
    char DI;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int branch;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'U';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'L';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label140;
        }
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'N';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'T';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'C';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label110;
        }
        if (Diag == CblasUnit) {
            pushControl1b(0);
            DI = 'U';
        } else if (Diag == CblasNonUnit) {
            pushControl1b(1);
            DI = 'N';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label100;
        }
        F77_strsv_b(&UL, &TA, &DI, &F77_N, A, Ab, &F77_lda, X, Xb, &F77_incX);
        popControl1b(&branch);
      label100:
        popControl2b(&branch);
      label110:
        popControl1b(&branch);
    } else if (layout == CblasRowMajor) {
        if (Uplo == CblasUpper) {
            pushControl1b(0);
            UL = 'L';
        } else if (Uplo == CblasLower) {
            pushControl1b(1);
            UL = 'U';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label140;
        }
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'T';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'N';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'N';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label130;
        }
        if (Diag == CblasUnit) {
            pushControl1b(0);
            DI = 'U';
        } else if (Diag == CblasNonUnit) {
            pushControl1b(1);
            DI = 'N';
        } else {
            if (Ab)
                *Ab = 0.0;
            goto label120;
        }
        F77_strsv_b(&UL, &TA, &DI, &F77_N, A, Ab, &F77_lda, X, Xb, &F77_incX);
        popControl1b(&branch);
      label120:
        popControl2b(&branch);
      label130:
        popControl1b(&branch);
    } else if (Ab)
        *Ab = 0.0;
  label140:
    ;
}
