/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zdotu_sub_d_base(...); */
/* Note: This should match the signature of zdotu_sub_d in Fortran */


/*
  Differentiation of cblas_zdotu_sub in forward (tangent) mode:
   variations   of useful results: *dotu
   with respect to varying inputs: *dotu *X *Y
   RW status of diff variables: dotu:(loc) *dotu:in-out X:(loc)
                *X:in Y:(loc) *Y:in
*/
void cblas_zdotu_sub_d(const __int32_t N, const void *X, const void *Xd, const
        __int32_t incX, const void *Y, const void *Yd, const __int32_t incY, 
        void *dotu, void *dotud) {
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    F77_zdotusub_d(&F77_N, X, Xd, &F77_incX, Y, Yd, &F77_incY, dotu, dotud);
    return;
}
