/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sger_dv_base(...); */
/* Note: This should match the signature of sger_dv in Fortran */


/*
  Differentiation of cblas_sger in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *A
   with respect to varying inputs: alpha *A *X *Y
   RW status of diff variables: alpha:in A:(loc) *A:in-out X:(loc)
                *X:in Y:(loc) *Y:in
*/
void cblas_sger_dv(const CBLAS_LAYOUT layout, const __int32_t M, const 
        __int32_t N, const float alpha, const float alphad[NBDirsMax], const 
        float *X, const float (*Xd)[NBDirsMax], const __int32_t incX, const 
        float *Y, const float (*Yd)[NBDirsMax], const __int32_t incY, float *A
        , float (*Ad)[NBDirsMax], const __int32_t lda, int nbdirs) {
    int32_t F77_M;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor)
        F77_sger_dv(&F77_M, &F77_N, (float *)&alpha, (float *)alphad, (float *)X, (float *)Xd, &F77_incX, (float *)Y, (float *)Yd, &
                 F77_incY, (float *)A, (float *)Ad, &F77_lda, &nbdirs, (size_t)1, (size_t)1);
    else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        F77_sger_dv(&F77_N, &F77_M, (float *)&alpha, (float *)alphad, (float *)Y, (float *)Yd, &F77_incY, (float *)X, (float *)Xd, &
                 F77_incX, (float *)A, (float *)Ad, &F77_lda, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_sger", "Illegal layout setting, %d\n", layout);
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
