/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_ctbmv_d_base(...); */
/* Note: This should match the signature of ctbmv_d in Fortran */


/*
  Differentiation of cblas_ctbmv in forward (tangent) mode:
   variations   of useful results: *X
   with respect to varying inputs: *A *X
   RW status of diff variables: A:(loc) *A:in X:(loc) *X:in-out
   Plus diff mem management of: X:in
*/
void cblas_ctbmv_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const __int32_t N, 
        const __int32_t K, const void *A, const void *Ad, const __int32_t lda,
        void *X, void *Xd, const __int32_t incX) {
    char TA;
    char UL;
    char DI;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_K = K;
    int32_t F77_incX = incX;
    int32_t n;
    int32_t i = 0;
    int32_t tincX;
    float *st = 0;
    float *x = (float *)X;
    float *xd = (float *)Xd;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_ctbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(3, "cblas_ctbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_ctbmv", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ctbmv_d(&UL, &TA, &DI, &F77_N, &F77_K, A, Ad, &F77_lda, X, Xd, &
                 F77_incX);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_ctbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans) {
            TA = 'N';
            if (N > 0) {
                if (incX > 0)
                    tincX = incX;
                else
                    tincX = -incX;
                i = tincX << 1;
                n = i*N;
                xd++;
                x++;
                st = x + n;
                do {
                    *xd = -*xd;
                    *x = -*x;
                    xd = xd + i;
                    x += i;
                } while(x != st);
                xd = xd - n;
                x -= n;
            }
        } else {
            cblas_xerbla(3, "cblas_ctbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_ctbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_ctbmv_d(&UL, &TA, &DI, &F77_N, &F77_K, A, Ad, &F77_lda, X, Xd, &
                 F77_incX);
        if (TransA == CblasConjTrans)
            if (N > 0)
                do {
                    *xd = -*xd;
                    *x = -*x;
                    xd = xd + i;
                    x += i;
                } while(x != st);
    } else
        cblas_xerbla(1, "cblas_ctbmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
