C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of snrm2sub in reverse (adjoint) mode:
C   gradient     of useful results: x nrm2
C   with respect to varying inputs: x
C     snrm2sub.f
C
C     The program is a fortran wrapper for snrm2.
C     Witten by Keita Teranishi.  2/11/1998
C
      SUBROUTINE SNRM2SUB_B(n, x, xb, incx, nrm2, nrm2b)
      IMPLICIT NONE
C
      EXTERNAL SNRM2
      EXTERNAL SNRM2_DIFF
      REAL SNRM2, nrm2
      REAL nrm2b
      INTEGER n, incx
      REAL x(*)
      REAL xb(*)
C
      CALL SNRM2_B(n, x, xb, incx, nrm2b)
      END

