/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_bv.h"
#include "cblas_f77_bv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sscal_bv_base(...); */
/* Note: This should match the signature of sscal_bv in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_sscal_bv_base F77_GLOBAL_SUFFIX(sscal_bv,SSCAL_BV)
#define F77_sscal_bv(...) F77_sscal_bv_base(__VA_ARGS__)


/*
  Differentiation of cblas_sscal in reverse (adjoint) mode (with options multiDirectional):
   gradient     of useful results: alpha *X
   with respect to varying inputs: alpha *X
   RW status of diff variables: alpha:incr X:(loc) *X:in-out
*/
void cblas_sscal_bv(const __int32_t N, const float alpha, float (*alphab)[
        NBDirsMax], float *X, float (*Xb)[NBDirsMax], const __int32_t incX, 
        int nbdirs) {
    int32_t F77_N;
    int nd;
    F77_N = N;
    int32_t F77_incX;
    F77_incX = incX;
    F77_sscal_bv(&F77_N, &alpha, &(*alphab), X, Xb, &F77_incX, &nbdirs);
}
