/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_bv.h"
#include "cblas_f77_bv.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_bv.h"
#include "cblas_f77_bv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sgbmv_bv_base(..., (size_t)1); */
/* Note: This should match the signature of sgbmv_bv in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_sgbmv_bv_base F77_GLOBAL_SUFFIX(sgbmv_bv,SGBMV_BV)
#define F77_sgbmv_bv(...) F77_sgbmv_bv_base(__VA_ARGS__)


/*
  Differentiation of cblas_sgbmv in reverse (adjoint) mode (with options multiDirectional):
   gradient     of useful results: *Y
   with respect to varying inputs: alpha *A beta *X *Y
   RW status of diff variables: alpha:out A:(loc) *A:out beta:out
                X:(loc) *X:out Y:(loc) *Y:in-out
*/
void cblas_sgbmv_bv(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const __int32_t M, const __int32_t N, const __int32_t KL, const 
        __int32_t KU, const float alpha, float (*alphab)[NBDirsMax], const 
        float *A, float *Ab, const __int32_t lda, const float *X,
        float (*Xb)[NBDirsMax], const __int32_t incX, const float beta, float 
        (*betab)[NBDirsMax], float *Y, float (*Yb)[NBDirsMax], const __int32_t
        incY, int nbdirs) {
    char TA;
    int32_t F77_M;
    int branch;
    int nd;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_incX;
    F77_incX = incX;
    int32_t F77_incY;
    F77_incY = incY;
    int32_t F77_KL;
    F77_KL = KL;
    int32_t F77_KU;
    F77_KU = KU;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    if (layout == CblasColMajor) {
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'N';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'T';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'C';
        } else {
            for (nd = 0; nd < NBDirsMax; ++nd)
                (*alphab)[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                Ab[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                (*betab)[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                *Xb[nd] = 0.0;
            goto label100;
        }
        F77_sgbmv_bv(&TA, &F77_M, &F77_N, &F77_KL, &F77_KU, &alpha, &(*alphab), A
                  , Ab, &F77_lda, X, Xb, &F77_incX, &beta, &(*betab), Y, Yb, &
                  F77_incY, &nbdirs, (size_t)1);
        popControl2b(&branch);
    } else if (layout == CblasRowMajor) {
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'T';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'N';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'N';
        } else {
            for (nd = 0; nd < NBDirsMax; ++nd)
                (*alphab)[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                Ab[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                (*betab)[nd] = 0.0;
            for (nd = 0; nd < NBDirsMax; ++nd)
                *Xb[nd] = 0.0;
            goto label100;
        }
        F77_sgbmv_bv(&TA, &F77_N, &F77_M, &F77_KU, &F77_KL, &alpha, &(*alphab), A
                  , Ab, &F77_lda, X, Xb, &F77_incX, &beta, &(*betab), Y, Yb, &
                  F77_incY, &nbdirs, (size_t)1);
        popControl2b(&branch);
    } else {
        for (nd = 0; nd < NBDirsMax; ++nd)
            (*alphab)[nd] = 0.0;
        for (nd = 0; nd < NBDirsMax; ++nd)
            Ab[nd] = 0.0;
        for (nd = 0; nd < NBDirsMax; ++nd)
            (*betab)[nd] = 0.0;
        for (nd = 0; nd < NBDirsMax; ++nd)
            *Xb[nd] = 0.0;
    }
  label100:
    ;
}
