/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_stbmv_dv_base(...); */
/* Note: This should match the signature of stbmv_dv in Fortran */


/*
  Differentiation of cblas_stbmv in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *X
   with respect to varying inputs: *A *X
   RW status of diff variables: A:(loc) *A:in X:(loc) *X:in-out
*/
void cblas_stbmv_dv(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const __int32_t N, 
        const __int32_t K, const float *A, const float (*Ad)[NBDirsMax], const
        __int32_t lda, float *X, float (*Xd)[NBDirsMax], const __int32_t incX,
        int nbdirs) {
    char TA;
    char UL;
    char DI;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_K;
    F77_K = K;
    int32_t F77_incX;
    F77_incX = incX;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_stbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'N';
        else if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else {
            cblas_xerbla(3, "cblas_stbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_stbmv", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_stbmv_dv((float *)&UL, &TA, (float *)&DI, &F77_N, &F77_K, (float *)A, (float *)Ad, &F77_lda, (float *)X, (float *)Xd, &
                  F77_incX, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(2, "cblas_stbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasNoTrans)
            TA = 'T';
        else if (TransA == CblasTrans)
            TA = 'N';
        else if (TransA == CblasConjTrans)
            TA = 'N';
        else {
            cblas_xerbla(3, "cblas_stbmv", "Illegal TransA setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(4, "cblas_stbmv", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_stbmv_dv((float *)&UL, &TA, (float *)&DI, &F77_N, &F77_K, (float *)A, (float *)Ad, &F77_lda, (float *)X, (float *)Xd, &
                  F77_incX, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_stbmv", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
