/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"
#include <stdc-predef.h>
#include "cblas_d.h"
#include "cblas_f77_d.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zsyrk_d_base(...); */
/* Note: This should match the signature of zsyrk_d in Fortran */


/*
  Differentiation of cblas_zsyrk in forward (tangent) mode:
   variations   of useful results: *C
   with respect to varying inputs: *alpha *A *C *beta
   RW status of diff variables: alpha:(loc) *alpha:in A:(loc)
                *A:in C:(loc) *C:in-out beta:(loc) *beta:in
*/
void cblas_zsyrk_d(const CBLAS_LAYOUT layout, const CBLAS_UPLO Uplo, const 
        CBLAS_TRANSPOSE Trans, const __int32_t N, const __int32_t K, const 
        void *alpha, const void *alphad, const void *A, const void *Ad, const 
        __int32_t lda, const void *beta, const void *betad, void *C, void *Cd,
        const __int32_t ldc) {
    char UL, TR;
    int32_t F77_N = N;
    int32_t F77_K = K;
    int32_t F77_lda = lda;
    int32_t F77_ldc = ldc;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(2, "cblas_zsyrk", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Trans == CblasTrans)
            TR = 'T';
        else if (Trans == CblasConjTrans)
            TR = 'C';
        else if (Trans == CblasNoTrans)
            TR = 'N';
        else {
            cblas_xerbla(3, "cblas_zsyrk", "Illegal Trans setting, %d\n", 
                         Trans);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_zsyrk_d(&UL, &TR, &F77_N, &F77_K, alpha, alphad, A, Ad, &F77_lda, 
                 beta, betad, C, Cd, &F77_ldc);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(3, "cblas_zsyrk", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Trans == CblasTrans)
            TR = 'N';
        else if (Trans == CblasConjTrans)
            TR = 'N';
        else if (Trans == CblasNoTrans)
            TR = 'T';
        else {
            cblas_xerbla(3, "cblas_zsyrk", "Illegal Trans setting, %d\n", 
                         Trans);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_zsyrk_d(&UL, &TR, &F77_N, &F77_K, alpha, alphad, A, Ad, &F77_lda, 
                 beta, betad, C, Cd, &F77_ldc);
    } else
        cblas_xerbla(1, "cblas_zsyrk", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
