/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <adStack.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_sgemv_b_base(...); */
/* Note: This should match the signature of sgemv_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_sgemv_b_base F77_GLOBAL_SUFFIX(sgemv_b,SGEMV_B)
#define F77_sgemv_b(...) F77_sgemv_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_sgemv in reverse (adjoint) mode:
   gradient     of useful results: *Y
   with respect to varying inputs: alpha *A beta *X *Y
   RW status of diff variables: alpha:out A:(loc) *A:out beta:out
                X:(loc) *X:out Y:(loc) *Y:in-out
*/
void cblas_sgemv_b(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA, 
        const __int32_t M, const __int32_t N, const float alpha, float *alphab
        , const float *A, float *Ab, const __int32_t lda, const float *X, 
        float *Xb, const __int32_t incX, const float beta, float *betab, float
        *Y, float *Yb, const __int32_t incY) {
    char TA;
    int32_t F77_M = M;
    int32_t F77_N = N;
    int32_t F77_lda = lda;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    int branch;
    if (layout == CblasColMajor) {
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'N';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'T';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'C';
        } else
            pushControl2b(2);
        F77_sgemv_b(&TA, &F77_M, &F77_N, &alpha, &(*alphab), A, Ab, &F77_lda, X, 
                 Xb, &F77_incX, &beta, &(*betab), Y, Yb, &F77_incY);
        popControl2b(&branch);
    } else if (layout == CblasRowMajor) {
        if (TransA == CblasNoTrans) {
            pushControl2b(0);
            TA = 'T';
        } else if (TransA == CblasTrans) {
            pushControl2b(1);
            TA = 'N';
        } else if (TransA == CblasConjTrans) {
            pushControl2b(2);
            TA = 'N';
        } else {
            if (alphab)
                *alphab = 0.0;
            if (Ab)
                *Ab = 0.0;
            if (betab)
                *betab = 0.0;
            if (Xb)
                *Xb = 0.0;
            goto label100;
        }
        F77_sgemv_b(&TA, &F77_N, &F77_M, &alpha, &(*alphab), A, Ab, &F77_lda, X, 
                 Xb, &F77_incX, &beta, &(*betab), Y, Yb, &F77_incY);
        popControl2b(&branch);
    } else {
        if (alphab)
            *alphab = 0.0;
        if (Ab)
            *Ab = 0.0;
        if (betab)
            *betab = 0.0;
        if (Xb)
            *Xb = 0.0;
    }
  label100:
    ;
}
