C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of snrm2sub in reverse (adjoint) mode (with options multiDirectional):
C   gradient     of useful results: x nrm2
C   with respect to varying inputs: x
C     snrm2sub.f
C
C     The program is a fortran wrapper for snrm2.
C     Witten by Keita Teranishi.  2/11/1998
C
      SUBROUTINE SNRM2SUB_BV(n, x, xb, incx, nrm2, nrm2b, nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZESF.inc'
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
      EXTERNAL SNRM2
      EXTERNAL SNRM2_DIFFV
      REAL SNRM2, nrm2
      REAL nrm2b(nbdirsmax)
      INTEGER n, incx
      REAL x(*)
      REAL xb(nbdirsmax, *)
C
      INTEGER nbdirs
      CALL SNRM2_BV(n, x, xb, incx, nrm2b, nbdirs)
      END

