/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include "DIFFSIZESC.inc"
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"
#include <stdc-predef.h>
#include "cblas_dv.h"
#include "cblas_f77_dv.h"

/* Declaration for differentiated Fortran routine */
/* void F77_strmm_dv_base(...); */
/* Note: This should match the signature of strmm_dv in Fortran */


/*
  Differentiation of cblas_strmm in forward (tangent) mode (with options multiDirectional):
   variations   of useful results: *B
   with respect to varying inputs: alpha *A *B
   RW status of diff variables: alpha:in A:(loc) *A:in B:(loc)
                *B:in-out
*/
void cblas_strmm_dv(const CBLAS_LAYOUT layout, const CBLAS_SIDE Side, const 
        CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, 
        const __int32_t M, const __int32_t N, const float alpha, const float 
        alphad[NBDirsMax], const float *A, const float (*Ad)[NBDirsMax], const
        __int32_t lda, float *B, float (*Bd)[NBDirsMax], const __int32_t ldb, 
        int nbdirs) {
    char UL, TA, SD, DI;
    int32_t F77_M;
    F77_M = M;
    int32_t F77_N;
    F77_N = N;
    int32_t F77_lda;
    F77_lda = lda;
    int32_t F77_ldb;
    F77_ldb = ldb;
    extern int CBLAS_CallFromC;
    extern int RowMajorStrg;
    RowMajorStrg = 0;
    CBLAS_CallFromC = 1;
    if (layout == CblasColMajor) {
        if (Side == CblasRight)
            SD = 'R';
        else if (Side == CblasLeft)
            SD = 'L';
        else {
            cblas_xerbla(2, "cblas_strmm", "Illegal Side setting, %d\n", Side)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Uplo == CblasUpper)
            UL = 'U';
        else if (Uplo == CblasLower)
            UL = 'L';
        else {
            cblas_xerbla(3, "cblas_strmm", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else if (TransA == CblasNoTrans)
            TA = 'N';
        else {
            cblas_xerbla(4, "cblas_strmm", "Illegal Trans setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(5, "cblas_strmm", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_strmm_dv((float *)&SD, (float *)&UL, &TA, (float *)&DI, &F77_M, &F77_N, (float *)&alpha, (float *)alphad, (float *)A, (float *)Ad, &F77_lda, (float *)B, (float *)Bd, &F77_ldb, &nbdirs, (size_t)1, (size_t)1);
    } else if (layout == CblasRowMajor) {
        RowMajorStrg = 1;
        if (Side == CblasRight)
            SD = 'L';
        else if (Side == CblasLeft)
            SD = 'R';
        else {
            cblas_xerbla(2, "cblas_strmm", "Illegal Side setting, %d\n", Side)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Uplo == CblasUpper)
            UL = 'L';
        else if (Uplo == CblasLower)
            UL = 'U';
        else {
            cblas_xerbla(3, "cblas_strmm", "Illegal Uplo setting, %d\n", Uplo)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (TransA == CblasTrans)
            TA = 'T';
        else if (TransA == CblasConjTrans)
            TA = 'C';
        else if (TransA == CblasNoTrans)
            TA = 'N';
        else {
            cblas_xerbla(4, "cblas_strmm", "Illegal Trans setting, %d\n", 
                         TransA);
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        if (Diag == CblasUnit)
            DI = 'U';
        else if (Diag == CblasNonUnit)
            DI = 'N';
        else {
            cblas_xerbla(5, "cblas_strmm", "Illegal Diag setting, %d\n", Diag)
            ;
            CBLAS_CallFromC = 0;
            RowMajorStrg = 0;
            return;
        }
        F77_strmm_dv((float *)&SD, (float *)&UL, &TA, (float *)&DI, &F77_N, &F77_M, (float *)&alpha, (float *)alphad, (float *)A, (float *)Ad, &F77_lda, (float *)B, (float *)Bd, &F77_ldb, &nbdirs, (size_t)1, (size_t)1);
    } else
        cblas_xerbla(1, "cblas_strmm", "Illegal layout setting, %d\n", layout)
        ;
    CBLAS_CallFromC = 0;
    RowMajorStrg = 0;
    return;
}
