/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) -  6 Jan 2026 19:07
*/
#include <complex.h>
#include <adStack.h>
#include <stdc-predef.h>
#include "cblas_b.h"
#include "cblas_f77_b.h"

/* Declaration for differentiated Fortran routine */
/* void F77_zswap_b_base(...); */
/* Note: This should match the signature of zswap_b in Fortran */

/* F77_ macros for differentiated Fortran routines */
/* These macros handle name mangling for differentiated Fortran functions */
#define F77_zswap_b_base F77_GLOBAL_SUFFIX(zswap_b,ZSWAP_B)
#define F77_zswap_b(...) F77_zswap_b_base(__VA_ARGS__)


/*
  Differentiation of cblas_zswap in reverse (adjoint) mode:
   gradient     of useful results: *X *Y
   with respect to varying inputs: *X *Y
   RW status of diff variables: X:(loc) *X:in-out Y:(loc) *Y:in-out
*/
void cblas_zswap_b(const __int32_t N, void *X, void *Xb, const __int32_t incX,
        void *Y, void *Yb, const __int32_t incY) {
    int32_t F77_N = N;
    int32_t F77_incX = incX;
    int32_t F77_incY = incY;
    F77_zswap_b(&F77_N, X, Xb, &F77_incX, Y, Yb, &F77_incY);
}
