C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of cgerc in forward (tangent) mode:
C   variations   of useful results: a
C   with respect to varying inputs: alpha x y a
C   RW status of diff variables: alpha:in x:in y:in a:in-out
C> \brief \b CGERC
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE CGERC(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
C
C       .. Scalar Arguments ..
C       COMPLEX ALPHA
C       INTEGER INCX,INCY,LDA,M,N
C       ..
C       .. Array Arguments ..
C       COMPLEX A(LDA,*),X(*),Y(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> CGERC  performs the rank 1 operation
C>
C>    A := alpha*x*y**H + A,
C>
C> where alpha is a scalar, x is an m element vector, y is an n element
C> vector and A is an m by n matrix.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry, M specifies the number of rows of the matrix A.
C>           M must be at least zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the number of columns of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is COMPLEX
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] X
C> \verbatim
C>          X is COMPLEX array, dimension at least
C>           ( 1 + ( m - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the m
C>           element vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C>
C> \param[in] Y
C> \verbatim
C>          Y is COMPLEX array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCY ) ).
C>           Before entry, the incremented array Y must contain the n
C>           element vector y.
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>           On entry, INCY specifies the increment for the elements of
C>           Y. INCY must not be zero.
C> \endverbatim
C>
C> \param[in,out] A
C> \verbatim
C>          A is COMPLEX array, dimension ( LDA, N )
C>           Before entry, the leading m by n part of the array A must
C>           contain the matrix of coefficients. On exit, A is
C>           overwritten by the updated matrix.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, m ).
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup ger
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE CGERC_D(m, n, alpha, alphad, x, xd, incx, y, yd, incy, 
     +                   a, ad, lda)
      IMPLICIT NONE
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      COMPLEX alpha
      COMPLEX alphad
      INTEGER incx, incy, lda, m, n
C     ..
C     .. Array Arguments ..
      COMPLEX a(lda, *), x(*), y(*)
      COMPLEX ad(lda, *), xd(*), yd(*)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      COMPLEX zero
      PARAMETER (zero=(0.0e+0,0.0e+0))
C     ..
C     .. Local Scalars ..
      COMPLEX temp
      COMPLEX tempd
      INTEGER i, info, ix, j, jy, kx
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC CONJG, MAX
      INTEGER max1
      COMPLEX temp0
C     ..
C
C     Test the input parameters.
C
      info = 0
      IF (m .LT. 0) THEN
        info = 1
      ELSE IF (n .LT. 0) THEN
        info = 2
      ELSE IF (incx .EQ. 0) THEN
        info = 5
      ELSE IF (incy .EQ. 0) THEN
        info = 7
      ELSE
        IF (1 .LT. m) THEN
          max1 = m
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) info = 9
      END IF
      IF (info .NE. 0) THEN
        CALL XERBLA('CGERC ', info)
        RETURN
      ELSE IF ((m .EQ. 0 .OR. n .EQ. 0) .OR. alpha .EQ. zero) THEN
C
C     Quick return if possible.
C
        RETURN
      ELSE
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through A.
C
        IF (incy .GT. 0) THEN
          jy = 1
        ELSE
          jy = 1 - (n-1)*incy
        END IF
        IF (incx .EQ. 1) THEN
          DO j=1,n
            IF (y(jy) .NE. zero) THEN
              temp0 = CONJG(y(jy))
              tempd = temp0*alphad + alpha*CONJG(yd(jy))
              temp = alpha*temp0
              DO i=1,m
                ad(i, j) = ad(i, j) + temp*xd(i) + x(i)*tempd
                a(i, j) = a(i, j) + x(i)*temp
              ENDDO
            END IF
            jy = jy + incy
          ENDDO
        ELSE
          IF (incx .GT. 0) THEN
            kx = 1
          ELSE
            kx = 1 - (m-1)*incx
          END IF
          DO j=1,n
            IF (y(jy) .NE. zero) THEN
              temp0 = CONJG(y(jy))
              tempd = temp0*alphad + alpha*CONJG(yd(jy))
              temp = alpha*temp0
              ix = kx
              DO i=1,m
                ad(i, j) = ad(i, j) + temp*xd(ix) + x(ix)*tempd
                a(i, j) = a(i, j) + x(ix)*temp
                ix = ix + incx
              ENDDO
            END IF
            jy = jy + incy
          ENDDO
        END IF
C
        RETURN
C
C     End of CGERC
C
      END IF
      END

