C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of cswap in reverse (adjoint) mode:
C   gradient     of useful results: cx cy
C   with respect to varying inputs: cx cy
C   RW status of diff variables: cx:in-out cy:in-out
C> \brief \b CSWAP
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE CSWAP(N,CX,INCX,CY,INCY)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       COMPLEX CX(*),CY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C>   CSWAP interchanges two vectors.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in,out] CX
C> \verbatim
C>          CX is COMPLEX array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of CX
C> \endverbatim
C>
C> \param[in,out] CY
C> \verbatim
C>          CY is COMPLEX array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of CY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup swap
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, linpack, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE CSWAP_B(n, cx, cxb, incx, cy, cyb, incy)
      IMPLICIT NONE
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, incy, n
C     ..
C     .. Array Arguments ..
      COMPLEX cx(*), cy(*)
      COMPLEX cxb(*), cyb(*)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      COMPLEX ctemp
      COMPLEX ctempb
      INTEGER i, ix, iy
C     ..
      IF (n .GT. 0) THEN
        IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
          DO i=n,1,-1
            ctempb = cyb(i)
            cyb(i) = cxb(i)
            cxb(i) = ctempb
          ENDDO
        ELSE
C
C       code for unequal increments or equal increments not equal
C         to 1
C
          ix = 1
          iy = 1
          IF (incx .LT. 0) ix = (-n+1)*incx + 1
          IF (incy .LT. 0) iy = (-n+1)*incy + 1
          DO i=1,n
            CALL PUSHINTEGER4(ix)
            ix = ix + incx
            CALL PUSHINTEGER4(iy)
            iy = iy + incy
          ENDDO
          DO i=n,1,-1
            CALL POPINTEGER4(iy)
            CALL POPINTEGER4(ix)
            ctempb = cyb(iy)
            cyb(iy) = cxb(ix)
            cxb(ix) = ctempb
          ENDDO
        END IF
      END IF
      END

