C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dcopy in reverse (adjoint) mode (with options multiDirectional):
C   gradient     of useful results: dy
C   with respect to varying inputs: dx dy
C   RW status of diff variables: dx:out dy:in-out
C> \brief \b DCOPY
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DCOPY(N,DX,INCX,DY,INCY)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION DX(*),DY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C>    DCOPY copies a vector, x, to a vector, y.
C>    uses unrolled loops for increments equal to 1.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in] DX
C> \verbatim
C>          DX is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of DX
C> \endverbatim
C>
C> \param[out] DY
C> \verbatim
C>          DY is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of DY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup copy
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, linpack, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DCOPY_BV(n, dx, dxb, incx, dy, dyb, incy, nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE1OFdx should be the size of dimension 1 of array dx
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, incy, n
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION dx(*), dy(*)
      DOUBLE PRECISION dxb(nbdirsmax, *), dyb(nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      INTEGER i, ix, iy, m, mp1
      INTEGER ISIZE1OFDx
      INTEGER get_ISIZE1OFDx
      EXTERNAL get_ISIZE1OFDx
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MOD
      INTEGER nd
      INTEGER ii1
      INTEGER*4 branch
      INTEGER nbdirs
C     ..
C     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
      CALL check_ISIZE1OFDx_initialized()
      ISIZE1OFDx = get_ISIZE1OFDx()
      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
        STOP 1
      END IF
C
      IF (n .LE. 0) THEN
        DO ii1=1,ISIZE1OFdx
          DO nd=1,nbdirsmax
            dxb(nd, ii1) = 0.D0
          ENDDO
        ENDDO
      ELSE IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C        code for both increments equal to 1
C
C
C        clean-up loop
C
        m = MOD(n, 7)
        IF (m .NE. 0) THEN
          IF (n .LT. 7) THEN
            DO ii1=1,ISIZE1OFdx
              DO nd=1,nbdirsmax
                dxb(nd, ii1) = 0.D0
              ENDDO
            ENDDO
            GOTO 100
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        mp1 = m + 1
        DO ii1=1,ISIZE1OFdx
          DO nd=1,nbdirsmax
            dxb(nd, ii1) = 0.D0
          ENDDO
        ENDDO
        DO i=n-MOD(n-mp1, 7),mp1,-7
          DO nd=1,nbdirs
            dxb(nd, i+6) = dxb(nd, i+6) + dyb(nd, i+6)
            dyb(nd, i+6) = 0.D0
            dxb(nd, i+5) = dxb(nd, i+5) + dyb(nd, i+5)
            dyb(nd, i+5) = 0.D0
            dxb(nd, i+4) = dxb(nd, i+4) + dyb(nd, i+4)
            dyb(nd, i+4) = 0.D0
            dxb(nd, i+3) = dxb(nd, i+3) + dyb(nd, i+3)
            dyb(nd, i+3) = 0.D0
            dxb(nd, i+2) = dxb(nd, i+2) + dyb(nd, i+2)
            dyb(nd, i+2) = 0.D0
            dxb(nd, i+1) = dxb(nd, i+1) + dyb(nd, i+1)
            dyb(nd, i+1) = 0.D0
            dxb(nd, i) = dxb(nd, i) + dyb(nd, i)
            dyb(nd, i) = 0.D0
          ENDDO
        ENDDO
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) GOTO 110
 100    DO i=m,1,-1
          DO nd=1,nbdirs
            dxb(nd, i) = dxb(nd, i) + dyb(nd, i)
            dyb(nd, i) = 0.D0
          ENDDO
        ENDDO
      ELSE
C
C        code for unequal increments or equal increments
C          not equal to 1
C
        ix = 1
        iy = 1
        IF (incx .LT. 0) ix = (-n+1)*incx + 1
        IF (incy .LT. 0) iy = (-n+1)*incy + 1
        DO i=1,n
          CALL PUSHINTEGER4(ix)
          ix = ix + incx
          CALL PUSHINTEGER4(iy)
          iy = iy + incy
        ENDDO
        DO ii1=1,ISIZE1OFdx
          DO nd=1,nbdirsmax
            dxb(nd, ii1) = 0.D0
          ENDDO
        ENDDO
        DO i=n,1,-1
          CALL POPINTEGER4(iy)
          CALL POPINTEGER4(ix)
          DO nd=1,nbdirs
            dxb(nd, ix) = dxb(nd, ix) + dyb(nd, iy)
            dyb(nd, iy) = 0.D0
          ENDDO
        ENDDO
      END IF
 110  CONTINUE
      END

