C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dgbmv in forward (tangent) mode (with options multiDirectional):
C   variations   of useful results: y
C   with respect to varying inputs: alpha x y beta a
C   RW status of diff variables: alpha:in x:in y:in-out beta:in
C                a:in
C> \brief \b DGBMV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DGBMV(TRANS,M,N,KL,KU,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
C
C       .. Scalar Arguments ..
C       DOUBLE PRECISION ALPHA,BETA
C       INTEGER INCX,INCY,KL,KU,LDA,M,N
C       CHARACTER TRANS
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION A(LDA,*),X(*),Y(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> DGBMV  performs one of the matrix-vector operations
C>
C>    y := alpha*A*x + beta*y,   or   y := alpha*A**T*x + beta*y,
C>
C> where alpha and beta are scalars, x and y are vectors and A is an
C> m by n band matrix, with kl sub-diagonals and ku super-diagonals.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] TRANS
C> \verbatim
C>          TRANS is CHARACTER*1
C>           On entry, TRANS specifies the operation to be performed as
C>           follows:
C>
C>              TRANS = 'N' or 'n'   y := alpha*A*x + beta*y.
C>
C>              TRANS = 'T' or 't'   y := alpha*A**T*x + beta*y.
C>
C>              TRANS = 'C' or 'c'   y := alpha*A**T*x + beta*y.
C> \endverbatim
C>
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry, M specifies the number of rows of the matrix A.
C>           M must be at least zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the number of columns of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] KL
C> \verbatim
C>          KL is INTEGER
C>           On entry, KL specifies the number of sub-diagonals of the
C>           matrix A. KL must satisfy  0 .le. KL.
C> \endverbatim
C>
C> \param[in] KU
C> \verbatim
C>          KU is INTEGER
C>           On entry, KU specifies the number of super-diagonals of the
C>           matrix A. KU must satisfy  0 .le. KU.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is DOUBLE PRECISION.
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is DOUBLE PRECISION array, dimension ( LDA, N )
C>           Before entry, the leading ( kl + ku + 1 ) by n part of the
C>           array A must contain the matrix of coefficients, supplied
C>           column by column, with the leading diagonal of the matrix in
C>           row ( ku + 1 ) of the array, the first super-diagonal
C>           starting at position 2 in row ku, the first sub-diagonal
C>           starting at position 1 in row ( ku + 2 ), and so on.
C>           Elements in the array A that do not correspond to elements
C>           in the band matrix (such as the top left ku by ku triangle)
C>           are not referenced.
C>           The following program segment will transfer a band matrix
C>           from conventional full matrix storage to band storage:
C>
C>                 DO 20, J = 1, N
C>                    K = KU + 1 - J
C>                    DO 10, I = MAX( 1, J - KU ), MIN( M, J + KL )
C>                       A( K + I, J ) = matrix( I, J )
C>              10    CONTINUE
C>              20 CONTINUE
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           ( kl + ku + 1 ).
C> \endverbatim
C>
C> \param[in] X
C> \verbatim
C>          X is DOUBLE PRECISION array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ) when TRANS = 'N' or 'n'
C>           and at least
C>           ( 1 + ( m - 1 )*abs( INCX ) ) otherwise.
C>           Before entry, the incremented array X must contain the
C>           vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is DOUBLE PRECISION.
C>           On entry, BETA specifies the scalar beta. When BETA is
C>           supplied as zero then Y need not be set on input.
C> \endverbatim
C>
C> \param[in,out] Y
C> \verbatim
C>          Y is DOUBLE PRECISION array, dimension at least
C>           ( 1 + ( m - 1 )*abs( INCY ) ) when TRANS = 'N' or 'n'
C>           and at least
C>           ( 1 + ( n - 1 )*abs( INCY ) ) otherwise.
C>           Before entry, the incremented array Y must contain the
C>           vector y. On exit, Y is overwritten by the updated vector y.
C>           If either m or n is zero, then Y not referenced and the function
C>           performs a quick return.
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>           On entry, INCY specifies the increment for the elements of
C>           Y. INCY must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup gbmv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>  The vector and matrix arguments are not referenced when N = 0, or M = 0
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DGBMV_DV(trans, m, n, kl, ku, alpha, alphad, a, ad, lda
     +                    , x, xd, incx, beta, betad, y, yd, incy, 
     +                    nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION alpha, beta
      DOUBLE PRECISION alphad(nbdirsmax), betad(nbdirsmax)
      INTEGER incx, incy, kl, ku, lda, m, n
      CHARACTER trans
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION a(lda, *), x(*), y(*)
      DOUBLE PRECISION ad(nbdirsmax, lda, *), xd(nbdirsmax, *), yd(
     +                 nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      DOUBLE PRECISION one, zero
      PARAMETER (one=1.0d+0, zero=0.0d+0)
C     ..
C     .. Local Scalars ..
      DOUBLE PRECISION temp
      DOUBLE PRECISION tempd(nbdirsmax)
      INTEGER i, info, ix, iy, j, jx, jy, k, kup1, kx, ky, lenx, leny
      EXTERNAL LSAME
C     ..
C     .. External Functions ..
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX, MIN
      INTEGER max1
      INTEGER max2
      INTEGER max3
      INTEGER max4
      INTEGER min1
      INTEGER min2
      INTEGER min3
      INTEGER min4
      INTEGER nd
      INTEGER nbdirs
C     ..
C
C     Test the input parameters.
C
C     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
        STOP 1
      END IF
C
      info = 0
      IF (.NOT.LSAME(trans, 'N') .AND. (.NOT.LSAME(trans, 'T')) .AND. (
     +    .NOT.LSAME(trans, 'C'))) THEN
        info = 1
      ELSE IF (m .LT. 0) THEN
        info = 2
      ELSE IF (n .LT. 0) THEN
        info = 3
      ELSE IF (kl .LT. 0) THEN
        info = 4
      ELSE IF (ku .LT. 0) THEN
        info = 5
      ELSE IF (lda .LT. kl + ku + 1) THEN
        info = 8
      ELSE IF (incx .EQ. 0) THEN
        info = 10
      ELSE IF (incy .EQ. 0) THEN
        info = 13
      END IF
      IF (info .NE. 0) THEN
        CALL XERBLA('DGBMV ', info)
        RETURN
      ELSE IF ((m .EQ. 0 .OR. n .EQ. 0) .OR. (alpha .EQ. zero .AND. beta
     +    .EQ. one)) THEN
C
C     Quick return if possible.
C
        RETURN
      ELSE
C
C     Set  LENX  and  LENY, the lengths of the vectors x and y, and set
C     up the start points in  X  and  Y.
C
        IF (LSAME(trans, 'N')) THEN
          lenx = n
          leny = m
        ELSE
          lenx = m
          leny = n
        END IF
        IF (incx .GT. 0) THEN
          kx = 1
        ELSE
          kx = 1 - (lenx-1)*incx
        END IF
        IF (incy .GT. 0) THEN
          ky = 1
        ELSE
          ky = 1 - (leny-1)*incy
        END IF
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through the band part of A.
C
C     First form  y := beta*y.
C
        IF (beta .NE. one) THEN
          IF (incy .EQ. 1) THEN
            IF (beta .EQ. zero) THEN
              DO i=1,leny
                DO nd=1,nbdirs
                  yd(nd, i) = 0.D0
                ENDDO
                y(i) = zero
              ENDDO
            ELSE
              DO i=1,leny
                DO nd=1,nbdirs
                  yd(nd, i) = y(i)*betad(nd) + beta*yd(nd, i)
                ENDDO
                y(i) = beta*y(i)
              ENDDO
            END IF
          ELSE
            iy = ky
            IF (beta .EQ. zero) THEN
              DO i=1,leny
                DO nd=1,nbdirs
                  yd(nd, iy) = 0.D0
                ENDDO
                y(iy) = zero
                iy = iy + incy
              ENDDO
            ELSE
              DO i=1,leny
                DO nd=1,nbdirs
                  yd(nd, iy) = y(iy)*betad(nd) + beta*yd(nd, iy)
                ENDDO
                y(iy) = beta*y(iy)
                iy = iy + incy
              ENDDO
            END IF
          END IF
        END IF
        IF (alpha .EQ. zero) THEN
          RETURN
        ELSE
          kup1 = ku + 1
          IF (LSAME(trans, 'N')) THEN
C
C        Form  y := alpha*A*x + y.
C
            jx = kx
            IF (incy .EQ. 1) THEN
              DO j=1,n
                DO nd=1,nbdirs
                  tempd(nd) = x(jx)*alphad(nd) + alpha*xd(nd, jx)
                ENDDO
                temp = alpha*x(jx)
                k = kup1 - j
                IF (1 .LT. j - ku) THEN
                  max1 = j - ku
                ELSE
                  max1 = 1
                END IF
                IF (m .GT. j + kl) THEN
                  min1 = j + kl
                ELSE
                  min1 = m
                END IF
                DO i=max1,min1
                  DO nd=1,nbdirs
                    yd(nd, i) = yd(nd, i) + a(k+i, j)*tempd(nd) + temp*
     +                ad(nd, k+i, j)
                  ENDDO
                  y(i) = y(i) + temp*a(k+i, j)
                ENDDO
                jx = jx + incx
              ENDDO
            ELSE
              DO j=1,n
                DO nd=1,nbdirs
                  tempd(nd) = x(jx)*alphad(nd) + alpha*xd(nd, jx)
                ENDDO
                temp = alpha*x(jx)
                iy = ky
                k = kup1 - j
                IF (1 .LT. j - ku) THEN
                  max2 = j - ku
                ELSE
                  max2 = 1
                END IF
                IF (m .GT. j + kl) THEN
                  min2 = j + kl
                ELSE
                  min2 = m
                END IF
                DO i=max2,min2
                  DO nd=1,nbdirs
                    yd(nd, iy) = yd(nd, iy) + a(k+i, j)*tempd(nd) + temp
     +                *ad(nd, k+i, j)
                  ENDDO
                  y(iy) = y(iy) + temp*a(k+i, j)
                  iy = iy + incy
                ENDDO
                jx = jx + incx
                IF (j .GT. ku) ky = ky + incy
              ENDDO
            END IF
          ELSE
C
C        Form  y := alpha*A**T*x + y.
C
            jy = ky
            IF (incx .EQ. 1) THEN
              DO j=1,n
                temp = zero
                k = kup1 - j
                IF (1 .LT. j - ku) THEN
                  max3 = j - ku
                ELSE
                  max3 = 1
                END IF
                IF (m .GT. j + kl) THEN
                  min3 = j + kl
                  DO nd=1,nbdirsmax
                    tempd(nd) = 0.D0
                  ENDDO
                ELSE
                  min3 = m
                  DO nd=1,nbdirsmax
                    tempd(nd) = 0.D0
                  ENDDO
                END IF
                DO i=max3,min3
                  DO nd=1,nbdirs
                    tempd(nd) = tempd(nd) + x(i)*ad(nd, k+i, j) + a(k+i
     +                , j)*xd(nd, i)
                  ENDDO
                  temp = temp + a(k+i, j)*x(i)
                ENDDO
                DO nd=1,nbdirs
                  yd(nd, jy) = yd(nd, jy) + temp*alphad(nd) + alpha*
     +              tempd(nd)
                ENDDO
                y(jy) = y(jy) + alpha*temp
                jy = jy + incy
              ENDDO
            ELSE
              DO j=1,n
                temp = zero
                ix = kx
                k = kup1 - j
                IF (1 .LT. j - ku) THEN
                  max4 = j - ku
                ELSE
                  max4 = 1
                END IF
                IF (m .GT. j + kl) THEN
                  min4 = j + kl
                  DO nd=1,nbdirsmax
                    tempd(nd) = 0.D0
                  ENDDO
                ELSE
                  min4 = m
                  DO nd=1,nbdirsmax
                    tempd(nd) = 0.D0
                  ENDDO
                END IF
                DO i=max4,min4
                  DO nd=1,nbdirs
                    tempd(nd) = tempd(nd) + x(ix)*ad(nd, k+i, j) + a(k+i
     +                , j)*xd(nd, ix)
                  ENDDO
                  temp = temp + a(k+i, j)*x(ix)
                  ix = ix + incx
                ENDDO
                DO nd=1,nbdirs
                  yd(nd, jy) = yd(nd, jy) + temp*alphad(nd) + alpha*
     +              tempd(nd)
                ENDDO
                y(jy) = y(jy) + alpha*temp
                jy = jy + incy
                IF (j .GT. ku) kx = kx + incx
              ENDDO
            END IF
          END IF
C
          RETURN
C
C     End of DGBMV
C
        END IF
      END IF
      END

