C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dgemv in reverse (adjoint) mode:
C   gradient     of useful results: y
C   with respect to varying inputs: alpha x y beta a
C   RW status of diff variables: alpha:out x:out y:in-out beta:out
C                a:out
C> \brief \b DGEMV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DGEMV(TRANS,M,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
C
C       .. Scalar Arguments ..
C       DOUBLE PRECISION ALPHA,BETA
C       INTEGER INCX,INCY,LDA,M,N
C       CHARACTER TRANS
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION A(LDA,*),X(*),Y(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> DGEMV  performs one of the matrix-vector operations
C>
C>    y := alpha*A*x + beta*y,   or   y := alpha*A**T*x + beta*y,
C>
C> where alpha and beta are scalars, x and y are vectors and A is an
C> m by n matrix.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] TRANS
C> \verbatim
C>          TRANS is CHARACTER*1
C>           On entry, TRANS specifies the operation to be performed as
C>           follows:
C>
C>              TRANS = 'N' or 'n'   y := alpha*A*x + beta*y.
C>
C>              TRANS = 'T' or 't'   y := alpha*A**T*x + beta*y.
C>
C>              TRANS = 'C' or 'c'   y := alpha*A**T*x + beta*y.
C> \endverbatim
C>
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry, M specifies the number of rows of the matrix A.
C>           M must be at least zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the number of columns of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is DOUBLE PRECISION.
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is DOUBLE PRECISION array, dimension ( LDA, N )
C>           Before entry, the leading m by n part of the array A must
C>           contain the matrix of coefficients.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, m ).
C> \endverbatim
C>
C> \param[in] X
C> \verbatim
C>          X is DOUBLE PRECISION array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ) when TRANS = 'N' or 'n'
C>           and at least
C>           ( 1 + ( m - 1 )*abs( INCX ) ) otherwise.
C>           Before entry, the incremented array X must contain the
C>           vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is DOUBLE PRECISION.
C>           On entry, BETA specifies the scalar beta. When BETA is
C>           supplied as zero then Y need not be set on input.
C> \endverbatim
C>
C> \param[in,out] Y
C> \verbatim
C>          Y is DOUBLE PRECISION array, dimension at least
C>           ( 1 + ( m - 1 )*abs( INCY ) ) when TRANS = 'N' or 'n'
C>           and at least
C>           ( 1 + ( n - 1 )*abs( INCY ) ) otherwise.
C>           Before entry with BETA non-zero, the incremented array Y
C>           must contain the vector y. On exit, Y is overwritten by the
C>           updated vector y.
C>           If either m or n is zero, then Y not referenced and the function
C>           performs a quick return.
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>           On entry, INCY specifies the increment for the elements of
C>           Y. INCY must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup gemv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>  The vector and matrix arguments are not referenced when N = 0, or M = 0
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DGEMV_B(trans, m, n, alpha, alphab, a, ab, lda, x, xb, 
     +                   incx, beta, betab, y, yb, incy)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE2OFa should be the size of dimension 2 of array a
C  Hint: ISIZE1OFx should be the size of dimension 1 of array x
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION alpha, beta
      DOUBLE PRECISION alphab, betab
      INTEGER incx, incy, lda, m, n
      CHARACTER trans
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION a(lda, *), x(*), y(*)
      DOUBLE PRECISION ab(lda, *), xb(*), yb(*)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      DOUBLE PRECISION one, zero
      PARAMETER (one=1.0d+0, zero=0.0d+0)
C     ..
C     .. Local Scalars ..
      DOUBLE PRECISION temp
      DOUBLE PRECISION tempb
      INTEGER i, info, ix, iy, j, jx, jy, kx, ky, lenx, leny
      EXTERNAL LSAME
      INTEGER ISIZE1OFX, ISIZE2OFA
C     ..
C     .. External Functions ..
      INTEGER get_ISIZE1OFX, get_ISIZE2OFA
      EXTERNAL get_ISIZE1OFX, get_ISIZE2OFA
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA, check_ISIZE1OFX_initialized, check_ISIZE2OFA_initialized
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX
      INTEGER max1
      INTEGER*4 branch
      INTEGER ii2
      INTEGER ii1
C     ..
C
C     Test the input parameters.
C
      CALL check_ISIZE1OFX_initialized()
      CALL check_ISIZE2OFA_initialized()
      ISIZE1OFX = get_ISIZE1OFX()
      ISIZE2OFA = get_ISIZE2OFA()
      info = 0
      IF (.NOT.LSAME(trans, 'N') .AND. (.NOT.LSAME(trans, 'T')) .AND. (
     +    .NOT.LSAME(trans, 'C'))) THEN
        CALL PUSHCONTROL3B(0)
        info = 1
      ELSE IF (m .LT. 0) THEN
        CALL PUSHCONTROL3B(1)
        info = 2
      ELSE IF (n .LT. 0) THEN
        CALL PUSHCONTROL3B(2)
        info = 3
      ELSE
        IF (1 .LT. m) THEN
          max1 = m
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          CALL PUSHCONTROL3B(3)
          info = 6
        ELSE IF (incx .EQ. 0) THEN
          CALL PUSHCONTROL3B(4)
          info = 8
        ELSE IF (incy .EQ. 0) THEN
          CALL PUSHCONTROL3B(5)
          info = 11
        ELSE
          CALL PUSHCONTROL3B(5)
        END IF
      END IF
      IF (info .EQ. 0) THEN
C
C     Quick return if possible.
C
        IF ((m .EQ. 0 .OR. n .EQ. 0) .OR. (alpha .EQ. zero .AND. beta 
     +      .EQ. one)) THEN
          alphab = 0.D0
          DO ii1=1,ISIZE1OFx
            xb(ii1) = 0.D0
          ENDDO
          betab = 0.D0
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              ab(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
        ELSE
C
C     Set  LENX  and  LENY, the lengths of the vectors x and y, and set
C     up the start points in  X  and  Y.
C
          IF (LSAME(trans, 'N')) THEN
            lenx = n
            leny = m
          ELSE
            lenx = m
            leny = n
          END IF
          IF (incx .GT. 0) THEN
            kx = 1
          ELSE
            kx = 1 - (lenx-1)*incx
          END IF
          IF (incy .GT. 0) THEN
            ky = 1
          ELSE
            ky = 1 - (leny-1)*incy
          END IF
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through A.
C
C     First form  y := beta*y.
C
          IF (beta .NE. one) THEN
            IF (incy .EQ. 1) THEN
              IF (beta .EQ. zero) THEN
                CALL PUSHCONTROL3B(0)
              ELSE
                CALL PUSHCONTROL3B(1)
              END IF
            ELSE
              iy = ky
              IF (beta .EQ. zero) THEN
                DO i=1,leny
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHCONTROL3B(2)
              ELSE
                DO i=1,leny
                  CALL PUSHREAL8(y(iy))
                  y(iy) = beta*y(iy)
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHCONTROL3B(3)
              END IF
            END IF
          ELSE
            CALL PUSHCONTROL3B(4)
          END IF
          IF (alpha .EQ. zero) THEN
            alphab = 0.D0
            DO ii1=1,ISIZE1OFx
              xb(ii1) = 0.D0
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                ab(ii2, ii1) = 0.D0
              ENDDO
            ENDDO
          ELSE IF (LSAME(trans, 'N')) THEN
C
C        Form  y := alpha*A*x + y.
C
            jx = kx
            IF (incy .EQ. 1) THEN
              DO j=1,n
                CALL PUSHINTEGER4(jx)
                jx = jx + incx
              ENDDO
              alphab = 0.D0
              DO ii1=1,ISIZE1OFx
                xb(ii1) = 0.D0
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  ab(ii2, ii1) = 0.D0
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jx)
                temp = alpha*x(jx)
                tempb = 0.D0
                DO i=m,1,-1
                  tempb = tempb + a(i, j)*yb(i)
                  ab(i, j) = ab(i, j) + temp*yb(i)
                ENDDO
                alphab = alphab + x(jx)*tempb
                xb(jx) = xb(jx) + alpha*tempb
              ENDDO
            ELSE
              DO j=1,n
                iy = ky
                DO i=1,m
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHINTEGER4(jx)
                jx = jx + incx
              ENDDO
              alphab = 0.D0
              DO ii1=1,ISIZE1OFx
                xb(ii1) = 0.D0
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  ab(ii2, ii1) = 0.D0
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jx)
                temp = alpha*x(jx)
                tempb = 0.D0
                DO i=m,1,-1
                  CALL POPINTEGER4(iy)
                  tempb = tempb + a(i, j)*yb(iy)
                  ab(i, j) = ab(i, j) + temp*yb(iy)
                ENDDO
                alphab = alphab + x(jx)*tempb
                xb(jx) = xb(jx) + alpha*tempb
              ENDDO
            END IF
          ELSE
C
C        Form  y := alpha*A**T*x + y.
C
            jy = ky
            IF (incx .EQ. 1) THEN
              DO j=1,n
                CALL PUSHREAL8(temp)
                temp = zero
                DO i=1,m
                  temp = temp + a(i, j)*x(i)
                ENDDO
                CALL PUSHINTEGER4(jy)
                jy = jy + incy
              ENDDO
              alphab = 0.D0
              DO ii1=1,ISIZE1OFx
                xb(ii1) = 0.D0
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  ab(ii2, ii1) = 0.D0
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jy)
                alphab = alphab + temp*yb(jy)
                tempb = alpha*yb(jy)
                DO i=m,1,-1
                  ab(i, j) = ab(i, j) + x(i)*tempb
                  xb(i) = xb(i) + a(i, j)*tempb
                ENDDO
                CALL POPREAL8(temp)
              ENDDO
            ELSE
              DO j=1,n
                CALL PUSHREAL8(temp)
                temp = zero
                ix = kx
                DO i=1,m
                  temp = temp + a(i, j)*x(ix)
                  CALL PUSHINTEGER4(ix)
                  ix = ix + incx
                ENDDO
                CALL PUSHINTEGER4(jy)
                jy = jy + incy
              ENDDO
              alphab = 0.D0
              DO ii1=1,ISIZE1OFx
                xb(ii1) = 0.D0
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  ab(ii2, ii1) = 0.D0
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jy)
                alphab = alphab + temp*yb(jy)
                tempb = alpha*yb(jy)
                DO i=m,1,-1
                  CALL POPINTEGER4(ix)
                  ab(i, j) = ab(i, j) + x(ix)*tempb
                  xb(ix) = xb(ix) + a(i, j)*tempb
                ENDDO
                CALL POPREAL8(temp)
              ENDDO
            END IF
          END IF
          CALL POPCONTROL3B(branch)
          IF (branch .LT. 2) THEN
            IF (branch .EQ. 0) THEN
              DO i=leny,1,-1
                yb(i) = 0.D0
              ENDDO
              betab = 0.D0
            ELSE
              betab = 0.D0
              DO i=leny,1,-1
                betab = betab + y(i)*yb(i)
                yb(i) = beta*yb(i)
              ENDDO
            END IF
          ELSE IF (branch .EQ. 2) THEN
            DO i=leny,1,-1
              CALL POPINTEGER4(iy)
              yb(iy) = 0.D0
            ENDDO
            betab = 0.D0
          ELSE IF (branch .EQ. 3) THEN
            betab = 0.D0
            DO i=leny,1,-1
              CALL POPINTEGER4(iy)
              CALL POPREAL8(y(iy))
              betab = betab + y(iy)*yb(iy)
              yb(iy) = beta*yb(iy)
            ENDDO
          ELSE
            betab = 0.D0
          END IF
        END IF
      END IF
      CALL POPCONTROL3B(branch)
      END

