C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dgemm in reverse (adjoint) mode:
C   gradient     of useful results: c
C   with respect to varying inputs: alpha beta a b c
C   RW status of diff variables: alpha:out beta:out a:out b:out
C                c:in-out
C> \brief \b DGEMM
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
C
C       .. Scalar Arguments ..
C       DOUBLE PRECISION ALPHA,BETA
C       INTEGER K,LDA,LDB,LDC,M,N
C       CHARACTER TRANSA,TRANSB
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION A(LDA,*),B(LDB,*),C(LDC,*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> DGEMM  performs one of the matrix-matrix operations
C>
C>    C := alpha*op( A )*op( B ) + beta*C,
C>
C> where  op( X ) is one of
C>
C>    op( X ) = X   or   op( X ) = X**T,
C>
C> alpha and beta are scalars, and A, B and C are matrices, with op( A )
C> an m by k matrix,  op( B )  a  k by n matrix and  C an m by n matrix.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] TRANSA
C> \verbatim
C>          TRANSA is CHARACTER*1
C>           On entry, TRANSA specifies the form of op( A ) to be used in
C>           the matrix multiplication as follows:
C>
C>              TRANSA = 'N' or 'n',  op( A ) = A.
C>
C>              TRANSA = 'T' or 't',  op( A ) = A**T.
C>
C>              TRANSA = 'C' or 'c',  op( A ) = A**T.
C> \endverbatim
C>
C> \param[in] TRANSB
C> \verbatim
C>          TRANSB is CHARACTER*1
C>           On entry, TRANSB specifies the form of op( B ) to be used in
C>           the matrix multiplication as follows:
C>
C>              TRANSB = 'N' or 'n',  op( B ) = B.
C>
C>              TRANSB = 'T' or 't',  op( B ) = B**T.
C>
C>              TRANSB = 'C' or 'c',  op( B ) = B**T.
C> \endverbatim
C>
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry,  M  specifies  the number  of rows  of the  matrix
C>           op( A )  and of the  matrix  C.  M  must  be at least  zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry,  N  specifies the number  of columns of the matrix
C>           op( B ) and the number of columns of the matrix C. N must be
C>           at least zero.
C> \endverbatim
C>
C> \param[in] K
C> \verbatim
C>          K is INTEGER
C>           On entry,  K  specifies  the number of columns of the matrix
C>           op( A ) and the number of rows of the matrix op( B ). K must
C>           be at least  zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is DOUBLE PRECISION.
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is DOUBLE PRECISION array, dimension ( LDA, ka ), where ka is
C>           k  when  TRANSA = 'N' or 'n',  and is  m  otherwise.
C>           Before entry with  TRANSA = 'N' or 'n',  the leading  m by k
C>           part of the array  A  must contain the matrix  A,  otherwise
C>           the leading  k by m  part of the array  A  must contain  the
C>           matrix A.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. When  TRANSA = 'N' or 'n' then
C>           LDA must be at least  max( 1, m ), otherwise  LDA must be at
C>           least  max( 1, k ).
C> \endverbatim
C>
C> \param[in] B
C> \verbatim
C>          B is DOUBLE PRECISION array, dimension ( LDB, kb ), where kb is
C>           n  when  TRANSB = 'N' or 'n',  and is  k  otherwise.
C>           Before entry with  TRANSB = 'N' or 'n',  the leading  k by n
C>           part of the array  B  must contain the matrix  B,  otherwise
C>           the leading  n by k  part of the array  B  must contain  the
C>           matrix B.
C> \endverbatim
C>
C> \param[in] LDB
C> \verbatim
C>          LDB is INTEGER
C>           On entry, LDB specifies the first dimension of B as declared
C>           in the calling (sub) program. When  TRANSB = 'N' or 'n' then
C>           LDB must be at least  max( 1, k ), otherwise  LDB must be at
C>           least  max( 1, n ).
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is DOUBLE PRECISION.
C>           On entry,  BETA  specifies the scalar  beta.  When  BETA  is
C>           supplied as zero then C need not be set on input.
C> \endverbatim
C>
C> \param[in,out] C
C> \verbatim
C>          C is DOUBLE PRECISION array, dimension ( LDC, N )
C>           Before entry, the leading  m by n  part of the array  C must
C>           contain the matrix  C,  except when  beta  is zero, in which
C>           case C need not be set on entry.
C>           On exit, the array  C  is overwritten by the  m by n  matrix
C>           ( alpha*op( A )*op( B ) + beta*C ).
C> \endverbatim
C>
C> \param[in] LDC
C> \verbatim
C>          LDC is INTEGER
C>           On entry, LDC specifies the first dimension of C as declared
C>           in  the  calling  (sub)  program.   LDC  must  be  at  least
C>           max( 1, m ).
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup gemm
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 3 Blas routine.
C>
C>  -- Written on 8-February-1989.
C>     Jack Dongarra, Argonne National Laboratory.
C>     Iain Duff, AERE Harwell.
C>     Jeremy Du Croz, Numerical Algorithms Group Ltd.
C>     Sven Hammarling, Numerical Algorithms Group Ltd.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DGEMM_B(transa, transb, m, n, k, alpha, alphab, a, ab, 
     +                   lda, b, bb, ldb, beta, betab, c, cb, ldc)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE2OFb should be the size of dimension 2 of array b
C  Hint: ISIZE2OFa should be the size of dimension 2 of array a
C
C  -- Reference BLAS level3 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION alpha, beta
      DOUBLE PRECISION alphab, betab
      INTEGER k, lda, ldb, ldc, m, n
      CHARACTER transa, transb
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION a(lda, *), b(ldb, *), c(ldc, *)
      DOUBLE PRECISION ab(lda, *), bb(ldb, *), cb(ldc, *)
      EXTERNAL LSAME
C     ..
C
C  =====================================================================
C
C     .. External Functions ..
      INTEGER get_ISIZE2OFA, get_ISIZE2OFB
      EXTERNAL get_ISIZE2OFA, get_ISIZE2OFB
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA, check_ISIZE2OFA_initialized, check_ISIZE2OFB_initialized
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX
C     ..
C     .. Local Scalars ..
      DOUBLE PRECISION temp
      DOUBLE PRECISION tempb
      INTEGER i, info, j, l, nrowa, nrowb
      LOGICAL nota, notb
      INTEGER ISIZE2OFA, ISIZE2OFB
C     ..
C     .. Parameters ..
      DOUBLE PRECISION one, zero
      PARAMETER (one=1.0d+0, zero=0.0d+0)
      INTEGER max1
      INTEGER max2
      INTEGER max3
      INTEGER*4 branch
      INTEGER ii2
      INTEGER ii1
C     ..
C
C     Set  NOTA  and  NOTB  as  true if  A  and  B  respectively are not
C     transposed and set  NROWA and NROWB  as the number of rows of  A
C     and  B  respectively.
C
      CALL check_ISIZE2OFA_initialized()
      CALL check_ISIZE2OFB_initialized()
      ISIZE2OFA = get_ISIZE2OFA()
      ISIZE2OFB = get_ISIZE2OFB()
      nota = LSAME(transa, 'N')
      notb = LSAME(transb, 'N')
      IF (nota) THEN
        nrowa = m
      ELSE
        nrowa = k
      END IF
      IF (notb) THEN
        nrowb = k
      ELSE
        nrowb = n
      END IF
C
C     Test the input parameters.
C
      info = 0
      IF (.NOT.nota .AND. (.NOT.LSAME(transa, 'C')) .AND. (.NOT.LSAME(
     +    transa, 'T'))) THEN
        CALL PUSHCONTROL3B(0)
        info = 1
      ELSE IF (.NOT.notb .AND. (.NOT.LSAME(transb, 'C')) .AND. (.NOT.
     +    LSAME(transb, 'T'))) THEN
        CALL PUSHCONTROL3B(1)
        info = 2
      ELSE IF (m .LT. 0) THEN
        CALL PUSHCONTROL3B(2)
        info = 3
      ELSE IF (n .LT. 0) THEN
        CALL PUSHCONTROL3B(3)
        info = 4
      ELSE IF (k .LT. 0) THEN
        CALL PUSHCONTROL3B(4)
        info = 5
      ELSE
        IF (1 .LT. nrowa) THEN
          max1 = nrowa
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          CALL PUSHCONTROL3B(5)
          info = 8
        ELSE
          IF (1 .LT. nrowb) THEN
            max2 = nrowb
          ELSE
            max2 = 1
          END IF
          IF (ldb .LT. max2) THEN
            CALL PUSHCONTROL3B(6)
            info = 10
          ELSE
            IF (1 .LT. m) THEN
              max3 = m
            ELSE
              max3 = 1
            END IF
            IF (ldc .LT. max3) THEN
              CALL PUSHCONTROL3B(7)
              info = 13
            ELSE
              CALL PUSHCONTROL3B(7)
            END IF
          END IF
        END IF
      END IF
      IF (info .EQ. 0) THEN
C
C     Quick return if possible.
C
        IF ((m .EQ. 0 .OR. n .EQ. 0) .OR. ((alpha .EQ. zero .OR. k .EQ. 
     +      0) .AND. beta .EQ. one)) THEN
          alphab = 0.D0
          betab = 0.D0
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              ab(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO ii1=1,ISIZE2OFb
            DO ii2=1,ldb
              bb(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
        ELSE IF (alpha .EQ. zero) THEN
C
C     And if  alpha.eq.zero.
C
          IF (beta .EQ. zero) THEN
            DO j=n,1,-1
              DO i=m,1,-1
                cb(i, j) = 0.D0
              ENDDO
            ENDDO
            betab = 0.D0
          ELSE
            betab = 0.D0
            DO j=n,1,-1
              DO i=m,1,-1
                betab = betab + c(i, j)*cb(i, j)
                cb(i, j) = beta*cb(i, j)
              ENDDO
            ENDDO
          END IF
          alphab = 0.D0
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              ab(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO ii1=1,ISIZE2OFb
            DO ii2=1,ldb
              bb(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
        ELSE IF (notb) THEN
C
C     Start the operations.
C
          IF (nota) THEN
C
C           Form  C := alpha*A*B + beta*C.
C
            DO j=1,n
              IF (beta .EQ. zero) THEN
                CALL PUSHCONTROL2B(2)
              ELSE IF (beta .NE. one) THEN
                CALL PUSHCONTROL2B(1)
              ELSE
                CALL PUSHCONTROL2B(0)
              END IF
            ENDDO
            alphab = 0.D0
            betab = 0.D0
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                ab(ii2, ii1) = 0.D0
              ENDDO
            ENDDO
            DO ii1=1,ISIZE2OFb
              DO ii2=1,ldb
                bb(ii2, ii1) = 0.D0
              ENDDO
            ENDDO
            DO j=n,1,-1
              DO l=k,1,-1
                temp = alpha*b(l, j)
                tempb = 0.D0
                DO i=m,1,-1
                  tempb = tempb + a(i, l)*cb(i, j)
                  ab(i, l) = ab(i, l) + temp*cb(i, j)
                ENDDO
                alphab = alphab + b(l, j)*tempb
                bb(l, j) = bb(l, j) + alpha*tempb
              ENDDO
              CALL POPCONTROL2B(branch)
              IF (branch .NE. 0) THEN
                IF (branch .EQ. 1) THEN
                  DO i=m,1,-1
                    betab = betab + c(i, j)*cb(i, j)
                    cb(i, j) = beta*cb(i, j)
                  ENDDO
                ELSE
                  DO i=m,1,-1
                    cb(i, j) = 0.D0
                  ENDDO
                END IF
              END IF
            ENDDO
          ELSE
C
C           Form  C := alpha*A**T*B + beta*C
C
            DO j=1,n
              DO i=1,m
                CALL PUSHREAL8(temp)
                temp = zero
                DO l=1,k
                  temp = temp + a(l, i)*b(l, j)
                ENDDO
                IF (beta .EQ. zero) THEN
                  CALL PUSHCONTROL1B(0)
                ELSE
                  CALL PUSHCONTROL1B(1)
                END IF
              ENDDO
            ENDDO
            alphab = 0.D0
            betab = 0.D0
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                ab(ii2, ii1) = 0.D0
              ENDDO
            ENDDO
            DO ii1=1,ISIZE2OFb
              DO ii2=1,ldb
                bb(ii2, ii1) = 0.D0
              ENDDO
            ENDDO
            DO j=n,1,-1
              DO i=m,1,-1
                CALL POPCONTROL1B(branch)
                IF (branch .EQ. 0) THEN
                  alphab = alphab + temp*cb(i, j)
                  tempb = alpha*cb(i, j)
                  cb(i, j) = 0.D0
                ELSE
                  alphab = alphab + temp*cb(i, j)
                  tempb = alpha*cb(i, j)
                  betab = betab + c(i, j)*cb(i, j)
                  cb(i, j) = beta*cb(i, j)
                END IF
                DO l=k,1,-1
                  ab(l, i) = ab(l, i) + b(l, j)*tempb
                  bb(l, j) = bb(l, j) + a(l, i)*tempb
                ENDDO
                CALL POPREAL8(temp)
              ENDDO
            ENDDO
          END IF
        ELSE IF (nota) THEN
C
C           Form  C := alpha*A*B**T + beta*C
C
          DO j=1,n
            IF (beta .EQ. zero) THEN
              CALL PUSHCONTROL2B(2)
            ELSE IF (beta .NE. one) THEN
              CALL PUSHCONTROL2B(1)
            ELSE
              CALL PUSHCONTROL2B(0)
            END IF
          ENDDO
          alphab = 0.D0
          betab = 0.D0
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              ab(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO ii1=1,ISIZE2OFb
            DO ii2=1,ldb
              bb(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO j=n,1,-1
            DO l=k,1,-1
              temp = alpha*b(j, l)
              tempb = 0.D0
              DO i=m,1,-1
                tempb = tempb + a(i, l)*cb(i, j)
                ab(i, l) = ab(i, l) + temp*cb(i, j)
              ENDDO
              alphab = alphab + b(j, l)*tempb
              bb(j, l) = bb(j, l) + alpha*tempb
            ENDDO
            CALL POPCONTROL2B(branch)
            IF (branch .NE. 0) THEN
              IF (branch .EQ. 1) THEN
                DO i=m,1,-1
                  betab = betab + c(i, j)*cb(i, j)
                  cb(i, j) = beta*cb(i, j)
                ENDDO
              ELSE
                DO i=m,1,-1
                  cb(i, j) = 0.D0
                ENDDO
              END IF
            END IF
          ENDDO
        ELSE
C
C           Form  C := alpha*A**T*B**T + beta*C
C
          DO j=1,n
            DO i=1,m
              CALL PUSHREAL8(temp)
              temp = zero
              DO l=1,k
                temp = temp + a(l, i)*b(j, l)
              ENDDO
              IF (beta .EQ. zero) THEN
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHCONTROL1B(1)
              END IF
            ENDDO
          ENDDO
          alphab = 0.D0
          betab = 0.D0
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              ab(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO ii1=1,ISIZE2OFb
            DO ii2=1,ldb
              bb(ii2, ii1) = 0.D0
            ENDDO
          ENDDO
          DO j=n,1,-1
            DO i=m,1,-1
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                alphab = alphab + temp*cb(i, j)
                tempb = alpha*cb(i, j)
                cb(i, j) = 0.D0
              ELSE
                alphab = alphab + temp*cb(i, j)
                tempb = alpha*cb(i, j)
                betab = betab + c(i, j)*cb(i, j)
                cb(i, j) = beta*cb(i, j)
              END IF
              DO l=k,1,-1
                ab(l, i) = ab(l, i) + b(j, l)*tempb
                bb(j, l) = bb(j, l) + a(l, i)*tempb
              ENDDO
              CALL POPREAL8(temp)
            ENDDO
          ENDDO
        END IF
      END IF
      CALL POPCONTROL3B(branch)
      END

