C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dswap in reverse (adjoint) mode:
C   gradient     of useful results: dx dy
C   with respect to varying inputs: dx dy
C   RW status of diff variables: dx:in-out dy:in-out
C> \brief \b DSWAP
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DSWAP(N,DX,INCX,DY,INCY)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION DX(*),DY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C>    DSWAP interchanges two vectors.
C>    uses unrolled loops for increments equal to 1.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in,out] DX
C> \verbatim
C>          DX is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of DX
C> \endverbatim
C>
C> \param[in,out] DY
C> \verbatim
C>          DY is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of DY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup swap
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, linpack, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DSWAP_B(n, dx, dxb, incx, dy, dyb, incy)
      IMPLICIT NONE
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, incy, n
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION dx(*), dy(*)
      DOUBLE PRECISION dxb(*), dyb(*)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      DOUBLE PRECISION dtemp
      DOUBLE PRECISION dtempb
      INTEGER i, ix, iy, m, mp1
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MOD
      INTEGER*4 branch
C     ..
      IF (n .GT. 0) THEN
        IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C       code for both increments equal to 1
C
C
C       clean-up loop
C
          m = MOD(n, 3)
          IF (m .NE. 0) THEN
            IF (n .LT. 3) THEN
              GOTO 100
            ELSE
              CALL PUSHCONTROL1B(0)
            END IF
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          mp1 = m + 1
          DO i=n-MOD(n-mp1, 3),mp1,-3
            dtempb = dyb(i+2)
            dyb(i+2) = dxb(i+2)
            dxb(i+2) = dtempb
            dtempb = dyb(i+1)
            dyb(i+1) = dxb(i+1)
            dxb(i+1) = dtempb
            dtempb = dyb(i)
            dyb(i) = dxb(i)
            dxb(i) = dtempb
          ENDDO
          CALL POPCONTROL1B(branch)
          IF (branch .NE. 0) GOTO 110
 100      DO i=m,1,-1
            dtempb = dyb(i)
            dyb(i) = dxb(i)
            dxb(i) = dtempb
          ENDDO
        ELSE
C
C       code for unequal increments or equal increments not equal
C         to 1
C
          ix = 1
          iy = 1
          IF (incx .LT. 0) ix = (-n+1)*incx + 1
          IF (incy .LT. 0) iy = (-n+1)*incy + 1
          DO i=1,n
            CALL PUSHINTEGER4(ix)
            ix = ix + incx
            CALL PUSHINTEGER4(iy)
            iy = iy + incy
          ENDDO
          DO i=n,1,-1
            CALL POPINTEGER4(iy)
            CALL POPINTEGER4(ix)
            dtempb = dyb(iy)
            dyb(iy) = dxb(ix)
            dxb(ix) = dtempb
          ENDDO
        END IF
      END IF
 110  CONTINUE
      END

