C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of dswap in forward (tangent) mode (with options multiDirectional):
C   variations   of useful results: dx dy
C   with respect to varying inputs: dx dy
C   RW status of diff variables: dx:in-out dy:in-out
C> \brief \b DSWAP
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DSWAP(N,DX,INCX,DY,INCY)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION DX(*),DY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C>    DSWAP interchanges two vectors.
C>    uses unrolled loops for increments equal to 1.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in,out] DX
C> \verbatim
C>          DX is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of DX
C> \endverbatim
C>
C> \param[in,out] DY
C> \verbatim
C>          DY is DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of DY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup swap
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, linpack, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE DSWAP_DV(n, dx, dxd, incx, dy, dyd, incy, nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, incy, n
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION dx(*), dy(*)
      DOUBLE PRECISION dxd(nbdirsmax, *), dyd(nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      DOUBLE PRECISION dtemp
      DOUBLE PRECISION dtempd(nbdirsmax)
      INTEGER i, ix, iy, m, mp1
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MOD
      INTEGER nd
      INTEGER nbdirs
C     ..
C     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
        STOP 1
      END IF
C
      IF (n .LE. 0) THEN
        RETURN
      ELSE
        IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C       code for both increments equal to 1
C
C
C       clean-up loop
C
          m = MOD(n, 3)
          IF (m .NE. 0) THEN
            DO i=1,m
              DO nd=1,nbdirs
                dtempd(nd) = dxd(nd, i)
                dxd(nd, i) = dyd(nd, i)
                dyd(nd, i) = dtempd(nd)
              ENDDO
              dtemp = dx(i)
              dx(i) = dy(i)
              dy(i) = dtemp
            ENDDO
            IF (n .LT. 3) RETURN
          END IF
          mp1 = m + 1
          DO i=mp1,n,3
            DO nd=1,nbdirs
              dtempd(nd) = dxd(nd, i)
              dxd(nd, i) = dyd(nd, i)
              dyd(nd, i) = dtempd(nd)
              dtempd(nd) = dxd(nd, i+1)
              dxd(nd, i+1) = dyd(nd, i+1)
              dyd(nd, i+1) = dtempd(nd)
              dtempd(nd) = dxd(nd, i+2)
              dxd(nd, i+2) = dyd(nd, i+2)
              dyd(nd, i+2) = dtempd(nd)
            ENDDO
            dtemp = dx(i)
            dx(i) = dy(i)
            dy(i) = dtemp
            dtemp = dx(i+1)
            dx(i+1) = dy(i+1)
            dy(i+1) = dtemp
            dtemp = dx(i+2)
            dx(i+2) = dy(i+2)
            dy(i+2) = dtemp
          ENDDO
        ELSE
C
C       code for unequal increments or equal increments not equal
C         to 1
C
          ix = 1
          iy = 1
          IF (incx .LT. 0) ix = (-n+1)*incx + 1
          IF (incy .LT. 0) iy = (-n+1)*incy + 1
          DO i=1,n
            DO nd=1,nbdirs
              dtempd(nd) = dxd(nd, ix)
              dxd(nd, ix) = dyd(nd, iy)
              dyd(nd, iy) = dtempd(nd)
            ENDDO
            dtemp = dx(ix)
            dx(ix) = dy(iy)
            dy(iy) = dtemp
            ix = ix + incx
            iy = iy + incy
          ENDDO
        END IF
        RETURN
C
C     End of DSWAP
C
      END IF
      END

