C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
C
C  Differentiation of dtrsv in forward (tangent) mode:
C   variations   of useful results: x
C   with respect to varying inputs: x a
C   RW status of diff variables: x:in-out a:in
C> \brief \b DTRSV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DTRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,LDA,N
C       CHARACTER DIAG,TRANS,UPLO
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION A(LDA,*),X(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> DTRSV  solves one of the systems of equations
C>
C>    A*x = b,   or   A**T*x = b,
C>
C> where b and x are n element vectors and A is an n by n unit, or
C> non-unit, upper or lower triangular matrix.
C>
C> No test for singularity or near-singularity is included in this
C> routine. Such tests must be performed before calling this routine.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the matrix is an upper or
C>           lower triangular matrix as follows:
C>
C>              UPLO = 'U' or 'u'   A is an upper triangular matrix.
C>
C>              UPLO = 'L' or 'l'   A is a lower triangular matrix.
C> \endverbatim
C>
C> \param[in] TRANS
C> \verbatim
C>          TRANS is CHARACTER*1
C>           On entry, TRANS specifies the equations to be solved as
C>           follows:
C>
C>              TRANS = 'N' or 'n'   A*x = b.
C>
C>              TRANS = 'T' or 't'   A**T*x = b.
C>
C>              TRANS = 'C' or 'c'   A**T*x = b.
C> \endverbatim
C>
C> \param[in] DIAG
C> \verbatim
C>          DIAG is CHARACTER*1
C>           On entry, DIAG specifies whether or not A is unit
C>           triangular as follows:
C>
C>              DIAG = 'U' or 'u'   A is assumed to be unit triangular.
C>
C>              DIAG = 'N' or 'n'   A is not assumed to be unit
C>                                  triangular.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the order of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is DOUBLE PRECISION array, dimension ( LDA, N )
C>           Before entry with  UPLO = 'U' or 'u', the leading n by n
C>           upper triangular part of the array A must contain the upper
C>           triangular matrix and the strictly lower triangular part of
C>           A is not referenced.
C>           Before entry with UPLO = 'L' or 'l', the leading n by n
C>           lower triangular part of the array A must contain the lower
C>           triangular matrix and the strictly upper triangular part of
C>           A is not referenced.
C>           Note that when  DIAG = 'U' or 'u', the diagonal elements of
C>           A are not referenced either, but are assumed to be unity.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, n ).
C> \endverbatim
C>
C> \param[in,out] X
C> \verbatim
C>          X is DOUBLE PRECISION array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the n
C>           element right-hand side vector b. On exit, X is overwritten
C>           with the solution vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C>
C>  Level 2 Blas routine.
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup trsv
C
C  =====================================================================
      SUBROUTINE DTRSV_D(UPLO, TRANS, DIAG, N, A, AD, LDA, X, XD, INCX)
C
C Forward-mode derivative of STRSV via the black-box / Giles-style
C approach: differentiate op(A)*s = b directly (the exact vector case
C from the Giles appendix). Uses only the original STRSV and STRMV.
C
C CONVENTION (matches the primal STRSV's own in-place behavior):
C   X, XD : overwritten in place with the solution S and its
C           derivative dS, exactly like the primal/forward routine.
C
      IMPLICIT NONE
      CHARACTER UPLO, TRANS, DIAG
      INTEGER N, LDA, INCX
      DOUBLE PRECISION A(LDA,*), AD(LDA,*)
      DOUBLE PRECISION X(*), XD(*)

      DOUBLE PRECISION S(N), W(N)
      INTEGER I, KX

      IF (N.EQ.0) RETURN

      IF (INCX.GE.1) THEN
         KX = 1
      ELSE
         KX = 1 - (N-1)*INCX
      END IF

C     Solve for S, overwriting X in place
      CALL DTRSV(UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
      DO I = 1, N
         S(I) = X(KX + (I-1)*INCX)
      END DO

C     T = op(Ad)*S  (local copy, unit stride)
      DO I = 1, N
         W(I) = S(I)
      END DO
C     'N' not DIAG: unit A has a constant (unit) diagonal, so AD diag=0.
      CALL DTRMV(UPLO, TRANS, 'N', N, AD, LDA, W, 1)

C     RHS = Xd_in - T
      DO I = 1, N
         W(I) = XD(KX + (I-1)*INCX) - W(I)
      END DO

C     Solve op(A)*dS = RHS -> W holds dS
      CALL DTRSV(UPLO, TRANS, DIAG, N, A, LDA, W, 1)

      DO I = 1, N
         XD(KX + (I-1)*INCX) = W(I)
      END DO

      RETURN
      END SUBROUTINE DTRSV_D

