C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
C
C  Differentiation of dtrsm in forward (tangent) mode (with options multiDirectional):
C   variations   of useful results: b
C   with respect to varying inputs: alpha a b
C   RW status of diff variables: alpha:in a:in b:in-out
C> \brief \b DTRSM
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE DTRSM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
C
C       .. Scalar Arguments ..
C       DOUBLE PRECISION ALPHA
C       INTEGER LDA,LDB,M,N
C       CHARACTER DIAG,SIDE,TRANSA,UPLO
C       ..
C       .. Array Arguments ..
C       DOUBLE PRECISION A(LDA,*),B(LDB,*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> DTRSM  solves one of the matrix equations
C>
C>    op( A )*X = alpha*B,   or   X*op( A ) = alpha*B,
C>
C> where alpha is a scalar, X and B are m by n matrices, A is a unit, or
C> non-unit,  upper or lower triangular matrix  and  op( A )  is one  of
C>
C>    op( A ) = A   or   op( A ) = A**T.
C>
C> The matrix X is overwritten on B.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] SIDE
C> \verbatim
C>          SIDE is CHARACTER*1
C>           On entry, SIDE specifies whether op( A ) appears on the left
C>           or right of X as follows:
C>
C>              SIDE = 'L' or 'l'   op( A )*X = alpha*B.
C>
C>              SIDE = 'R' or 'r'   X*op( A ) = alpha*B.
C> \endverbatim
C>
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the matrix A is an upper or
C>           lower triangular matrix as follows:
C>
C>              UPLO = 'U' or 'u'   A is an upper triangular matrix.
C>
C>              UPLO = 'L' or 'l'   A is a lower triangular matrix.
C> \endverbatim
C>
C> \param[in] TRANSA
C> \verbatim
C>          TRANSA is CHARACTER*1
C>           On entry, TRANSA specifies the form of op( A ) to be used in
C>           the matrix multiplication as follows:
C>
C>              TRANSA = 'N' or 'n'   op( A ) = A.
C>
C>              TRANSA = 'T' or 't'   op( A ) = A**T.
C>
C>              TRANSA = 'C' or 'c'   op( A ) = A**T.
C> \endverbatim
C>
C> \param[in] DIAG
C> \verbatim
C>          DIAG is CHARACTER*1
C>           On entry, DIAG specifies whether or not A is unit triangular
C>           as follows:
C>
C>              DIAG = 'U' or 'u'   A is assumed to be unit triangular.
C>
C>              DIAG = 'N' or 'n'   A is not assumed to be unit
C>                                  triangular.
C> \endverbatim
C>
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry, M specifies the number of rows of B. M must be at
C>           least zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the number of columns of B.  N must be
C>           at least zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is DOUBLE PRECISION.
C>           On entry,  ALPHA specifies the scalar  alpha. When  alpha is
C>           zero then  A is not referenced and  B need not be set before
C>           entry.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is DOUBLE PRECISION array, dimension ( LDA, k ),
C>           where k is m when SIDE = 'L' or 'l'
C>             and k is n when SIDE = 'R' or 'r'.
C>           Before entry  with  UPLO = 'U' or 'u',  the  leading  k by k
C>           upper triangular part of the array  A must contain the upper
C>           triangular matrix  and the strictly lower triangular part of
C>           A is not referenced.
C>           Before entry  with  UPLO = 'L' or 'l',  the  leading  k by k
C>           lower triangular part of the array  A must contain the lower
C>           triangular matrix  and the strictly upper triangular part of
C>           A is not referenced.
C>           Note that when  DIAG = 'U' or 'u',  the diagonal elements of
C>           A  are not referenced either,  but are assumed to be  unity.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program.  When  SIDE = 'L' or 'l'  then
C>           LDA  must be at least  max( 1, m ),  when  SIDE = 'R' or 'r'
C>           then LDA must be at least max( 1, n ).
C> \endverbatim
C>
C> \param[in,out] B
C> \verbatim
C>          B is DOUBLE PRECISION array, dimension ( LDB, N )
C>           Before entry,  the leading  m by n part of the array  B must
C>           contain  the  right-hand  side  matrix  B,  and  on exit  is
C>           overwritten by the solution matrix  X.
C> \endverbatim
C>
C> \param[in] LDB
C> \verbatim
C>          LDB is INTEGER
C>           On entry, LDB specifies the first dimension of B as declared
C>           in  the  calling  (sub)  program.   LDB  must  be  at  least
C>           max( 1, m ).
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup trsm
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 3 Blas routine.
C>
C>
C>  -- Written on 8-February-1989.
C>     Jack Dongarra, Argonne National Laboratory.
C>     Iain Duff, AERE Harwell.
C>     Jeremy Du Croz, Numerical Algorithms Group Ltd.
C>     Sven Hammarling, Numerical Algorithms Group Ltd.
C> \endverbatim
C>
C  =====================================================================
C      SUBROUTINE DTRSM_DV(side, uplo, transa, diag, m, n, alpha, alphad
C     +                    , a, ad, lda, b, bd, ldb, nbdirs)
C      IMPLICIT NONE
C      INCLUDE 'DIFFSIZES.inc'
CC  Hint: nbdirsmax should be the maximum number of differentiation directions
CC
CC  -- Reference BLAS level3 routine --
CC  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
CC  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
CC
CC     .. Scalar Arguments ..
C      DOUBLE PRECISION alpha
C      DOUBLE PRECISION alphad(nbdirsmax)
C      INTEGER lda, ldb, m, n
C      CHARACTER diag, side, transa, uplo
CC     ..
CC     .. Array Arguments ..
C      DOUBLE PRECISION a(lda, *), b(ldb, *)
C      DOUBLE PRECISION ad(nbdirsmax, lda, *), bd(nbdirsmax, ldb, *)
C      EXTERNAL LSAME
CC     ..
CC
CC  =====================================================================
CC
CC     .. External Functions ..
C      LOGICAL LSAME
CC     ..
CC     .. External Subroutines ..
C      EXTERNAL XERBLA
CC     ..
CC     .. Intrinsic Functions ..
C      INTRINSIC MAX
CC     ..
CC     .. Local Scalars ..
C      DOUBLE PRECISION temp
C      DOUBLE PRECISION tempd(nbdirsmax)
C      INTEGER i, info, j, k, nrowa
C      LOGICAL lside, nounit, upper
CC     ..
CC     .. Parameters ..
C      DOUBLE PRECISION zero
C      PARAMETER (zero=0.0d+0)
C      INTEGER max1
C      INTEGER max2
C      INTEGER nd
C      DOUBLE PRECISION temp0
C      INTEGER nbdirs
CC     ..
CC
CC     Test the input parameters.
CC
CC     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
C      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
C        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
C     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
C        STOP 1
C      END IF
CC
C      lside = LSAME(side, 'L')
C      IF (lside) THEN
C        nrowa = m
C      ELSE
C        nrowa = n
C      END IF
C      nounit = LSAME(diag, 'N')
C      upper = LSAME(uplo, 'U')
CC
C      info = 0
C      IF (.NOT.lside .AND. (.NOT.LSAME(side, 'R'))) THEN
C        info = 1
C      ELSE IF (.NOT.upper .AND. (.NOT.LSAME(uplo, 'L'))) THEN
C        info = 2
C      ELSE IF (.NOT.LSAME(transa, 'N') .AND. (.NOT.LSAME(transa, 'T')) 
C     +    .AND. (.NOT.LSAME(transa, 'C'))) THEN
C        info = 3
C      ELSE IF (.NOT.LSAME(diag, 'U') .AND. (.NOT.LSAME(diag, 'N'))) THEN
C        info = 4
C      ELSE IF (m .LT. 0) THEN
C        info = 5
C      ELSE IF (n .LT. 0) THEN
C        info = 6
C      ELSE
C        IF (1 .LT. nrowa) THEN
C          max1 = nrowa
C        ELSE
C          max1 = 1
C        END IF
C        IF (lda .LT. max1) THEN
C          info = 9
C        ELSE
C          IF (1 .LT. m) THEN
C            max2 = m
C          ELSE
C            max2 = 1
C          END IF
C          IF (ldb .LT. max2) info = 11
C        END IF
C      END IF
C      IF (info .NE. 0) THEN
C        CALL XERBLA('DTRSM ', info)
C        RETURN
C      ELSE IF (m .EQ. 0 .OR. n .EQ. 0) THEN
CC
CC     Quick return if possible.
CC
C        RETURN
C      ELSE IF (alpha .EQ. zero) THEN
CC
CC     And when  alpha.eq.zero.
CC
C        DO j=1,n
C          DO i=1,m
C            DO nd=1,nbdirs
C              bd(nd, i, j) = 0.D0
C            ENDDO
C            b(i, j) = zero
C          ENDDO
C        ENDDO
C        RETURN
C      ELSE
CC
CC     Start the operations.
CC
C        IF (lside) THEN
C          IF (LSAME(transa, 'N')) THEN
CC
CC           Form  B := alpha*inv( A )*B.
CC
C            IF (upper) THEN
C              DO j=1,n
C                DO i=1,m
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = b(i, j)*alphad(nd) + alpha*bd(nd, i, 
C     +                j)
C                  ENDDO
C                  b(i, j) = alpha*b(i, j)
C                ENDDO
C                DO k=m,1,-1
C                  IF (nounit) THEN
C                    temp0 = b(k, j)/a(k, k)
C                    DO nd=1,nbdirs
C                      bd(nd, k, j) = (bd(nd, k, j)-temp0*ad(nd, k, k))/a
C     +                  (k, k)
C                    ENDDO
C                    b(k, j) = temp0
C                  END IF
C                  DO i=1,k-1
C                    DO nd=1,nbdirs
C                      bd(nd, i, j) = bd(nd, i, j) - a(i, k)*bd(nd, k, j)
C     +                  - b(k, j)*ad(nd, i, k)
C                    ENDDO
C                    b(i, j) = b(i, j) - b(k, j)*a(i, k)
C                  ENDDO
C                ENDDO
C              ENDDO
C            ELSE
C              DO j=1,n
C                DO i=1,m
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = b(i, j)*alphad(nd) + alpha*bd(nd, i, 
C     +                j)
C                  ENDDO
C                  b(i, j) = alpha*b(i, j)
C                ENDDO
C                DO k=1,m
C                  IF (nounit) THEN
C                    temp0 = b(k, j)/a(k, k)
C                    DO nd=1,nbdirs
C                      bd(nd, k, j) = (bd(nd, k, j)-temp0*ad(nd, k, k))/a
C     +                  (k, k)
C                    ENDDO
C                    b(k, j) = temp0
C                  END IF
C                  DO i=k+1,m
C                    DO nd=1,nbdirs
C                      bd(nd, i, j) = bd(nd, i, j) - a(i, k)*bd(nd, k, j)
C     +                  - b(k, j)*ad(nd, i, k)
C                    ENDDO
C                    b(i, j) = b(i, j) - b(k, j)*a(i, k)
C                  ENDDO
C                ENDDO
C              ENDDO
C            END IF
C          ELSE IF (upper) THEN
CC
CC           Form  B := alpha*inv( A**T )*B.
CC
C            DO j=1,n
C              DO i=1,m
C                DO nd=1,nbdirs
C                  tempd(nd) = b(i, j)*alphad(nd) + alpha*bd(nd, i, j)
C                ENDDO
C                temp = alpha*b(i, j)
C                DO k=1,i-1
C                  DO nd=1,nbdirs
C                    tempd(nd) = tempd(nd) - b(k, j)*ad(nd, k, i) - a(k, 
C     +                i)*bd(nd, k, j)
C                  ENDDO
C                  temp = temp - a(k, i)*b(k, j)
C                ENDDO
C                IF (nounit) THEN
C                  temp0 = temp/a(i, i)
C                  DO nd=1,nbdirs
C                    tempd(nd) = (tempd(nd)-temp0*ad(nd, i, i))/a(i, i)
C                  ENDDO
C                  temp = temp0
C                END IF
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = tempd(nd)
C                ENDDO
C                b(i, j) = temp
C              ENDDO
C            ENDDO
C          ELSE
C            DO j=1,n
C              DO i=m,1,-1
C                DO nd=1,nbdirs
C                  tempd(nd) = b(i, j)*alphad(nd) + alpha*bd(nd, i, j)
C                ENDDO
C                temp = alpha*b(i, j)
C                DO k=i+1,m
C                  DO nd=1,nbdirs
C                    tempd(nd) = tempd(nd) - b(k, j)*ad(nd, k, i) - a(k, 
C     +                i)*bd(nd, k, j)
C                  ENDDO
C                  temp = temp - a(k, i)*b(k, j)
C                ENDDO
C                IF (nounit) THEN
C                  temp0 = temp/a(i, i)
C                  DO nd=1,nbdirs
C                    tempd(nd) = (tempd(nd)-temp0*ad(nd, i, i))/a(i, i)
C                  ENDDO
C                  temp = temp0
C                END IF
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = tempd(nd)
C                ENDDO
C                b(i, j) = temp
C              ENDDO
C            ENDDO
C          END IF
C        ELSE IF (LSAME(transa, 'N')) THEN
CC
CC           Form  B := alpha*B*inv( A ).
CC
C          IF (upper) THEN
C            DO j=1,n
C              DO i=1,m
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = b(i, j)*alphad(nd) + alpha*bd(nd, i, j)
C                ENDDO
C                b(i, j) = alpha*b(i, j)
C              ENDDO
C              DO k=1,j-1
C                DO i=1,m
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = bd(nd, i, j) - b(i, k)*ad(nd, k, j) -
C     +                a(k, j)*bd(nd, i, k)
C                  ENDDO
C                  b(i, j) = b(i, j) - a(k, j)*b(i, k)
C                ENDDO
C              ENDDO
C              IF (nounit) THEN
C                DO i=1,m
C                  temp0 = b(i, j)/a(j, j)
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = (bd(nd, i, j)-temp0*ad(nd, j, j))/a(j
C     +                , j)
C                  ENDDO
C                  b(i, j) = temp0
C                ENDDO
C              END IF
C            ENDDO
C          ELSE
C            DO j=n,1,-1
C              DO i=1,m
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = b(i, j)*alphad(nd) + alpha*bd(nd, i, j)
C                ENDDO
C                b(i, j) = alpha*b(i, j)
C              ENDDO
C              DO k=j+1,n
C                DO i=1,m
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = bd(nd, i, j) - b(i, k)*ad(nd, k, j) -
C     +                a(k, j)*bd(nd, i, k)
C                  ENDDO
C                  b(i, j) = b(i, j) - a(k, j)*b(i, k)
C                ENDDO
C              ENDDO
C              IF (nounit) THEN
C                DO i=1,m
C                  temp0 = b(i, j)/a(j, j)
C                  DO nd=1,nbdirs
C                    bd(nd, i, j) = (bd(nd, i, j)-temp0*ad(nd, j, j))/a(j
C     +                , j)
C                  ENDDO
C                  b(i, j) = temp0
C                ENDDO
C              END IF
C            ENDDO
C          END IF
C        ELSE IF (upper) THEN
CC
CC           Form  B := alpha*B*inv( A**T ).
CC
C          DO k=n,1,-1
C            IF (nounit) THEN
C              DO i=1,m
C                temp0 = b(i, k)/a(k, k)
C                DO nd=1,nbdirs
C                  bd(nd, i, k) = (bd(nd, i, k)-temp0*ad(nd, k, k))/a(k, 
C     +              k)
C                ENDDO
C                b(i, k) = temp0
C              ENDDO
C            END IF
C            DO j=1,k-1
C              DO i=1,m
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = bd(nd, i, j) - b(i, k)*ad(nd, j, k) - a
C     +              (j, k)*bd(nd, i, k)
C                ENDDO
C                b(i, j) = b(i, j) - a(j, k)*b(i, k)
C              ENDDO
C            ENDDO
C            DO i=1,m
C              DO nd=1,nbdirs
C                bd(nd, i, k) = b(i, k)*alphad(nd) + alpha*bd(nd, i, k)
C              ENDDO
C              b(i, k) = alpha*b(i, k)
C            ENDDO
C          ENDDO
C        ELSE
C          DO k=1,n
C            IF (nounit) THEN
C              DO i=1,m
C                temp0 = b(i, k)/a(k, k)
C                DO nd=1,nbdirs
C                  bd(nd, i, k) = (bd(nd, i, k)-temp0*ad(nd, k, k))/a(k, 
C     +              k)
C                ENDDO
C                b(i, k) = temp0
C              ENDDO
C            END IF
C            DO j=k+1,n
C              DO i=1,m
C                DO nd=1,nbdirs
C                  bd(nd, i, j) = bd(nd, i, j) - b(i, k)*ad(nd, j, k) - a
C     +              (j, k)*bd(nd, i, k)
C                ENDDO
C                b(i, j) = b(i, j) - a(j, k)*b(i, k)
C              ENDDO
C            ENDDO
C            DO i=1,m
C              DO nd=1,nbdirs
C                bd(nd, i, k) = b(i, k)*alphad(nd) + alpha*bd(nd, i, k)
C              ENDDO
C              b(i, k) = alpha*b(i, k)
C            ENDDO
C          ENDDO
C        END IF
CC
C        RETURN
CC
CC     End of DTRSM
CC
C      END IF
C      END

      SUBROUTINE DTRSM_DV(SIDE, UPLO, TRANSA, DIAG, M, N,
     +                    ALPHA, ALPHAD, A, AD, LDA, B, BD, LDB, NBDIRS)
C
C Vector forward-mode derivative of DTRSM (black-box / Giles-style):
C differentiates op(A)*X = alpha*B directly, using only the original
C DTRSM and DTRMM. Self-contained, does not call DTRSM_D.
C
C AD/BD store direction as the FASTEST-varying index (nbdirsmax, LDA/LDB, *),
C so each direction's slice is gathered into a plain work array before use.
C
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
      CHARACTER SIDE, UPLO, TRANSA, DIAG
      INTEGER M, N, LDA, LDB, NBDIRS
      DOUBLE PRECISION ALPHA
      DOUBLE PRECISION ALPHAD(NBDIRSMAX)
      DOUBLE PRECISION A(LDA,*), AD(NBDIRSMAX,LDA,*)
      DOUBLE PRECISION B(LDB,*), BD(NBDIRSMAX,LDB,*)

      DOUBLE PRECISION X(M,N), T(M,N)
      DOUBLE PRECISION AD_SLICE(LDA,N), BD_SLICE(LDB,N)
      INTEGER ND, I, J

      IF (NBDIRS.LE.0 .OR. NBDIRS.GT.NBDIRSMAX) THEN
         WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', NBDIRS,
     +      ' must be in 1..nbdirsmax=', NBDIRSMAX, '. Stopping.'
         STOP 1
      END IF

      IF (M.EQ.0 .OR. N.EQ.0) RETURN

C     X = solution of the original forward call (same for every direction)
      DO J = 1, N
         DO I = 1, M
            X(I,J) = B(I,J)
         END DO
      END DO
      CALL DTRSM(SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, X, M)

      DO ND = 1, NBDIRS

C        Gather this direction out of the interleaved AD/BD layout
         DO J = 1, N
            DO I = 1, M
               AD_SLICE(I,J) = AD(ND,I,J)
               BD_SLICE(I,J) = BD(ND,I,J)
            END DO
         END DO

C        T = op(Ad)*X  (SIDE='L')  or  X*op(Ad)  (SIDE='R')
         DO J = 1, N
            DO I = 1, M
               T(I,J) = X(I,J)
            END DO
         END DO
         CALL DTRMM(SIDE, UPLO, TRANSA, DIAG, M, N, 1.0D0,
     +              AD_SLICE, LDA, T, M)

C        RHS = alphad*B + alpha*Bd - T, built in place in BD_SLICE
         DO J = 1, N
            DO I = 1, M
               BD_SLICE(I,J) = ALPHAD(ND)*B(I,J) + ALPHA*BD_SLICE(I,J)
     +                         - T(I,J)
            END DO
         END DO

C        Solve the same triangular system again -> dX for this direction
         CALL DTRSM(SIDE, UPLO, TRANSA, DIAG, M, N, 1.0D0,
     +              A, LDA, BD_SLICE, LDB)

C        Scatter the result back into the interleaved layout
         DO J = 1, N
            DO I = 1, M
               BD(ND,I,J) = BD_SLICE(I,J)
            END DO
         END DO

      END DO

      RETURN
      END SUBROUTINE DTRSM_DV
