C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of ssymv in reverse (adjoint) mode (with options multiDirectional):
C   gradient     of useful results: y
C   with respect to varying inputs: alpha x y beta a
C   RW status of diff variables: alpha:out x:out y:in-out beta:out
C                a:out
C> \brief \b SSYMV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE SSYMV(UPLO,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
C
C       .. Scalar Arguments ..
C       REAL ALPHA,BETA
C       INTEGER INCX,INCY,LDA,N
C       CHARACTER UPLO
C       ..
C       .. Array Arguments ..
C       REAL A(LDA,*),X(*),Y(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> SSYMV  performs the matrix-vector  operation
C>
C>    y := alpha*A*x + beta*y,
C>
C> where alpha and beta are scalars, x and y are n element vectors and
C> A is an n by n symmetric matrix.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the upper or lower
C>           triangular part of the array A is to be referenced as
C>           follows:
C>
C>              UPLO = 'U' or 'u'   Only the upper triangular part of A
C>                                  is to be referenced.
C>
C>              UPLO = 'L' or 'l'   Only the lower triangular part of A
C>                                  is to be referenced.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the order of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is REAL
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is REAL array, dimension ( LDA, N )
C>           Before entry with  UPLO = 'U' or 'u', the leading n by n
C>           upper triangular part of the array A must contain the upper
C>           triangular part of the symmetric matrix and the strictly
C>           lower triangular part of A is not referenced.
C>           Before entry with UPLO = 'L' or 'l', the leading n by n
C>           lower triangular part of the array A must contain the lower
C>           triangular part of the symmetric matrix and the strictly
C>           upper triangular part of A is not referenced.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, n ).
C> \endverbatim
C>
C> \param[in] X
C> \verbatim
C>          X is REAL array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the n
C>           element vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is REAL
C>           On entry, BETA specifies the scalar beta. When BETA is
C>           supplied as zero then Y need not be set on input.
C> \endverbatim
C>
C> \param[in,out] Y
C> \verbatim
C>          Y is REAL array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCY ) ).
C>           Before entry, the incremented array Y must contain the n
C>           element vector y. On exit, Y is overwritten by the updated
C>           vector y.
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>           On entry, INCY specifies the increment for the elements of
C>           Y. INCY must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup hemv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>  The vector and matrix arguments are not referenced when N = 0, or M = 0
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE SSYMV_BV(uplo, n, alpha, alphab, a, ab, lda, x, xb, 
     +                    incx, beta, betab, y, yb, incy, nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE2OFa should be the size of dimension 2 of array a
C  Hint: ISIZE1OFx should be the size of dimension 1 of array x
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      REAL alpha, beta
      REAL alphab(nbdirsmax), betab(nbdirsmax)
      INTEGER incx, incy, lda, n
      CHARACTER uplo
C     ..
C     .. Array Arguments ..
      REAL a(lda, *), x(*), y(*)
      REAL ab(nbdirsmax, lda, *), xb(nbdirsmax, *), yb(nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      REAL one, zero
      PARAMETER (one=1.0e+0, zero=0.0e+0)
C     ..
C     .. Local Scalars ..
      REAL temp1, temp2
      REAL temp1b(nbdirsmax), temp2b(nbdirsmax)
      INTEGER i, info, ix, iy, j, jx, jy, kx, ky
      EXTERNAL LSAME
      INTEGER ISIZE1OFX, ISIZE2OFA
C     ..
C     .. External Functions ..
      INTEGER get_ISIZE1OFX, get_ISIZE2OFA
      EXTERNAL get_ISIZE1OFX, get_ISIZE2OFA
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA, check_ISIZE1OFX_initialized, check_ISIZE2OFA_initialized
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX
      INTEGER max1
      INTEGER nd
      INTEGER ad_to
      INTEGER ad_to0
      INTEGER ad_from
      INTEGER ad_from0
      INTEGER*4 branch
      INTEGER ii2
      INTEGER ii1
      INTEGER nbdirs
C     ..
C
C     Test the input parameters.
C
C     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
      CALL check_ISIZE1OFX_initialized()
      CALL check_ISIZE2OFA_initialized()
      ISIZE1OFX = get_ISIZE1OFX()
      ISIZE2OFA = get_ISIZE2OFA()
      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
        STOP 1
      END IF
C
      info = 0
      IF (.NOT.LSAME(uplo, 'U') .AND. (.NOT.LSAME(uplo, 'L'))) THEN
        CALL PUSHCONTROL3B(0)
        info = 1
      ELSE IF (n .LT. 0) THEN
        CALL PUSHCONTROL3B(1)
        info = 2
      ELSE
        IF (1 .LT. n) THEN
          max1 = n
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          CALL PUSHCONTROL3B(2)
          info = 5
        ELSE IF (incx .EQ. 0) THEN
          CALL PUSHCONTROL3B(3)
          info = 7
        ELSE IF (incy .EQ. 0) THEN
          CALL PUSHCONTROL3B(4)
          info = 10
        ELSE
          CALL PUSHCONTROL3B(4)
        END IF
      END IF
      IF (info .EQ. 0) THEN
C
C     Quick return if possible.
C
        IF (n .EQ. 0 .OR. (alpha .EQ. zero .AND. beta .EQ. one)) THEN
          DO nd=1,nbdirsmax
            alphab(nd) = 0.0
          ENDDO
          DO ii1=1,ISIZE1OFx
            DO nd=1,nbdirsmax
              xb(nd, ii1) = 0.0
            ENDDO
          ENDDO
          DO nd=1,nbdirsmax
            betab(nd) = 0.0
          ENDDO
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              DO nd=1,nbdirsmax
                ab(nd, ii2, ii1) = 0.0
              ENDDO
            ENDDO
          ENDDO
        ELSE
C
C     Set up the start points in  X  and  Y.
C
          IF (incx .GT. 0) THEN
            kx = 1
          ELSE
            kx = 1 - (n-1)*incx
          END IF
          IF (incy .GT. 0) THEN
            ky = 1
          ELSE
            ky = 1 - (n-1)*incy
          END IF
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through the triangular part
C     of A.
C
C     First form  y := beta*y.
C
          IF (beta .NE. one) THEN
            IF (incy .EQ. 1) THEN
              IF (beta .EQ. zero) THEN
                CALL PUSHCONTROL3B(0)
              ELSE
                CALL PUSHCONTROL3B(1)
              END IF
            ELSE
              iy = ky
              IF (beta .EQ. zero) THEN
                DO i=1,n
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHCONTROL3B(2)
              ELSE
                DO i=1,n
                  CALL PUSHREAL4(y(iy))
                  y(iy) = beta*y(iy)
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHCONTROL3B(3)
              END IF
            END IF
          ELSE
            CALL PUSHCONTROL3B(4)
          END IF
          IF (alpha .EQ. zero) THEN
            DO nd=1,nbdirsmax
              alphab(nd) = 0.0
            ENDDO
            DO ii1=1,ISIZE1OFx
              DO nd=1,nbdirsmax
                xb(nd, ii1) = 0.0
              ENDDO
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                DO nd=1,nbdirsmax
                  ab(nd, ii2, ii1) = 0.0
                ENDDO
              ENDDO
            ENDDO
          ELSE IF (LSAME(uplo, 'U')) THEN
C
C        Form  y  when A is stored in upper triangle.
C
            IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
              DO j=1,n
                CALL PUSHREAL4(temp2)
                temp2 = zero
                DO i=1,j-1
                  temp2 = temp2 + a(i, j)*x(i)
                ENDDO
                CALL PUSHINTEGER4(i - 1)
              ENDDO
              DO nd=1,nbdirsmax
                alphab(nd) = 0.0
              ENDDO
              DO ii1=1,ISIZE1OFx
                DO nd=1,nbdirsmax
                  xb(nd, ii1) = 0.0
                ENDDO
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                temp1 = alpha*x(j)
                DO nd=1,nbdirs
                  temp1b(nd) = a(j, j)*yb(nd, j)
                  ab(nd, j, j) = ab(nd, j, j) + temp1*yb(nd, j)
                  alphab(nd) = alphab(nd) + temp2*yb(nd, j)
                  temp2b(nd) = alpha*yb(nd, j)
                ENDDO
                CALL POPINTEGER4(ad_to)
                DO i=ad_to,1,-1
                  DO nd=1,nbdirs
                    ab(nd, i, j) = ab(nd, i, j) + x(i)*temp2b(nd) + 
     +                temp1*yb(nd, i)
                    xb(nd, i) = xb(nd, i) + a(i, j)*temp2b(nd)
                    temp1b(nd) = temp1b(nd) + a(i, j)*yb(nd, i)
                  ENDDO
                ENDDO
                CALL POPREAL4(temp2)
                DO nd=1,nbdirs
                  alphab(nd) = alphab(nd) + x(j)*temp1b(nd)
                  xb(nd, j) = xb(nd, j) + alpha*temp1b(nd)
                ENDDO
              ENDDO
            ELSE
              jx = kx
              jy = ky
              DO j=1,n
                CALL PUSHREAL4(temp2)
                temp2 = zero
                ix = kx
                iy = ky
                DO i=1,j-1
                  temp2 = temp2 + a(i, j)*x(ix)
                  CALL PUSHINTEGER4(ix)
                  ix = ix + incx
                  CALL PUSHINTEGER4(iy)
                  iy = iy + incy
                ENDDO
                CALL PUSHINTEGER4(i - 1)
                CALL PUSHINTEGER4(jx)
                jx = jx + incx
                CALL PUSHINTEGER4(jy)
                jy = jy + incy
              ENDDO
              DO nd=1,nbdirsmax
                alphab(nd) = 0.0
              ENDDO
              DO ii1=1,ISIZE1OFx
                DO nd=1,nbdirsmax
                  xb(nd, ii1) = 0.0
                ENDDO
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jy)
                CALL POPINTEGER4(jx)
                temp1 = alpha*x(jx)
                DO nd=1,nbdirs
                  temp1b(nd) = a(j, j)*yb(nd, jy)
                  ab(nd, j, j) = ab(nd, j, j) + temp1*yb(nd, jy)
                  alphab(nd) = alphab(nd) + temp2*yb(nd, jy)
                  temp2b(nd) = alpha*yb(nd, jy)
                ENDDO
                CALL POPINTEGER4(ad_to0)
                DO i=ad_to0,1,-1
                  CALL POPINTEGER4(iy)
                  CALL POPINTEGER4(ix)
                  DO nd=1,nbdirs
                    ab(nd, i, j) = ab(nd, i, j) + x(ix)*temp2b(nd) + 
     +                temp1*yb(nd, iy)
                    xb(nd, ix) = xb(nd, ix) + a(i, j)*temp2b(nd)
                    temp1b(nd) = temp1b(nd) + a(i, j)*yb(nd, iy)
                  ENDDO
                ENDDO
                CALL POPREAL4(temp2)
                DO nd=1,nbdirs
                  alphab(nd) = alphab(nd) + x(jx)*temp1b(nd)
                  xb(nd, jx) = xb(nd, jx) + alpha*temp1b(nd)
                ENDDO
              ENDDO
            END IF
          ELSE IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C        Form  y  when A is stored in lower triangle.
C
            DO j=1,n
              CALL PUSHREAL4(temp2)
              temp2 = zero
              ad_from = j + 1
              DO i=ad_from,n
                temp2 = temp2 + a(i, j)*x(i)
              ENDDO
              CALL PUSHINTEGER4(ad_from)
            ENDDO
            DO nd=1,nbdirsmax
              alphab(nd) = 0.0
            ENDDO
            DO ii1=1,ISIZE1OFx
              DO nd=1,nbdirsmax
                xb(nd, ii1) = 0.0
              ENDDO
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                DO nd=1,nbdirsmax
                  ab(nd, ii2, ii1) = 0.0
                ENDDO
              ENDDO
            ENDDO
            DO j=n,1,-1
              DO nd=1,nbdirs
                alphab(nd) = alphab(nd) + temp2*yb(nd, j)
                temp2b(nd) = alpha*yb(nd, j)
              ENDDO
              temp1 = alpha*x(j)
              DO nd=1,nbdirsmax
                temp1b(nd) = 0.0
              ENDDO
              CALL POPINTEGER4(ad_from)
              DO i=n,ad_from,-1
                DO nd=1,nbdirs
                  ab(nd, i, j) = ab(nd, i, j) + x(i)*temp2b(nd) + temp1*
     +              yb(nd, i)
                  xb(nd, i) = xb(nd, i) + a(i, j)*temp2b(nd)
                  temp1b(nd) = temp1b(nd) + a(i, j)*yb(nd, i)
                ENDDO
              ENDDO
              DO nd=1,nbdirs
                temp1b(nd) = temp1b(nd) + a(j, j)*yb(nd, j)
                ab(nd, j, j) = ab(nd, j, j) + temp1*yb(nd, j)
                alphab(nd) = alphab(nd) + x(j)*temp1b(nd)
                xb(nd, j) = xb(nd, j) + alpha*temp1b(nd)
              ENDDO
              CALL POPREAL4(temp2)
            ENDDO
          ELSE
            jx = kx
            jy = ky
            DO j=1,n
              CALL PUSHREAL4(temp2)
              temp2 = zero
              CALL PUSHINTEGER4(ix)
              ix = jx
              CALL PUSHINTEGER4(iy)
              iy = jy
              ad_from0 = j + 1
              DO i=ad_from0,n
                CALL PUSHINTEGER4(ix)
                ix = ix + incx
                CALL PUSHINTEGER4(iy)
                iy = iy + incy
                temp2 = temp2 + a(i, j)*x(ix)
              ENDDO
              CALL PUSHINTEGER4(ad_from0)
              CALL PUSHINTEGER4(jx)
              jx = jx + incx
              CALL PUSHINTEGER4(jy)
              jy = jy + incy
            ENDDO
            DO nd=1,nbdirsmax
              alphab(nd) = 0.0
            ENDDO
            DO ii1=1,ISIZE1OFx
              DO nd=1,nbdirsmax
                xb(nd, ii1) = 0.0
              ENDDO
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                DO nd=1,nbdirsmax
                  ab(nd, ii2, ii1) = 0.0
                ENDDO
              ENDDO
            ENDDO
            DO j=n,1,-1
              CALL POPINTEGER4(jy)
              CALL POPINTEGER4(jx)
              temp1 = alpha*x(jx)
              DO nd=1,nbdirs
                alphab(nd) = alphab(nd) + temp2*yb(nd, jy)
                temp2b(nd) = alpha*yb(nd, jy)
              ENDDO
              DO nd=1,nbdirsmax
                temp1b(nd) = 0.0
              ENDDO
              CALL POPINTEGER4(ad_from0)
              DO i=n,ad_from0,-1
                DO nd=1,nbdirs
                  ab(nd, i, j) = ab(nd, i, j) + x(ix)*temp2b(nd) + temp1
     +              *yb(nd, iy)
                  xb(nd, ix) = xb(nd, ix) + a(i, j)*temp2b(nd)
                  temp1b(nd) = temp1b(nd) + a(i, j)*yb(nd, iy)
                ENDDO
                CALL POPINTEGER4(iy)
                CALL POPINTEGER4(ix)
              ENDDO
              CALL POPINTEGER4(iy)
              CALL POPINTEGER4(ix)
              CALL POPREAL4(temp2)
              DO nd=1,nbdirs
                temp1b(nd) = temp1b(nd) + a(j, j)*yb(nd, jy)
                ab(nd, j, j) = ab(nd, j, j) + temp1*yb(nd, jy)
                alphab(nd) = alphab(nd) + x(jx)*temp1b(nd)
                xb(nd, jx) = xb(nd, jx) + alpha*temp1b(nd)
              ENDDO
            ENDDO
          END IF
          CALL POPCONTROL3B(branch)
          IF (branch .LT. 2) THEN
            IF (branch .EQ. 0) THEN
              DO i=n,1,-1
                DO nd=1,nbdirs
                  yb(nd, i) = 0.0
                ENDDO
              ENDDO
              DO nd=1,nbdirsmax
                betab(nd) = 0.0
              ENDDO
            ELSE
              DO nd=1,nbdirsmax
                betab(nd) = 0.0
              ENDDO
              DO i=n,1,-1
                DO nd=1,nbdirs
                  betab(nd) = betab(nd) + y(i)*yb(nd, i)
                  yb(nd, i) = beta*yb(nd, i)
                ENDDO
              ENDDO
            END IF
          ELSE IF (branch .EQ. 2) THEN
            DO i=n,1,-1
              CALL POPINTEGER4(iy)
              DO nd=1,nbdirs
                yb(nd, iy) = 0.0
              ENDDO
            ENDDO
            DO nd=1,nbdirsmax
              betab(nd) = 0.0
            ENDDO
          ELSE IF (branch .EQ. 3) THEN
            DO nd=1,nbdirsmax
              betab(nd) = 0.0
            ENDDO
            DO i=n,1,-1
              CALL POPINTEGER4(iy)
              CALL POPREAL4(y(iy))
              DO nd=1,nbdirs
                betab(nd) = betab(nd) + y(iy)*yb(nd, iy)
                yb(nd, iy) = beta*yb(nd, iy)
              ENDDO
            ENDDO
          ELSE
            DO nd=1,nbdirsmax
              betab(nd) = 0.0
            ENDDO
          END IF
        END IF
      END IF
      CALL POPCONTROL3B(branch)
      END

