C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of strsv in reverse (adjoint) mode (with options multiDirectional):
C   gradient     of useful results: x
C   with respect to varying inputs: x a
C   RW status of diff variables: x:in-out a:out
C> \brief \b STRSV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE STRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,LDA,N
C       CHARACTER DIAG,TRANS,UPLO
C       ..
C       .. Array Arguments ..
C       REAL A(LDA,*),X(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> STRSV  solves one of the systems of equations
C>
C>    A*x = b,   or   A**T*x = b,
C>
C> where b and x are n element vectors and A is an n by n unit, or
C> non-unit, upper or lower triangular matrix.
C>
C> No test for singularity or near-singularity is included in this
C> routine. Such tests must be performed before calling this routine.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the matrix is an upper or
C>           lower triangular matrix as follows:
C>
C>              UPLO = 'U' or 'u'   A is an upper triangular matrix.
C>
C>              UPLO = 'L' or 'l'   A is a lower triangular matrix.
C> \endverbatim
C>
C> \param[in] TRANS
C> \verbatim
C>          TRANS is CHARACTER*1
C>           On entry, TRANS specifies the equations to be solved as
C>           follows:
C>
C>              TRANS = 'N' or 'n'   A*x = b.
C>
C>              TRANS = 'T' or 't'   A**T*x = b.
C>
C>              TRANS = 'C' or 'c'   A**T*x = b.
C> \endverbatim
C>
C> \param[in] DIAG
C> \verbatim
C>          DIAG is CHARACTER*1
C>           On entry, DIAG specifies whether or not A is unit
C>           triangular as follows:
C>
C>              DIAG = 'U' or 'u'   A is assumed to be unit triangular.
C>
C>              DIAG = 'N' or 'n'   A is not assumed to be unit
C>                                  triangular.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the order of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is REAL array, dimension ( LDA, N )
C>           Before entry with  UPLO = 'U' or 'u', the leading n by n
C>           upper triangular part of the array A must contain the upper
C>           triangular matrix and the strictly lower triangular part of
C>           A is not referenced.
C>           Before entry with UPLO = 'L' or 'l', the leading n by n
C>           lower triangular part of the array A must contain the lower
C>           triangular matrix and the strictly upper triangular part of
C>           A is not referenced.
C>           Note that when  DIAG = 'U' or 'u', the diagonal elements of
C>           A are not referenced either, but are assumed to be unity.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, n ).
C> \endverbatim
C>
C> \param[in,out] X
C> \verbatim
C>          X is REAL array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the n
C>           element right-hand side vector b. On exit, X is overwritten
C>           with the solution vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup trsv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE STRSV_BV(uplo, trans, diag, n, a, ab, lda, x, xb, incx
     +                    , nbdirs)
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE2OFa should be the size of dimension 2 of array a
C  Hint: nbdirsmax should be the maximum number of differentiation directions
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, lda, n
      CHARACTER diag, trans, uplo
C     ..
C     .. Array Arguments ..
      REAL a(lda, *), x(*)
      REAL ab(nbdirsmax, lda, *), xb(nbdirsmax, *)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      REAL zero
      PARAMETER (zero=0.0e+0)
C     ..
C     .. Local Scalars ..
      REAL temp
      REAL tempb(nbdirsmax)
      INTEGER i, info, ix, j, jx, kx
      LOGICAL nounit
      EXTERNAL LSAME
      INTEGER ISIZE2OFA
C     ..
C     .. External Functions ..
      INTEGER get_ISIZE2OFA
      EXTERNAL get_ISIZE2OFA
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA, check_ISIZE2OFA_initialized
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX
      INTEGER max1
      INTEGER nd
      REAL tempb0(nbdirsmax)
      INTEGER ad_from
      INTEGER*4 branch
      INTEGER ad_from0
      INTEGER ad_from1
      INTEGER ad_from2
      INTEGER ad_to
      INTEGER ad_to0
      INTEGER ad_to1
      INTEGER ad_to2
      INTEGER ii2
      INTEGER ii1
      INTEGER nbdirs
C     ..
C
C     Test the input parameters.
C
C     Check 0 < nbdirs <= nbdirsmax (required by DIFFSIZES.inc)
      CALL check_ISIZE2OFA_initialized()
      ISIZE2OFA = get_ISIZE2OFA()
      IF (nbdirs.LE.0 .OR. nbdirs.GT.nbdirsmax) THEN
        WRITE(*,'(A,I0,A,I0,A)') 'Error: nbdirs=', nbdirs,
     +  ' must be in 1..nbdirsmax=', nbdirsmax, '. Stopping.'
        STOP 1
      END IF
C
      info = 0
      IF (.NOT.LSAME(uplo, 'U') .AND. (.NOT.LSAME(uplo, 'L'))) THEN
        CALL PUSHCONTROL3B(0)
        info = 1
      ELSE IF (.NOT.LSAME(trans, 'N') .AND. (.NOT.LSAME(trans, 'T')) 
     +    .AND. (.NOT.LSAME(trans, 'C'))) THEN
        CALL PUSHCONTROL3B(1)
        info = 2
      ELSE IF (.NOT.LSAME(diag, 'U') .AND. (.NOT.LSAME(diag, 'N'))) THEN
        CALL PUSHCONTROL3B(2)
        info = 3
      ELSE IF (n .LT. 0) THEN
        CALL PUSHCONTROL3B(3)
        info = 4
      ELSE
        IF (1 .LT. n) THEN
          max1 = n
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          CALL PUSHCONTROL3B(4)
          info = 6
        ELSE IF (incx .EQ. 0) THEN
          CALL PUSHCONTROL3B(5)
          info = 8
        ELSE
          CALL PUSHCONTROL3B(5)
        END IF
      END IF
      IF (info .EQ. 0) THEN
C
C     Quick return if possible.
C
        IF (n .EQ. 0) THEN
          DO ii1=1,ISIZE2OFa
            DO ii2=1,lda
              DO nd=1,nbdirsmax
                ab(nd, ii2, ii1) = 0.0
              ENDDO
            ENDDO
          ENDDO
        ELSE
C
          nounit = LSAME(diag, 'N')
C
C     Set up the start point in X if the increment is not unity. This
C     will be  ( N - 1 )*INCX  too small for descending loops.
C
          IF (incx .LE. 0) THEN
            CALL PUSHCONTROL1B(0)
            kx = 1 - (n-1)*incx
          ELSE IF (incx .NE. 1) THEN
            CALL PUSHCONTROL1B(1)
            kx = 1
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through A.
C
          IF (LSAME(trans, 'N')) THEN
C
C        Form  x := inv( A )*x.
C
            IF (LSAME(uplo, 'U')) THEN
              IF (incx .EQ. 1) THEN
                DO j=n,1,-1
                  IF (x(j) .NE. zero) THEN
                    IF (nounit) THEN
                      CALL PUSHREAL4(x(j))
                      x(j) = x(j)/a(j, j)
                      CALL PUSHCONTROL1B(0)
                    ELSE
                      CALL PUSHCONTROL1B(1)
                    END IF
                    CALL PUSHREAL4(temp)
                    temp = x(j)
                    ad_from = j - 1
                    DO i=ad_from,1,-1
                      CALL PUSHREAL4(x(i))
                      x(i) = x(i) - temp*a(i, j)
                    ENDDO
                    CALL PUSHINTEGER4(ad_from)
                    CALL PUSHCONTROL1B(0)
                  ELSE
                    CALL PUSHCONTROL1B(1)
                  END IF
                ENDDO
                DO ii1=1,ISIZE2OFa
                  DO ii2=1,lda
                    DO nd=1,nbdirsmax
                      ab(nd, ii2, ii1) = 0.0
                    ENDDO
                  ENDDO
                ENDDO
                DO j=1,n,1
                  CALL POPCONTROL1B(branch)
                  IF (branch .EQ. 0) THEN
                    DO nd=1,nbdirsmax
                      tempb(nd) = 0.0
                    ENDDO
                    CALL POPINTEGER4(ad_from)
                    DO i=1,ad_from,1
                      CALL POPREAL4(x(i))
                      DO nd=1,nbdirs
                        tempb(nd) = tempb(nd) - a(i, j)*xb(nd, i)
                        ab(nd, i, j) = ab(nd, i, j) - temp*xb(nd, i)
                      ENDDO
                    ENDDO
                    CALL POPREAL4(temp)
                    DO nd=1,nbdirs
                      xb(nd, j) = xb(nd, j) + tempb(nd)
                    ENDDO
                    CALL POPCONTROL1B(branch)
                    IF (branch .EQ. 0) THEN
                      CALL POPREAL4(x(j))
                      DO nd=1,nbdirs
                        tempb0(nd) = xb(nd, j)/a(j, j)
                        xb(nd, j) = tempb0(nd)
                        ab(nd, j, j) = ab(nd, j, j) - x(j)*tempb0(nd)/a(
     +                    j, j)
                      ENDDO
                    END IF
                  END IF
                ENDDO
              ELSE
                jx = kx + (n-1)*incx
                DO j=n,1,-1
                  IF (x(jx) .NE. zero) THEN
                    IF (nounit) THEN
                      CALL PUSHREAL4(x(jx))
                      x(jx) = x(jx)/a(j, j)
                      CALL PUSHCONTROL1B(0)
                    ELSE
                      CALL PUSHCONTROL1B(1)
                    END IF
                    CALL PUSHREAL4(temp)
                    temp = x(jx)
                    CALL PUSHINTEGER4(ix)
                    ix = jx
                    ad_from0 = j - 1
                    DO i=ad_from0,1,-1
                      CALL PUSHINTEGER4(ix)
                      ix = ix - incx
                      CALL PUSHREAL4(x(ix))
                      x(ix) = x(ix) - temp*a(i, j)
                    ENDDO
                    CALL PUSHINTEGER4(ad_from0)
                    CALL PUSHCONTROL1B(0)
                  ELSE
                    CALL PUSHCONTROL1B(1)
                  END IF
                  CALL PUSHINTEGER4(jx)
                  jx = jx - incx
                ENDDO
                DO ii1=1,ISIZE2OFa
                  DO ii2=1,lda
                    DO nd=1,nbdirsmax
                      ab(nd, ii2, ii1) = 0.0
                    ENDDO
                  ENDDO
                ENDDO
                DO j=1,n,1
                  CALL POPINTEGER4(jx)
                  CALL POPCONTROL1B(branch)
                  IF (branch .EQ. 0) THEN
                    DO nd=1,nbdirsmax
                      tempb(nd) = 0.0
                    ENDDO
                    CALL POPINTEGER4(ad_from0)
                    DO i=1,ad_from0,1
                      DO nd=1,nbdirs
                        tempb(nd) = tempb(nd) - a(i, j)*xb(nd, ix)
                        ab(nd, i, j) = ab(nd, i, j) - temp*xb(nd, ix)
                      ENDDO
                      CALL POPREAL4(x(ix))
                      CALL POPINTEGER4(ix)
                    ENDDO
                    CALL POPINTEGER4(ix)
                    CALL POPREAL4(temp)
                    DO nd=1,nbdirs
                      xb(nd, jx) = xb(nd, jx) + tempb(nd)
                    ENDDO
                    CALL POPCONTROL1B(branch)
                    IF (branch .EQ. 0) THEN
                      CALL POPREAL4(x(jx))
                      DO nd=1,nbdirs
                        tempb0(nd) = xb(nd, jx)/a(j, j)
                        xb(nd, jx) = tempb0(nd)
                        ab(nd, j, j) = ab(nd, j, j) - x(jx)*tempb0(nd)/a
     +                    (j, j)
                      ENDDO
                    END IF
                  END IF
                ENDDO
              END IF
            ELSE IF (incx .EQ. 1) THEN
              DO j=1,n
                IF (x(j) .NE. zero) THEN
                  IF (nounit) THEN
                    CALL PUSHREAL4(x(j))
                    x(j) = x(j)/a(j, j)
                    CALL PUSHCONTROL1B(0)
                  ELSE
                    CALL PUSHCONTROL1B(1)
                  END IF
                  CALL PUSHREAL4(temp)
                  temp = x(j)
                  ad_from1 = j + 1
                  DO i=ad_from1,n
                    CALL PUSHREAL4(x(i))
                    x(i) = x(i) - temp*a(i, j)
                  ENDDO
                  CALL PUSHINTEGER4(ad_from1)
                  CALL PUSHCONTROL1B(0)
                ELSE
                  CALL PUSHCONTROL1B(1)
                END IF
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPCONTROL1B(branch)
                IF (branch .EQ. 0) THEN
                  DO nd=1,nbdirsmax
                    tempb(nd) = 0.0
                  ENDDO
                  CALL POPINTEGER4(ad_from1)
                  DO i=n,ad_from1,-1
                    CALL POPREAL4(x(i))
                    DO nd=1,nbdirs
                      tempb(nd) = tempb(nd) - a(i, j)*xb(nd, i)
                      ab(nd, i, j) = ab(nd, i, j) - temp*xb(nd, i)
                    ENDDO
                  ENDDO
                  CALL POPREAL4(temp)
                  DO nd=1,nbdirs
                    xb(nd, j) = xb(nd, j) + tempb(nd)
                  ENDDO
                  CALL POPCONTROL1B(branch)
                  IF (branch .EQ. 0) THEN
                    CALL POPREAL4(x(j))
                    DO nd=1,nbdirs
                      tempb0(nd) = xb(nd, j)/a(j, j)
                      xb(nd, j) = tempb0(nd)
                      ab(nd, j, j) = ab(nd, j, j) - x(j)*tempb0(nd)/a(j
     +                  , j)
                    ENDDO
                  END IF
                END IF
              ENDDO
            ELSE
              jx = kx
              DO j=1,n
                IF (x(jx) .NE. zero) THEN
                  IF (nounit) THEN
                    CALL PUSHREAL4(x(jx))
                    x(jx) = x(jx)/a(j, j)
                    CALL PUSHCONTROL1B(0)
                  ELSE
                    CALL PUSHCONTROL1B(1)
                  END IF
                  CALL PUSHREAL4(temp)
                  temp = x(jx)
                  CALL PUSHINTEGER4(ix)
                  ix = jx
                  ad_from2 = j + 1
                  DO i=ad_from2,n
                    CALL PUSHINTEGER4(ix)
                    ix = ix + incx
                    CALL PUSHREAL4(x(ix))
                    x(ix) = x(ix) - temp*a(i, j)
                  ENDDO
                  CALL PUSHINTEGER4(ad_from2)
                  CALL PUSHCONTROL1B(0)
                ELSE
                  CALL PUSHCONTROL1B(1)
                END IF
                CALL PUSHINTEGER4(jx)
                jx = jx + incx
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jx)
                CALL POPCONTROL1B(branch)
                IF (branch .EQ. 0) THEN
                  DO nd=1,nbdirsmax
                    tempb(nd) = 0.0
                  ENDDO
                  CALL POPINTEGER4(ad_from2)
                  DO i=n,ad_from2,-1
                    DO nd=1,nbdirs
                      tempb(nd) = tempb(nd) - a(i, j)*xb(nd, ix)
                      ab(nd, i, j) = ab(nd, i, j) - temp*xb(nd, ix)
                    ENDDO
                    CALL POPREAL4(x(ix))
                    CALL POPINTEGER4(ix)
                  ENDDO
                  CALL POPINTEGER4(ix)
                  CALL POPREAL4(temp)
                  DO nd=1,nbdirs
                    xb(nd, jx) = xb(nd, jx) + tempb(nd)
                  ENDDO
                  CALL POPCONTROL1B(branch)
                  IF (branch .EQ. 0) THEN
                    CALL POPREAL4(x(jx))
                    DO nd=1,nbdirs
                      tempb0(nd) = xb(nd, jx)/a(j, j)
                      xb(nd, jx) = tempb0(nd)
                      ab(nd, j, j) = ab(nd, j, j) - x(jx)*tempb0(nd)/a(j
     +                  , j)
                    ENDDO
                  END IF
                END IF
              ENDDO
            END IF
          ELSE IF (LSAME(uplo, 'U')) THEN
C
C        Form  x := inv( A**T )*x.
C
            IF (incx .EQ. 1) THEN
              DO j=1,n
                temp = x(j)
                DO i=1,j-1
                  temp = temp - a(i, j)*x(i)
                ENDDO
                CALL PUSHINTEGER4(i - 1)
                IF (nounit) THEN
                  CALL PUSHREAL4(temp)
                  temp = temp/a(j, j)
                  CALL PUSHCONTROL1B(0)
                ELSE
                  CALL PUSHCONTROL1B(1)
                END IF
                CALL PUSHREAL4(x(j))
                x(j) = temp
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPREAL4(x(j))
                DO nd=1,nbdirs
                  tempb(nd) = xb(nd, j)
                  xb(nd, j) = 0.0
                ENDDO
                CALL POPCONTROL1B(branch)
                IF (branch .EQ. 0) THEN
                  CALL POPREAL4(temp)
                  DO nd=1,nbdirs
                    tempb(nd) = tempb0(nd)
                    ab(nd, j, j) = ab(nd, j, j) - temp*tempb0(nd)/a(j, j
     +                )
                  ENDDO
                END IF
                CALL POPINTEGER4(ad_to)
                DO i=ad_to,1,-1
                  DO nd=1,nbdirs
                    ab(nd, i, j) = ab(nd, i, j) - x(i)*tempb(nd)
                    xb(nd, i) = xb(nd, i) - a(i, j)*tempb(nd)
                  ENDDO
                ENDDO
                DO nd=1,nbdirs
                  xb(nd, j) = xb(nd, j) + tempb(nd)
                ENDDO
              ENDDO
            ELSE
              jx = kx
              DO j=1,n
                temp = x(jx)
                ix = kx
                DO i=1,j-1
                  temp = temp - a(i, j)*x(ix)
                  CALL PUSHINTEGER4(ix)
                  ix = ix + incx
                ENDDO
                CALL PUSHINTEGER4(i - 1)
                IF (nounit) THEN
                  CALL PUSHREAL4(temp)
                  temp = temp/a(j, j)
                  CALL PUSHCONTROL1B(0)
                ELSE
                  CALL PUSHCONTROL1B(1)
                END IF
                CALL PUSHREAL4(x(jx))
                x(jx) = temp
                CALL PUSHINTEGER4(jx)
                jx = jx + incx
              ENDDO
              DO ii1=1,ISIZE2OFa
                DO ii2=1,lda
                  DO nd=1,nbdirsmax
                    ab(nd, ii2, ii1) = 0.0
                  ENDDO
                ENDDO
              ENDDO
              DO j=n,1,-1
                CALL POPINTEGER4(jx)
                CALL POPREAL4(x(jx))
                DO nd=1,nbdirs
                  tempb(nd) = xb(nd, jx)
                  xb(nd, jx) = 0.0
                ENDDO
                CALL POPCONTROL1B(branch)
                IF (branch .EQ. 0) THEN
                  CALL POPREAL4(temp)
                  DO nd=1,nbdirs
                    tempb(nd) = tempb0(nd)
                    ab(nd, j, j) = ab(nd, j, j) - temp*tempb0(nd)/a(j, j
     +                )
                  ENDDO
                END IF
                CALL POPINTEGER4(ad_to0)
                DO i=ad_to0,1,-1
                  CALL POPINTEGER4(ix)
                  DO nd=1,nbdirs
                    ab(nd, i, j) = ab(nd, i, j) - x(ix)*tempb(nd)
                    xb(nd, ix) = xb(nd, ix) - a(i, j)*tempb(nd)
                  ENDDO
                ENDDO
                DO nd=1,nbdirs
                  xb(nd, jx) = xb(nd, jx) + tempb(nd)
                ENDDO
              ENDDO
            END IF
          ELSE IF (incx .EQ. 1) THEN
            DO j=n,1,-1
              temp = x(j)
              DO i=n,j+1,-1
                temp = temp - a(i, j)*x(i)
              ENDDO
              CALL PUSHINTEGER4(i + 1)
              IF (nounit) THEN
                CALL PUSHREAL4(temp)
                temp = temp/a(j, j)
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL4(x(j))
              x(j) = temp
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                DO nd=1,nbdirsmax
                  ab(nd, ii2, ii1) = 0.0
                ENDDO
              ENDDO
            ENDDO
            DO j=1,n,1
              CALL POPREAL4(x(j))
              DO nd=1,nbdirs
                tempb(nd) = xb(nd, j)
                xb(nd, j) = 0.0
              ENDDO
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL4(temp)
                DO nd=1,nbdirs
                  tempb(nd) = tempb0(nd)
                  ab(nd, j, j) = ab(nd, j, j) - temp*tempb0(nd)/a(j, j)
                ENDDO
              END IF
              CALL POPINTEGER4(ad_to1)
              DO i=ad_to1,n,1
                DO nd=1,nbdirs
                  ab(nd, i, j) = ab(nd, i, j) - x(i)*tempb(nd)
                  xb(nd, i) = xb(nd, i) - a(i, j)*tempb(nd)
                ENDDO
              ENDDO
              DO nd=1,nbdirs
                xb(nd, j) = xb(nd, j) + tempb(nd)
              ENDDO
            ENDDO
          ELSE
            kx = kx + (n-1)*incx
            jx = kx
            DO j=n,1,-1
              temp = x(jx)
              ix = kx
              DO i=n,j+1,-1
                temp = temp - a(i, j)*x(ix)
                CALL PUSHINTEGER4(ix)
                ix = ix - incx
              ENDDO
              CALL PUSHINTEGER4(i + 1)
              IF (nounit) THEN
                CALL PUSHREAL4(temp)
                temp = temp/a(j, j)
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL4(x(jx))
              x(jx) = temp
              CALL PUSHINTEGER4(jx)
              jx = jx - incx
            ENDDO
            DO ii1=1,ISIZE2OFa
              DO ii2=1,lda
                DO nd=1,nbdirsmax
                  ab(nd, ii2, ii1) = 0.0
                ENDDO
              ENDDO
            ENDDO
            DO j=1,n,1
              CALL POPINTEGER4(jx)
              CALL POPREAL4(x(jx))
              DO nd=1,nbdirs
                tempb(nd) = xb(nd, jx)
                xb(nd, jx) = 0.0
              ENDDO
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL4(temp)
                DO nd=1,nbdirs
                  tempb(nd) = tempb0(nd)
                  ab(nd, j, j) = ab(nd, j, j) - temp*tempb0(nd)/a(j, j)
                ENDDO
              END IF
              CALL POPINTEGER4(ad_to2)
              DO i=ad_to2,n,1
                CALL POPINTEGER4(ix)
                DO nd=1,nbdirs
                  ab(nd, i, j) = ab(nd, i, j) - x(ix)*tempb(nd)
                  xb(nd, ix) = xb(nd, ix) - a(i, j)*tempb(nd)
                ENDDO
              ENDDO
              DO nd=1,nbdirs
                xb(nd, jx) = xb(nd, jx) + tempb(nd)
              ENDDO
            ENDDO
          END IF
          CALL POPCONTROL1B(branch)
        END IF
      END IF
      CALL POPCONTROL3B(branch)
      END

