C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of zdotc in forward (tangent) mode:
C   variations   of useful results: zdotc
C   with respect to varying inputs: zx zy
C   RW status of diff variables: zx:in zy:in zdotc:out
C> \brief \b ZDOTC
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       COMPLEX*16 FUNCTION ZDOTC(N,ZX,INCX,ZY,INCY)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,INCY,N
C       ..
C       .. Array Arguments ..
C       COMPLEX*16 ZX(*),ZY(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> ZDOTC forms the dot product of two complex vectors
C>      ZDOTC = X^H * Y
C>
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>         number of elements in input vector(s)
C> \endverbatim
C>
C> \param[in] ZX
C> \verbatim
C>          ZX is COMPLEX*16 array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>         storage spacing between elements of ZX
C> \endverbatim
C>
C> \param[in] ZY
C> \verbatim
C>          ZY is COMPLEX*16 array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>         storage spacing between elements of ZY
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup dot
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>     jack dongarra, 3/11/78.
C>     modified 12/3/93, array(1) declarations changed to array(*)
C> \endverbatim
C>
C  =====================================================================
      COMPLEX*16 FUNCTION ZDOTC_D(n, zx, zxd, incx, zy, zyd, incy, zdotc
     +)
      IMPLICIT NONE
C
C  -- Reference BLAS level1 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, incy, n
C     ..
C     .. Array Arguments ..
      COMPLEX*16 zx(*), zy(*)
      COMPLEX*16 zxd(*), zyd(*)
C     ..
C
C  =====================================================================
C
C     .. Local Scalars ..
      COMPLEX*16 ztemp
      COMPLEX*16 ztempd
      INTEGER i, ix, iy
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC DCONJG
      DOUBLE COMPLEX temp
      COMPLEX*16 zdotc
C     ..
      ztemp = (0.0d0,0.0d0)
      zdotc = (0.0d0,0.0d0)
      IF (n .LE. 0) THEN
        zdotc_d = (0.0,0.0)
        RETURN
      ELSE
        IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
          ztempd = (0.0,0.0)
C
C        code for both increments equal to 1
C
          DO i=1,n
            temp = DCONJG(zx(i))
            ztempd = ztempd + zy(i)*DCONJG(zxd(i)) + temp*zyd(i)
            ztemp = ztemp + temp*zy(i)
          ENDDO
        ELSE
C
C        code for unequal increments or equal increments
C          not equal to 1
C
          ix = 1
          iy = 1
          IF (incx .LT. 0) ix = (-n+1)*incx + 1
          IF (incy .LT. 0) THEN
            iy = (-n+1)*incy + 1
            ztempd = (0.0,0.0)
          ELSE
            ztempd = (0.0,0.0)
          END IF
          DO i=1,n
            temp = DCONJG(zx(ix))
            ztempd = ztempd + zy(iy)*DCONJG(zxd(ix)) + temp*zyd(iy)
            ztemp = ztemp + temp*zy(iy)
            ix = ix + incx
            iy = iy + incy
          ENDDO
        END IF
        zdotc_d = ztempd
        zdotc = ztemp
        RETURN
C
C     End of ZDOTC
C
      END IF
      END

