C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of zhbmv in forward (tangent) mode:
C   variations   of useful results: y
C   with respect to varying inputs: alpha x y beta a
C   RW status of diff variables: alpha:in x:in y:in-out beta:in
C                a:in
C> \brief \b ZHBMV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE ZHBMV(UPLO,N,K,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
C
C       .. Scalar Arguments ..
C       COMPLEX*16 ALPHA,BETA
C       INTEGER INCX,INCY,K,LDA,N
C       CHARACTER UPLO
C       ..
C       .. Array Arguments ..
C       COMPLEX*16 A(LDA,*),X(*),Y(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> ZHBMV  performs the matrix-vector  operation
C>
C>    y := alpha*A*x + beta*y,
C>
C> where alpha and beta are scalars, x and y are n element vectors and
C> A is an n by n hermitian band matrix, with k super-diagonals.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the upper or lower
C>           triangular part of the band matrix A is being supplied as
C>           follows:
C>
C>              UPLO = 'U' or 'u'   The upper triangular part of A is
C>                                  being supplied.
C>
C>              UPLO = 'L' or 'l'   The lower triangular part of A is
C>                                  being supplied.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the order of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] K
C> \verbatim
C>          K is INTEGER
C>           On entry, K specifies the number of super-diagonals of the
C>           matrix A. K must satisfy  0 .le. K.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is COMPLEX*16
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is COMPLEX*16 array, dimension ( LDA, N )
C>           Before entry with UPLO = 'U' or 'u', the leading ( k + 1 )
C>           by n part of the array A must contain the upper triangular
C>           band part of the hermitian matrix, supplied column by
C>           column, with the leading diagonal of the matrix in row
C>           ( k + 1 ) of the array, the first super-diagonal starting at
C>           position 2 in row k, and so on. The top left k by k triangle
C>           of the array A is not referenced.
C>           The following program segment will transfer the upper
C>           triangular part of a hermitian band matrix from conventional
C>           full matrix storage to band storage:
C>
C>                 DO 20, J = 1, N
C>                    M = K + 1 - J
C>                    DO 10, I = MAX( 1, J - K ), J
C>                       A( M + I, J ) = matrix( I, J )
C>              10    CONTINUE
C>              20 CONTINUE
C>
C>           Before entry with UPLO = 'L' or 'l', the leading ( k + 1 )
C>           by n part of the array A must contain the lower triangular
C>           band part of the hermitian matrix, supplied column by
C>           column, with the leading diagonal of the matrix in row 1 of
C>           the array, the first sub-diagonal starting at position 1 in
C>           row 2, and so on. The bottom right k by k triangle of the
C>           array A is not referenced.
C>           The following program segment will transfer the lower
C>           triangular part of a hermitian band matrix from conventional
C>           full matrix storage to band storage:
C>
C>                 DO 20, J = 1, N
C>                    M = 1 - J
C>                    DO 10, I = J, MIN( N, J + K )
C>                       A( M + I, J ) = matrix( I, J )
C>              10    CONTINUE
C>              20 CONTINUE
C>
C>           Note that the imaginary parts of the diagonal elements need
C>           not be set and are assumed to be zero.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           ( k + 1 ).
C> \endverbatim
C>
C> \param[in] X
C> \verbatim
C>          X is COMPLEX*16 array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the
C>           vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is COMPLEX*16
C>           On entry, BETA specifies the scalar beta.
C> \endverbatim
C>
C> \param[in,out] Y
C> \verbatim
C>          Y is COMPLEX*16 array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCY ) ).
C>           Before entry, the incremented array Y must contain the
C>           vector y. On exit, Y is overwritten by the updated vector y.
C> \endverbatim
C>
C> \param[in] INCY
C> \verbatim
C>          INCY is INTEGER
C>           On entry, INCY specifies the increment for the elements of
C>           Y. INCY must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup hbmv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>  The vector and matrix arguments are not referenced when N = 0, or M = 0
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE ZHBMV_D(uplo, n, k, alpha, alphad, a, ad, lda, x, xd, 
     +                   incx, beta, betad, y, yd, incy)
      IMPLICIT NONE
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      COMPLEX*16 alpha, beta
      COMPLEX*16 alphad, betad
      INTEGER incx, incy, k, lda, n
      CHARACTER uplo
C     ..
C     .. Array Arguments ..
      COMPLEX*16 a(lda, *), x(*), y(*)
      COMPLEX*16 ad(lda, *), xd(*), yd(*)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      COMPLEX*16 one
      PARAMETER (one=(1.0d+0,0.0d+0))
      COMPLEX*16 zero
      PARAMETER (zero=(0.0d+0,0.0d+0))
C     ..
C     .. Local Scalars ..
      COMPLEX*16 temp1, temp2
      COMPLEX*16 temp1d, temp2d
      INTEGER i, info, ix, iy, j, jx, jy, kplus1, kx, ky, l
      EXTERNAL LSAME
C     ..
C     .. External Functions ..
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC DBLE, DCONJG, MAX, MIN
      INTEGER max1
      INTEGER max2
      INTEGER min1
      INTEGER min2
      DOUBLE COMPLEX temp
      DOUBLE PRECISION temp0
C     ..
C
C     Test the input parameters.
C
      info = 0
      IF (.NOT.LSAME(uplo, 'U') .AND. (.NOT.LSAME(uplo, 'L'))) THEN
        info = 1
      ELSE IF (n .LT. 0) THEN
        info = 2
      ELSE IF (k .LT. 0) THEN
        info = 3
      ELSE IF (lda .LT. k + 1) THEN
        info = 6
      ELSE IF (incx .EQ. 0) THEN
        info = 8
      ELSE IF (incy .EQ. 0) THEN
        info = 11
      END IF
      IF (info .NE. 0) THEN
        CALL XERBLA('ZHBMV ', info)
        RETURN
      ELSE IF (n .EQ. 0 .OR. (alpha .EQ. zero .AND. beta .EQ. one)) THEN
C
C     Quick return if possible.
C
        RETURN
      ELSE
C
C     Set up the start points in  X  and  Y.
C
        IF (incx .GT. 0) THEN
          kx = 1
        ELSE
          kx = 1 - (n-1)*incx
        END IF
        IF (incy .GT. 0) THEN
          ky = 1
        ELSE
          ky = 1 - (n-1)*incy
        END IF
C
C     Start the operations. In this version the elements of the array A
C     are accessed sequentially with one pass through A.
C
C     First form  y := beta*y.
C
        IF (beta .NE. one) THEN
          IF (incy .EQ. 1) THEN
            IF (beta .EQ. zero) THEN
              DO i=1,n
                yd(i) = 0.0
                y(i) = zero
              ENDDO
            ELSE
              DO i=1,n
                yd(i) = y(i)*betad + beta*yd(i)
                y(i) = beta*y(i)
              ENDDO
            END IF
          ELSE
            iy = ky
            IF (beta .EQ. zero) THEN
              DO i=1,n
                yd(iy) = 0.0
                y(iy) = zero
                iy = iy + incy
              ENDDO
            ELSE
              DO i=1,n
                yd(iy) = y(iy)*betad + beta*yd(iy)
                y(iy) = beta*y(iy)
                iy = iy + incy
              ENDDO
            END IF
          END IF
        END IF
        IF (alpha .EQ. zero) THEN
          RETURN
        ELSE
          IF (LSAME(uplo, 'U')) THEN
C
C        Form  y  when upper triangle of A is stored.
C
            kplus1 = k + 1
            IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
              DO j=1,n
                temp1d = x(j)*alphad + alpha*xd(j)
                temp1 = alpha*x(j)
                temp2 = zero
                l = kplus1 - j
                IF (1 .LT. j - k) THEN
                  max1 = j - k
                  temp2d = (0.0,0.0)
                ELSE
                  max1 = 1
                  temp2d = (0.0,0.0)
                END IF
                DO i=max1,j-1
                  yd(i) = yd(i) + a(l+i, j)*temp1d + temp1*ad(l+i, j)
                  y(i) = y(i) + temp1*a(l+i, j)
                  temp = DCONJG(a(l+i, j))
                  temp2d = temp2d + x(i)*DCONJG(ad(l+i, j)) + temp*xd(i)
                  temp2 = temp2 + temp*x(i)
                ENDDO
                temp0 = DBLE(a(kplus1, j))
                yd(j) = yd(j) + temp0*temp1d + temp1*DBLE(ad(kplus1, j))
     +            + temp2*alphad + alpha*temp2d
                y(j) = y(j) + temp1*temp0 + alpha*temp2
              ENDDO
            ELSE
              jx = kx
              jy = ky
              DO j=1,n
                temp1d = x(jx)*alphad + alpha*xd(jx)
                temp1 = alpha*x(jx)
                temp2 = zero
                ix = kx
                iy = ky
                l = kplus1 - j
                IF (1 .LT. j - k) THEN
                  max2 = j - k
                  temp2d = (0.0,0.0)
                ELSE
                  max2 = 1
                  temp2d = (0.0,0.0)
                END IF
                DO i=max2,j-1
                  yd(iy) = yd(iy) + a(l+i, j)*temp1d + temp1*ad(l+i, j)
                  y(iy) = y(iy) + temp1*a(l+i, j)
                  temp = DCONJG(a(l+i, j))
                  temp2d = temp2d + x(ix)*DCONJG(ad(l+i, j)) + temp*xd(
     +              ix)
                  temp2 = temp2 + temp*x(ix)
                  ix = ix + incx
                  iy = iy + incy
                ENDDO
                temp0 = DBLE(a(kplus1, j))
                yd(jy) = yd(jy) + temp0*temp1d + temp1*DBLE(ad(kplus1, j
     +            )) + temp2*alphad + alpha*temp2d
                y(jy) = y(jy) + temp1*temp0 + alpha*temp2
                jx = jx + incx
                jy = jy + incy
                IF (j .GT. k) THEN
                  kx = kx + incx
                  ky = ky + incy
                END IF
              ENDDO
            END IF
          ELSE IF (incx .EQ. 1 .AND. incy .EQ. 1) THEN
C
C        Form  y  when lower triangle of A is stored.
C
            DO j=1,n
              temp1d = x(j)*alphad + alpha*xd(j)
              temp1 = alpha*x(j)
              temp2 = zero
              temp0 = DBLE(a(1, j))
              yd(j) = yd(j) + temp0*temp1d + temp1*DBLE(ad(1, j))
              y(j) = y(j) + temp1*temp0
              l = 1 - j
              IF (n .GT. j + k) THEN
                min1 = j + k
                temp2d = (0.0,0.0)
              ELSE
                min1 = n
                temp2d = (0.0,0.0)
              END IF
              DO i=j+1,min1
                yd(i) = yd(i) + a(l+i, j)*temp1d + temp1*ad(l+i, j)
                y(i) = y(i) + temp1*a(l+i, j)
                temp = DCONJG(a(l+i, j))
                temp2d = temp2d + x(i)*DCONJG(ad(l+i, j)) + temp*xd(i)
                temp2 = temp2 + temp*x(i)
              ENDDO
              yd(j) = yd(j) + temp2*alphad + alpha*temp2d
              y(j) = y(j) + alpha*temp2
            ENDDO
          ELSE
            jx = kx
            jy = ky
            DO j=1,n
              temp1d = x(jx)*alphad + alpha*xd(jx)
              temp1 = alpha*x(jx)
              temp2 = zero
              temp0 = DBLE(a(1, j))
              yd(jy) = yd(jy) + temp0*temp1d + temp1*DBLE(ad(1, j))
              y(jy) = y(jy) + temp1*temp0
              l = 1 - j
              ix = jx
              iy = jy
              IF (n .GT. j + k) THEN
                min2 = j + k
                temp2d = (0.0,0.0)
              ELSE
                min2 = n
                temp2d = (0.0,0.0)
              END IF
              DO i=j+1,min2
                ix = ix + incx
                iy = iy + incy
                yd(iy) = yd(iy) + a(l+i, j)*temp1d + temp1*ad(l+i, j)
                y(iy) = y(iy) + temp1*a(l+i, j)
                temp = DCONJG(a(l+i, j))
                temp2d = temp2d + x(ix)*DCONJG(ad(l+i, j)) + temp*xd(ix)
                temp2 = temp2 + temp*x(ix)
              ENDDO
              yd(jy) = yd(jy) + temp2*alphad + alpha*temp2d
              y(jy) = y(jy) + alpha*temp2
              jx = jx + incx
              jy = jy + incy
            ENDDO
          END IF
C
          RETURN
C
C     End of ZHBMV
C
        END IF
      END IF
      END

