C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of zsymm in forward (tangent) mode:
C   variations   of useful results: c
C   with respect to varying inputs: alpha beta a b c
C   RW status of diff variables: alpha:in beta:in a:in b:in c:in-out
C> \brief \b ZSYMM
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE ZSYMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
C
C       .. Scalar Arguments ..
C       COMPLEX*16 ALPHA,BETA
C       INTEGER LDA,LDB,LDC,M,N
C       CHARACTER SIDE,UPLO
C       ..
C       .. Array Arguments ..
C       COMPLEX*16 A(LDA,*),B(LDB,*),C(LDC,*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> ZSYMM  performs one of the matrix-matrix operations
C>
C>    C := alpha*A*B + beta*C,
C>
C> or
C>
C>    C := alpha*B*A + beta*C,
C>
C> where  alpha and beta are scalars, A is a symmetric matrix and  B and
C> C are m by n matrices.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] SIDE
C> \verbatim
C>          SIDE is CHARACTER*1
C>           On entry,  SIDE  specifies whether  the  symmetric matrix  A
C>           appears on the  left or right  in the  operation as follows:
C>
C>              SIDE = 'L' or 'l'   C := alpha*A*B + beta*C,
C>
C>              SIDE = 'R' or 'r'   C := alpha*B*A + beta*C,
C> \endverbatim
C>
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On  entry,   UPLO  specifies  whether  the  upper  or  lower
C>           triangular  part  of  the  symmetric  matrix   A  is  to  be
C>           referenced as follows:
C>
C>              UPLO = 'U' or 'u'   Only the upper triangular part of the
C>                                  symmetric matrix is to be referenced.
C>
C>              UPLO = 'L' or 'l'   Only the lower triangular part of the
C>                                  symmetric matrix is to be referenced.
C> \endverbatim
C>
C> \param[in] M
C> \verbatim
C>          M is INTEGER
C>           On entry,  M  specifies the number of rows of the matrix  C.
C>           M  must be at least zero.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the number of columns of the matrix C.
C>           N  must be at least zero.
C> \endverbatim
C>
C> \param[in] ALPHA
C> \verbatim
C>          ALPHA is COMPLEX*16
C>           On entry, ALPHA specifies the scalar alpha.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is COMPLEX*16 array, dimension ( LDA, ka ), where ka is
C>           m  when  SIDE = 'L' or 'l'  and is n  otherwise.
C>           Before entry  with  SIDE = 'L' or 'l',  the  m by m  part of
C>           the array  A  must contain the  symmetric matrix,  such that
C>           when  UPLO = 'U' or 'u', the leading m by m upper triangular
C>           part of the array  A  must contain the upper triangular part
C>           of the  symmetric matrix and the  strictly  lower triangular
C>           part of  A  is not referenced,  and when  UPLO = 'L' or 'l',
C>           the leading  m by m  lower triangular part  of the  array  A
C>           must  contain  the  lower triangular part  of the  symmetric
C>           matrix and the  strictly upper triangular part of  A  is not
C>           referenced.
C>           Before entry  with  SIDE = 'R' or 'r',  the  n by n  part of
C>           the array  A  must contain the  symmetric matrix,  such that
C>           when  UPLO = 'U' or 'u', the leading n by n upper triangular
C>           part of the array  A  must contain the upper triangular part
C>           of the  symmetric matrix and the  strictly  lower triangular
C>           part of  A  is not referenced,  and when  UPLO = 'L' or 'l',
C>           the leading  n by n  lower triangular part  of the  array  A
C>           must  contain  the  lower triangular part  of the  symmetric
C>           matrix and the  strictly upper triangular part of  A  is not
C>           referenced.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the  calling (sub) program. When  SIDE = 'L' or 'l'  then
C>           LDA must be at least  max( 1, m ), otherwise  LDA must be at
C>           least max( 1, n ).
C> \endverbatim
C>
C> \param[in] B
C> \verbatim
C>          B is COMPLEX*16 array, dimension ( LDB, N )
C>           Before entry, the leading  m by n part of the array  B  must
C>           contain the matrix B.
C> \endverbatim
C>
C> \param[in] LDB
C> \verbatim
C>          LDB is INTEGER
C>           On entry, LDB specifies the first dimension of B as declared
C>           in  the  calling  (sub)  program.   LDB  must  be  at  least
C>           max( 1, m ).
C> \endverbatim
C>
C> \param[in] BETA
C> \verbatim
C>          BETA is COMPLEX*16
C>           On entry,  BETA  specifies the scalar  beta.  When  BETA  is
C>           supplied as zero then C need not be set on input.
C> \endverbatim
C>
C> \param[in,out] C
C> \verbatim
C>          C is COMPLEX*16 array, dimension ( LDC, N )
C>           Before entry, the leading  m by n  part of the array  C must
C>           contain the matrix  C,  except when  beta  is zero, in which
C>           case C need not be set on entry.
C>           On exit, the array  C  is overwritten by the  m by n updated
C>           matrix.
C> \endverbatim
C>
C> \param[in] LDC
C> \verbatim
C>          LDC is INTEGER
C>           On entry, LDC specifies the first dimension of C as declared
C>           in  the  calling  (sub)  program.   LDC  must  be  at  least
C>           max( 1, m ).
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup hemm
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 3 Blas routine.
C>
C>  -- Written on 8-February-1989.
C>     Jack Dongarra, Argonne National Laboratory.
C>     Iain Duff, AERE Harwell.
C>     Jeremy Du Croz, Numerical Algorithms Group Ltd.
C>     Sven Hammarling, Numerical Algorithms Group Ltd.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE ZSYMM_D(side, uplo, m, n, alpha, alphad, a, ad, lda, b
     +                   , bd, ldb, beta, betad, c, cd, ldc)
      IMPLICIT NONE
C
C  -- Reference BLAS level3 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      COMPLEX*16 alpha, beta
      COMPLEX*16 alphad, betad
      INTEGER lda, ldb, ldc, m, n
      CHARACTER side, uplo
C     ..
C     .. Array Arguments ..
      COMPLEX*16 a(lda, *), b(ldb, *), c(ldc, *)
      COMPLEX*16 ad(lda, *), bd(ldb, *), cd(ldc, *)
      EXTERNAL LSAME
C     ..
C
C  =====================================================================
C
C     .. External Functions ..
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC MAX
C     ..
C     .. Local Scalars ..
      COMPLEX*16 temp1, temp2
      COMPLEX*16 temp1d, temp2d
      INTEGER i, info, j, k, nrowa
      LOGICAL upper
C     ..
C     .. Parameters ..
      COMPLEX*16 one
      PARAMETER (one=(1.0d+0,0.0d+0))
      COMPLEX*16 zero
      PARAMETER (zero=(0.0d+0,0.0d+0))
      INTEGER max1
      INTEGER max2
      INTEGER max3
C     ..
C
C     Set NROWA as the number of rows of A.
C
      IF (LSAME(side, 'L')) THEN
        nrowa = m
      ELSE
        nrowa = n
      END IF
      upper = LSAME(uplo, 'U')
C
C     Test the input parameters.
C
      info = 0
      IF (.NOT.LSAME(side, 'L') .AND. (.NOT.LSAME(side, 'R'))) THEN
        info = 1
      ELSE IF (.NOT.upper .AND. (.NOT.LSAME(uplo, 'L'))) THEN
        info = 2
      ELSE IF (m .LT. 0) THEN
        info = 3
      ELSE IF (n .LT. 0) THEN
        info = 4
      ELSE
        IF (1 .LT. nrowa) THEN
          max1 = nrowa
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          info = 7
        ELSE
          IF (1 .LT. m) THEN
            max2 = m
          ELSE
            max2 = 1
          END IF
          IF (ldb .LT. max2) THEN
            info = 9
          ELSE
            IF (1 .LT. m) THEN
              max3 = m
            ELSE
              max3 = 1
            END IF
            IF (ldc .LT. max3) info = 12
          END IF
        END IF
      END IF
      IF (info .NE. 0) THEN
        CALL XERBLA('ZSYMM ', info)
        RETURN
      ELSE IF ((m .EQ. 0 .OR. n .EQ. 0) .OR. (alpha .EQ. zero .AND. beta
     +    .EQ. one)) THEN
C
C     Quick return if possible.
C
        RETURN
      ELSE IF (alpha .EQ. zero) THEN
C
C     And when  alpha.eq.zero.
C
        IF (beta .EQ. zero) THEN
          DO j=1,n
            DO i=1,m
              cd(i, j) = 0.0
              c(i, j) = zero
            ENDDO
          ENDDO
        ELSE
          DO j=1,n
            DO i=1,m
              cd(i, j) = c(i, j)*betad + beta*cd(i, j)
              c(i, j) = beta*c(i, j)
            ENDDO
          ENDDO
        END IF
        RETURN
      ELSE
C
C     Start the operations.
C
        IF (LSAME(side, 'L')) THEN
C
C        Form  C := alpha*A*B + beta*C.
C
          IF (upper) THEN
            DO j=1,n
              DO i=1,m
                temp1d = b(i, j)*alphad + alpha*bd(i, j)
                temp1 = alpha*b(i, j)
                temp2 = zero
                temp2d = (0.0,0.0)
                DO k=1,i-1
                  cd(k, j) = cd(k, j) + a(k, i)*temp1d + temp1*ad(k, i)
                  c(k, j) = c(k, j) + temp1*a(k, i)
                  temp2d = temp2d + a(k, i)*bd(k, j) + b(k, j)*ad(k, i)
                  temp2 = temp2 + b(k, j)*a(k, i)
                ENDDO
                IF (beta .EQ. zero) THEN
                  cd(i, j) = a(i, i)*temp1d + temp1*ad(i, i) + temp2*
     +              alphad + alpha*temp2d
                  c(i, j) = temp1*a(i, i) + alpha*temp2
                ELSE
                  cd(i, j) = c(i, j)*betad + beta*cd(i, j) + a(i, i)*
     +              temp1d + temp1*ad(i, i) + temp2*alphad + alpha*
     +              temp2d
                  c(i, j) = beta*c(i, j) + temp1*a(i, i) + alpha*temp2
                END IF
              ENDDO
            ENDDO
          ELSE
            DO j=1,n
              DO i=m,1,-1
                temp1d = b(i, j)*alphad + alpha*bd(i, j)
                temp1 = alpha*b(i, j)
                temp2 = zero
                temp2d = (0.0,0.0)
                DO k=i+1,m
                  cd(k, j) = cd(k, j) + a(k, i)*temp1d + temp1*ad(k, i)
                  c(k, j) = c(k, j) + temp1*a(k, i)
                  temp2d = temp2d + a(k, i)*bd(k, j) + b(k, j)*ad(k, i)
                  temp2 = temp2 + b(k, j)*a(k, i)
                ENDDO
                IF (beta .EQ. zero) THEN
                  cd(i, j) = a(i, i)*temp1d + temp1*ad(i, i) + temp2*
     +              alphad + alpha*temp2d
                  c(i, j) = temp1*a(i, i) + alpha*temp2
                ELSE
                  cd(i, j) = c(i, j)*betad + beta*cd(i, j) + a(i, i)*
     +              temp1d + temp1*ad(i, i) + temp2*alphad + alpha*
     +              temp2d
                  c(i, j) = beta*c(i, j) + temp1*a(i, i) + alpha*temp2
                END IF
              ENDDO
            ENDDO
          END IF
        ELSE
C
C        Form  C := alpha*B*A + beta*C.
C
          DO j=1,n
            temp1d = a(j, j)*alphad + alpha*ad(j, j)
            temp1 = alpha*a(j, j)
            IF (beta .EQ. zero) THEN
              DO i=1,m
                cd(i, j) = b(i, j)*temp1d + temp1*bd(i, j)
                c(i, j) = temp1*b(i, j)
              ENDDO
            ELSE
              DO i=1,m
                cd(i, j) = c(i, j)*betad + beta*cd(i, j) + b(i, j)*
     +            temp1d + temp1*bd(i, j)
                c(i, j) = beta*c(i, j) + temp1*b(i, j)
              ENDDO
            END IF
            DO k=1,j-1
              IF (upper) THEN
                temp1d = a(k, j)*alphad + alpha*ad(k, j)
                temp1 = alpha*a(k, j)
              ELSE
                temp1d = a(j, k)*alphad + alpha*ad(j, k)
                temp1 = alpha*a(j, k)
              END IF
              DO i=1,m
                cd(i, j) = cd(i, j) + b(i, k)*temp1d + temp1*bd(i, k)
                c(i, j) = c(i, j) + temp1*b(i, k)
              ENDDO
            ENDDO
            DO k=j+1,n
              IF (upper) THEN
                temp1d = a(j, k)*alphad + alpha*ad(j, k)
                temp1 = alpha*a(j, k)
              ELSE
                temp1d = a(k, j)*alphad + alpha*ad(k, j)
                temp1 = alpha*a(k, j)
              END IF
              DO i=1,m
                cd(i, j) = cd(i, j) + b(i, k)*temp1d + temp1*bd(i, k)
                c(i, j) = c(i, j) + temp1*b(i, k)
              ENDDO
            ENDDO
          ENDDO
        END IF
C
        RETURN
C
C     End of ZSYMM
C
      END IF
      END

