C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) -  6 Jan 2026 19:07
C
C  Differentiation of ztrmv in forward (tangent) mode:
C   variations   of useful results: x
C   with respect to varying inputs: x a
C   RW status of diff variables: x:in-out a:in
C> \brief \b ZTRMV
C
C  =========== DOCUMENTATION ===========
C
C Online html documentation available at
C            http://www.netlib.org/lapack/explore-html/
C
C  Definition:
C  ===========
C
C       SUBROUTINE ZTRMV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
C
C       .. Scalar Arguments ..
C       INTEGER INCX,LDA,N
C       CHARACTER DIAG,TRANS,UPLO
C       ..
C       .. Array Arguments ..
C       COMPLEX*16 A(LDA,*),X(*)
C       ..
C
C
C> \par Purpose:
C  =============
C>
C> \verbatim
C>
C> ZTRMV  performs one of the matrix-vector operations
C>
C>    x := A*x,   or   x := A**T*x,   or   x := A**H*x,
C>
C> where x is an n element vector and  A is an n by n unit, or non-unit,
C> upper or lower triangular matrix.
C> \endverbatim
C
C  Arguments:
C  ==========
C
C> \param[in] UPLO
C> \verbatim
C>          UPLO is CHARACTER*1
C>           On entry, UPLO specifies whether the matrix is an upper or
C>           lower triangular matrix as follows:
C>
C>              UPLO = 'U' or 'u'   A is an upper triangular matrix.
C>
C>              UPLO = 'L' or 'l'   A is a lower triangular matrix.
C> \endverbatim
C>
C> \param[in] TRANS
C> \verbatim
C>          TRANS is CHARACTER*1
C>           On entry, TRANS specifies the operation to be performed as
C>           follows:
C>
C>              TRANS = 'N' or 'n'   x := A*x.
C>
C>              TRANS = 'T' or 't'   x := A**T*x.
C>
C>              TRANS = 'C' or 'c'   x := A**H*x.
C> \endverbatim
C>
C> \param[in] DIAG
C> \verbatim
C>          DIAG is CHARACTER*1
C>           On entry, DIAG specifies whether or not A is unit
C>           triangular as follows:
C>
C>              DIAG = 'U' or 'u'   A is assumed to be unit triangular.
C>
C>              DIAG = 'N' or 'n'   A is not assumed to be unit
C>                                  triangular.
C> \endverbatim
C>
C> \param[in] N
C> \verbatim
C>          N is INTEGER
C>           On entry, N specifies the order of the matrix A.
C>           N must be at least zero.
C> \endverbatim
C>
C> \param[in] A
C> \verbatim
C>          A is COMPLEX*16 array, dimension ( LDA, N ).
C>           Before entry with  UPLO = 'U' or 'u', the leading n by n
C>           upper triangular part of the array A must contain the upper
C>           triangular matrix and the strictly lower triangular part of
C>           A is not referenced.
C>           Before entry with UPLO = 'L' or 'l', the leading n by n
C>           lower triangular part of the array A must contain the lower
C>           triangular matrix and the strictly upper triangular part of
C>           A is not referenced.
C>           Note that when  DIAG = 'U' or 'u', the diagonal elements of
C>           A are not referenced either, but are assumed to be unity.
C> \endverbatim
C>
C> \param[in] LDA
C> \verbatim
C>          LDA is INTEGER
C>           On entry, LDA specifies the first dimension of A as declared
C>           in the calling (sub) program. LDA must be at least
C>           max( 1, n ).
C> \endverbatim
C>
C> \param[in,out] X
C> \verbatim
C>          X is COMPLEX*16 array, dimension at least
C>           ( 1 + ( n - 1 )*abs( INCX ) ).
C>           Before entry, the incremented array X must contain the n
C>           element vector x. On exit, X is overwritten with the
C>           transformed vector x.
C> \endverbatim
C>
C> \param[in] INCX
C> \verbatim
C>          INCX is INTEGER
C>           On entry, INCX specifies the increment for the elements of
C>           X. INCX must not be zero.
C> \endverbatim
C
C  Authors:
C  ========
C
C> \author Univ. of Tennessee
C> \author Univ. of California Berkeley
C> \author Univ. of Colorado Denver
C> \author NAG Ltd.
C
C> \ingroup trmv
C
C> \par Further Details:
C  =====================
C>
C> \verbatim
C>
C>  Level 2 Blas routine.
C>  The vector and matrix arguments are not referenced when N = 0, or M = 0
C>
C>  -- Written on 22-October-1986.
C>     Jack Dongarra, Argonne National Lab.
C>     Jeremy Du Croz, Nag Central Office.
C>     Sven Hammarling, Nag Central Office.
C>     Richard Hanson, Sandia National Labs.
C> \endverbatim
C>
C  =====================================================================
      SUBROUTINE ZTRMV_D(uplo, trans, diag, n, a, ad, lda, x, xd, incx)
      IMPLICIT NONE
C
C  -- Reference BLAS level2 routine --
C  -- Reference BLAS is a software package provided by Univ. of Tennessee,    --
C  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
C
C     .. Scalar Arguments ..
      INTEGER incx, lda, n
      CHARACTER diag, trans, uplo
C     ..
C     .. Array Arguments ..
      COMPLEX*16 a(lda, *), x(*)
      COMPLEX*16 ad(lda, *), xd(*)
C     ..
C
C  =====================================================================
C
C     .. Parameters ..
      COMPLEX*16 zero
      PARAMETER (zero=(0.0d+0,0.0d+0))
C     ..
C     .. Local Scalars ..
      COMPLEX*16 temp
      COMPLEX*16 tempd
      INTEGER i, info, ix, j, jx, kx
      LOGICAL noconj, nounit
      EXTERNAL LSAME
C     ..
C     .. External Functions ..
      LOGICAL LSAME
C     ..
C     .. External Subroutines ..
      EXTERNAL XERBLA
C     ..
C     .. Intrinsic Functions ..
      INTRINSIC DCONJG, MAX
      INTEGER max1
      DOUBLE COMPLEX temp0
C     ..
C
C     Test the input parameters.
C
      info = 0
      IF (.NOT.LSAME(uplo, 'U') .AND. (.NOT.LSAME(uplo, 'L'))) THEN
        info = 1
      ELSE IF (.NOT.LSAME(trans, 'N') .AND. (.NOT.LSAME(trans, 'T')) 
     +    .AND. (.NOT.LSAME(trans, 'C'))) THEN
        info = 2
      ELSE IF (.NOT.LSAME(diag, 'U') .AND. (.NOT.LSAME(diag, 'N'))) THEN
        info = 3
      ELSE IF (n .LT. 0) THEN
        info = 4
      ELSE
        IF (1 .LT. n) THEN
          max1 = n
        ELSE
          max1 = 1
        END IF
        IF (lda .LT. max1) THEN
          info = 6
        ELSE IF (incx .EQ. 0) THEN
          info = 8
        END IF
      END IF
      IF (info .NE. 0) THEN
        CALL XERBLA('ZTRMV ', info)
        RETURN
      ELSE IF (n .EQ. 0) THEN
C
C     Quick return if possible.
C
        RETURN
      ELSE
C
        noconj = LSAME(trans, 'T')
        nounit = LSAME(diag, 'N')
C
C     Set up the start point in X if the increment is not unity. This
C     will be  ( N - 1 )*INCX  too small for descending loops.
C
        IF (incx .LE. 0) THEN
          kx = 1 - (n-1)*incx
        ELSE IF (incx .NE. 1) THEN
          kx = 1
        END IF
C
C     Start the operations. In this version the elements of A are
C     accessed sequentially with one pass through A.
C
        IF (LSAME(trans, 'N')) THEN
C
C        Form  x := A*x.
C
          IF (LSAME(uplo, 'U')) THEN
            IF (incx .EQ. 1) THEN
              DO j=1,n
                IF (x(j) .NE. zero) THEN
                  tempd = xd(j)
                  temp = x(j)
                  DO i=1,j-1
                    xd(i) = xd(i) + a(i, j)*tempd + temp*ad(i, j)
                    x(i) = x(i) + temp*a(i, j)
                  ENDDO
                  IF (nounit) THEN
                    xd(j) = a(j, j)*xd(j) + x(j)*ad(j, j)
                    x(j) = x(j)*a(j, j)
                  END IF
                END IF
              ENDDO
            ELSE
              jx = kx
              DO j=1,n
                IF (x(jx) .NE. zero) THEN
                  tempd = xd(jx)
                  temp = x(jx)
                  ix = kx
                  DO i=1,j-1
                    xd(ix) = xd(ix) + a(i, j)*tempd + temp*ad(i, j)
                    x(ix) = x(ix) + temp*a(i, j)
                    ix = ix + incx
                  ENDDO
                  IF (nounit) THEN
                    xd(jx) = a(j, j)*xd(jx) + x(jx)*ad(j, j)
                    x(jx) = x(jx)*a(j, j)
                  END IF
                END IF
                jx = jx + incx
              ENDDO
            END IF
          ELSE IF (incx .EQ. 1) THEN
            DO j=n,1,-1
              IF (x(j) .NE. zero) THEN
                tempd = xd(j)
                temp = x(j)
                DO i=n,j+1,-1
                  xd(i) = xd(i) + a(i, j)*tempd + temp*ad(i, j)
                  x(i) = x(i) + temp*a(i, j)
                ENDDO
                IF (nounit) THEN
                  xd(j) = a(j, j)*xd(j) + x(j)*ad(j, j)
                  x(j) = x(j)*a(j, j)
                END IF
              END IF
            ENDDO
          ELSE
            kx = kx + (n-1)*incx
            jx = kx
            DO j=n,1,-1
              IF (x(jx) .NE. zero) THEN
                tempd = xd(jx)
                temp = x(jx)
                ix = kx
                DO i=n,j+1,-1
                  xd(ix) = xd(ix) + a(i, j)*tempd + temp*ad(i, j)
                  x(ix) = x(ix) + temp*a(i, j)
                  ix = ix - incx
                ENDDO
                IF (nounit) THEN
                  xd(jx) = a(j, j)*xd(jx) + x(jx)*ad(j, j)
                  x(jx) = x(jx)*a(j, j)
                END IF
              END IF
              jx = jx - incx
            ENDDO
          END IF
        ELSE IF (LSAME(uplo, 'U')) THEN
C
C        Form  x := A**T*x  or  x := A**H*x.
C
          IF (incx .EQ. 1) THEN
            DO j=n,1,-1
              tempd = xd(j)
              temp = x(j)
              IF (noconj) THEN
                IF (nounit) THEN
                  tempd = a(j, j)*tempd + temp*ad(j, j)
                  temp = temp*a(j, j)
                END IF
                DO i=j-1,1,-1
                  tempd = tempd + x(i)*ad(i, j) + a(i, j)*xd(i)
                  temp = temp + a(i, j)*x(i)
                ENDDO
              ELSE
                IF (nounit) THEN
                  temp0 = DCONJG(a(j, j))
                  tempd = temp0*tempd + temp*DCONJG(ad(j, j))
                  temp = temp*temp0
                END IF
                DO i=j-1,1,-1
                  temp0 = DCONJG(a(i, j))
                  tempd = tempd + x(i)*DCONJG(ad(i, j)) + temp0*xd(i)
                  temp = temp + temp0*x(i)
                ENDDO
              END IF
              xd(j) = tempd
              x(j) = temp
            ENDDO
          ELSE
            jx = kx + (n-1)*incx
            DO j=n,1,-1
              tempd = xd(jx)
              temp = x(jx)
              ix = jx
              IF (noconj) THEN
                IF (nounit) THEN
                  tempd = a(j, j)*tempd + temp*ad(j, j)
                  temp = temp*a(j, j)
                END IF
                DO i=j-1,1,-1
                  ix = ix - incx
                  tempd = tempd + x(ix)*ad(i, j) + a(i, j)*xd(ix)
                  temp = temp + a(i, j)*x(ix)
                ENDDO
              ELSE
                IF (nounit) THEN
                  temp0 = DCONJG(a(j, j))
                  tempd = temp0*tempd + temp*DCONJG(ad(j, j))
                  temp = temp*temp0
                END IF
                DO i=j-1,1,-1
                  ix = ix - incx
                  temp0 = DCONJG(a(i, j))
                  tempd = tempd + x(ix)*DCONJG(ad(i, j)) + temp0*xd(ix)
                  temp = temp + temp0*x(ix)
                ENDDO
              END IF
              xd(jx) = tempd
              x(jx) = temp
              jx = jx - incx
            ENDDO
          END IF
        ELSE IF (incx .EQ. 1) THEN
          DO j=1,n
            tempd = xd(j)
            temp = x(j)
            IF (noconj) THEN
              IF (nounit) THEN
                tempd = a(j, j)*tempd + temp*ad(j, j)
                temp = temp*a(j, j)
              END IF
              DO i=j+1,n
                tempd = tempd + x(i)*ad(i, j) + a(i, j)*xd(i)
                temp = temp + a(i, j)*x(i)
              ENDDO
            ELSE
              IF (nounit) THEN
                temp0 = DCONJG(a(j, j))
                tempd = temp0*tempd + temp*DCONJG(ad(j, j))
                temp = temp*temp0
              END IF
              DO i=j+1,n
                temp0 = DCONJG(a(i, j))
                tempd = tempd + x(i)*DCONJG(ad(i, j)) + temp0*xd(i)
                temp = temp + temp0*x(i)
              ENDDO
            END IF
            xd(j) = tempd
            x(j) = temp
          ENDDO
        ELSE
          jx = kx
          DO j=1,n
            tempd = xd(jx)
            temp = x(jx)
            ix = jx
            IF (noconj) THEN
              IF (nounit) THEN
                tempd = a(j, j)*tempd + temp*ad(j, j)
                temp = temp*a(j, j)
              END IF
              DO i=j+1,n
                ix = ix + incx
                tempd = tempd + x(ix)*ad(i, j) + a(i, j)*xd(ix)
                temp = temp + a(i, j)*x(ix)
              ENDDO
            ELSE
              IF (nounit) THEN
                temp0 = DCONJG(a(j, j))
                tempd = temp0*tempd + temp*DCONJG(ad(j, j))
                temp = temp*temp0
              END IF
              DO i=j+1,n
                ix = ix + incx
                temp0 = DCONJG(a(i, j))
                tempd = tempd + x(ix)*DCONJG(ad(i, j)) + temp0*xd(ix)
                temp = temp + temp0*x(ix)
              ENDDO
            END IF
            xd(jx) = tempd
            x(jx) = temp
            jx = jx + incx
          ENDDO
        END IF
C
        RETURN
C
C     End of ZTRMV
C
      END IF
      END

